microsoft/Application-Insights-Workbooks

- Workbooks/TSG/Performance Counter TSG/Performance Counter TSG.workbook
- Workbooks/TSG/Performance Counter TSG/settings.json
- Workbooks/TSG/categoryResources.json
The gallery hotfix is now in PROD so I would like to publish this again.
> Added "TSG" back to template

- Workbooks/Azure Active Directory/Sign-ins Overview/SigninsOverview.workbook
- Workbooks/Azure Active Directory/Sign-ins Overview/settings.json
- Workbooks/Azure Active Directory/categoryResources.json
Created an initial template for integration testing purpose for Azure Active Directory
> Initial commit for Azure Active Directory templates

- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/Security and Audit.workbook
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/settings.json
Port over various charts from OMS Security and Audit panel
> First draft of Security and Audit workbook

- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/settings.json
I have kept the name as "Performance Counters", will check with PMs tomorrow and if they suggest a different name, I will update it.
> Performance Counters Workbook

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a group of VMs/Performance Analysis for a group of VMs.workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a group of VMs/settings.json
Temporary hotfix to mitigate problems accessing workbook
> Add duplicate workbook for mitigation

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/Performance Analysis for a Single VM.workbook
Update description text and select a default counter so the workbook
doesn't show a broken view when opened from gallery.
> Fix Single VM Perf Analysis workbook

- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
Remove helper text and shrink size of the table. Add disclaimer text to
warn user if they need to onboard or if there is no data in
`VMConnection`
Preview:
> Streamline Connections Overview workbook

- Workbooks/Performance/Single Page Application Insights/Single Page Application Website Insights.workbook
- Workbooks/Performance/Single Page Application Insights/settings.json
This is a pull request to put in a workbook for the Mezzurite Timing Library.  We have shown this workbook to Arun and John.
> Adding a Workbook for Single Page Application Websites

- Workbooks/Performance/Single Page Application Insights/Single Page Application Website Insights.workbook
Locking the workbook from edits.
> locking workbook

- Workbooks/Virtual Machines - Network Dependencies/Failed Connections/Failed Connections.workbook
- Workbooks/Virtual Machines - Network Dependencies/Failed Connections/settings.json
- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/TCP Traffic.workbook
- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/settings.json
TCP Traffic
Failed Connections
> Add TCP Traffic and Failed Connections workbook

- Workbooks/Virtual Machines - Network Dependencies/Connection Records/Connection Records.workbook
- Workbooks/Virtual Machines - Network Dependencies/Connection Records/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/Security and Audit.workbook
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/Traffic Comparison.workbook
- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/settings.json
- Workbooks/Virtual Machines - Network Dependencies/VM Events/VM Events.workbook
- Workbooks/Virtual Machines - Network Dependencies/VM Events/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook
- Workbooks/Virtual Machines - Performance Analysis/Resource Monitor/Resource Monitor.workbook
- Workbooks/Virtual Machines - Performance Analysis/Resource Monitor/settings.json
Some workbooks will be hidden behind
`feature.includePreviewTemplates=true` feature flag
AtScale
AtScale (preview included)
SingleVM
> Publish draft workbooks for VM Insights

- Workbooks/Azure Monitor - Applications/Failure Analysis/Failure Analysis.workbook
Allow only single subs and some viz changes
> Slight update to failure template

- Workbooks/TSG/Performance Counter TSG/Performance Counter TSG.workbook
To clarify a possible cause of issues. Addresses issue https://github.com/Microsoft/Application-Insights-Workbooks/issues/148
> Update the perf counter TSG

- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
Made test query parameter simpler hopefully to improve performance upon
initialization. Fixes #146
> Fix custom time range

- Workbooks/Azure Active Directory TroubleShooting/SignInFailureAnalysis/SignInFailureAnalysis.workbook
- Workbooks/Azure Active Directory TroubleShooting/categoryResources.json
- Workbooks/Azure Active Directory/SignIns/SignIns.workbook
- Workbooks/Azure Active Directory/SignInsAndConditionalAccess/SignInsAndConditionalAccess.workbook
- Workbooks/Azure Active Directory/SignInsUsingLegacyAuth/SignIns.workbook
* Better parameters - uses the built-in All option instead of manually creating that group. Link time range parameters.
* Link Users parameters to queries.
* Add link to see sign-in details
> Fix some issues in the AAD templates and add detail links

- Workbooks/CosmosDb/Overview/Overview.workbook
- Workbooks/Storage/Overview/Overview.workbook
Metric Grid has a new  version
added resource count tile 
added conditional visibility to resource name
> Changed Grid, resource count

- Workbooks/Workspace/Agent Health/Agent Health.workbook
- Workbooks/Workspace/Agent Health/settings.json
- Workbooks/Workspace/Workspace Usage/Workspace Usage.workbook
- Workbooks/Workspace/Workspace Usage/settings.json
- Workbooks/Workspace/categoryResources.json
Adding following workbooks for workspace resource type:
- Workspace Usage
- Agent Health
> Adds two workbooks for workspaces.

- test/jsonValidationTest.js
this pr should fail to validate because there's a workbook that is failing this validation.
so this proves that the test works, then I can fix the workbook in a different pr, then this should work to validate.
> attempting resource id validation

- Workbooks/Storage/Overview/Overview.workbook
> Update at-scale Storage overview

- Workbooks/AKS/Node-Disk/Node-Disk.workbook
- Workbooks/AKS/Node-Disk/settings.json
- Workbooks/AKS/categoryResources.json
Adding disk workbook for container insights ahead of releasing ci integration with workbooks
> added disk workbook

- Workbooks/Virtual Machines - Network Dependencies/Active Ports/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connection Records/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Failed Connections/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Open Ports/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/settings.json
- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/settings.json
- Workbooks/Virtual Machines - Network Dependencies/VM Events/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Resource Monitor/settings.json
This is part of the effort to eventually move VM Insights workbooks from type `workbook` to type `vm-insights`
> Add vm-insights gallery to VM Insights workbooks

- Workbooks/Individual Storage/Availability/Availability.workbook
- Workbooks/Individual Storage/Availability/settings.json
- Workbooks/Individual Storage/Capacity/Capacity.workbook
- Workbooks/Individual Storage/Capacity/settings.json
- Workbooks/Individual Storage/Failures/Failures.workbook
- Workbooks/Individual Storage/Failures/settings.json
- Workbooks/Individual Storage/Overview/Overview.workbook
- Workbooks/Individual Storage/Performance/Performance.workbook
- Workbooks/Individual Storage/Performance/settings.json
- Workbooks/Storage/Overview/Overview.workbook
> Update storae templates

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook
Added Search:
Fixed Network grid: Now showing all counters, and fixed aggregation.
> Add search to performance workbook

- Workbooks/Storage/Overview/Overview.workbook
> Group by subs and misc fixes

- Workbooks/Virtual Machine Scale Sets - Network Dependencies/Active Ports/settings.json
- Workbooks/Virtual Machine Scale Sets - Network Dependencies/Connections Overview/settings.json
- Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/settings.json
Add the remainder of the VM Insights workbooks to `vm-insights` workbook type
> Update the rest of the VM Insights workbook types

- Workbooks/Storage/Overview/Overview.workbook
> Update at-scale storage template to have grouping and links

- Workbooks/Storage/Capacity/Capacity.workbook
- Workbooks/Storage/Capacity/settings.json
> Add at-scale storage capcity template

- Workbooks/AKS/Node Disk Capacity AKS/Node Disk Capacity AKS.workbook
> Update Node Disk Capacity AKS.workbook

- Workbooks/Virtual Machines/VM details/VM details.workbook
- Workbooks/Virtual Machines/VM details/settings.json
Generic view that will be used to see individual VM details in a context menu from other reports.
> Add vm details template

- Workbooks/Individual Storage/Availability/Availability.workbook
- Workbooks/Individual Storage/Capacity/Capacity.workbook
- Workbooks/Individual Storage/Failures/Failures.workbook
- Workbooks/Individual Storage/Overview/Overview.workbook
- Workbooks/Individual Storage/Performance/Performance.workbook
- Workbooks/Resource Groups/Sql databases/Sql databases.workbook
- Workbooks/Resource Groups/Sql databases/settings.json
- Workbooks/Resource Groups/Storage Accounts/Storage Accounts.workbook
- Workbooks/Resource Groups/Virtual Machines/Virtual Machines.workbook
- Workbooks/Storage/Capacity/Capacity.workbook
- Workbooks/Storage/Overview/Overview.workbook
- Workbooks/Virtual Machines/At-scale Metrics/Key Metrics.workbook
1. Update VM and Storage templates to account for metric id changes.
2. Add learn more links to Storage templates
3. Add a SQL db template to resource groups.
> Changes to storage and rg templates

- Workbooks/Storage/Capacity/Capacity.workbook
- Workbooks/Storage/Overview/Overview.workbook
1. Also adds download to excel button to the grids
2. Removes link to single-storage insights
3. Removed default option in drop downs.
> Update at-scale storage template to have slightly better spacing

- Workbooks/Intune Reports/Device Compliance Trends/DeviceComplianceTrends.workbook
- Workbooks/Intune Reports/Device Compliance Trends/settings.json
- Workbooks/Intune Reports/categoryResources.json
> Adding Device Compliance Trends to Intune Reports

- Workbooks/Storage/Overview/Overview.workbook
> Storage Insights: Add resource limit

- Workbooks/Individual Storage/Availability/Availability.workbook
- Workbooks/Individual Storage/Overview/Overview.workbook
- Workbooks/Individual Storage/Performance/Performance.workbook
Give more meaningful step names to storage insights templates so we can track telemetry easier
> Storage Insights: Add missing step names

- Workbooks/Individual Storage/Availability/Availability.workbook
- Workbooks/Individual Storage/Capacity/Capacity.workbook
- Workbooks/Individual Storage/Failures/Failures.workbook
- Workbooks/Individual Storage/Overview/Overview.workbook
- Workbooks/Individual Storage/Performance/Performance.workbook
Removing a bunch of text steps and replacing them with margins. This will help with the template being less confusing in edit mode (not seeing random edit buttons everywhere).
> Storage Insights: Replace empty text steps with styling

- Workbooks/SapMonitor/SapHanaInfrastructure/SapHanaInfrastructure.workbook
- Workbooks/SapMonitor/SapHanaInfrastructure/settings.json
- Workbooks/SapMonitor/categoryResources.json
- Add file/folder structure
- Add basic template with utilization and forecast metrics
- Add `{LogAnalyticsWorkspaceArmId}` placeholder
> Initial version of SAP Monitor template

- Workbooks/Individual Storage/Capacity/Capacity.workbook
> Storage Insights: Change heatmap color to purplebluegreen

- Workbooks/CosmosDb/Overview/Overview.workbook
attempt to handle too many sub scenario
> changed from All sub to default sub

- Workbooks/Individual Storage/Failures/Failures.workbook
- Workbooks/Individual Storage/Overview/Overview.workbook
- Workbooks/Individual Storage/Performance/Performance.workbook
- Workbooks/Storage/Capacity/Capacity.workbook
- Workbooks/Storage/Overview/Overview.workbook
Individual Storage: Change tile setting if there is None or is single color, so that there exist a color.
Storage: time range required for both the overview and capacity
> change tile color for Individual SAI templates, time ranges required for at-scale templates

- Workbooks/Storage/Capacity/Capacity.workbook
- Workbooks/Storage/Overview/Overview.workbook
link to insights from Storage Accounts in Monitor
> storage(at-scale) - link to insights

- Workbooks/SapMonitor/SapHanaInfrastructure/SapHanaInfrastructure.workbook
- Cleaned up JSON (assigned meaningful step names)
- Added tabs for utilization, anomalies and host config
- Improved labels in KQL queries
> SAP Monitor infrastructure template v2

- Workbooks/CosmosDb/Overview/Overview.workbook
Add tabs to Cosmos DB template for overview and capacity.
Time required param changes.
> tabs, capacity and time unset changes

- Workbooks/Virtual Machine Scale Sets - Network Dependencies/Active Ports/settings.json
- Workbooks/Virtual Machine Scale Sets - Network Dependencies/Connections Overview/settings.json
- Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Active Ports/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connection Records/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Failed Connections/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Open Ports/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/settings.json
- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/settings.json
- Workbooks/Virtual Machines - Network Dependencies/VM Events/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Resource Monitor/settings.json
Update category (`settings.json`) for transition to new category and types for VM Insights workbooks. Existing categories will remain for now until transition is complete and will be removed in subsequent commit.
> Update category for VM Insights workbooks

- Workbooks/CosmosDb/Overview/Overview.workbook
New CosmosDB Capacity View:
palette changes, dropdown option changes, enable export to excel.
> cosmosDB insights capacity changes

- Workbooks/Network Insights/NetworkInsights-AppGatewayMetrics/NetworkInsights-AppGatewayMetrics.workbook
- Workbooks/Network Insights/NetworkInsights-AppGatewayMetrics/settings.json
1. Adding specific resource types for grid resource selection dropdowns
2. Changing the Application gateway metric chart size from "Full" to "Small"
> Adding specific resource types for grid resource selection dropdowns

- Workbooks/Network Insights/NetworkInsights-AppGatewayMetrics-Minified/NetworkInsights-AppGatewayMetrics-Minified.workbook
- Workbooks/Network Insights/NetworkInsights-AppGatewayMetrics/NetworkInsights-AppGatewayMetrics.workbook
Adding new parameters to achieve conditional visibility
> Adding new parameter to achieve conditional visibility

- Workbooks/Network Insights/NetworkInsights-AppGatewayMetrics-Minified/NetworkInsights-AppGatewayMetrics-Minified.workbook
- Workbooks/Network Insights/NetworkInsights-AppGatewayMetrics/NetworkInsights-AppGatewayMetrics.workbook
Moving conditional variables up in order
> Moving conditional variables up

- Workbooks/Azure Active Directory Conditional Access/Multiple Policy Insights (Preview)/multiplepolicyinsights.workbook
Reduced CA policy dropdown query time to 4 hours from 7 days and replaced User and App dropdowns with text parameters
> Simplified workbook parameters

- Documentation/Contributing.md
- schema/settings.json
add missing schema to settings.json example
add generated schema for settings.json
> add missing schema to example

- Workbooks/CosmosDb/Overview/Overview.workbook
> Update cosmos db insights template

- Workbooks/CosmosDb/Overview/Overview.workbook
> Add a Failures tab to CDI

- Workbooks/Azure Backup/Backup Explorer/settings.json
- Workbooks/Azure Backup/Backup Report/settings.json
Type change in settings for Azure backup templates.
New type: backup-insights
> Type change for Azure backup templates

- Workbooks/KeyVault/AzureMonitor/Insights/Insights.workbook
- Workbooks/KeyVault/AzureMonitor/Insights/settings.json
- Workbooks/KeyVault/Resource/Insights/Insights.workbook
- Workbooks/KeyVault/Resource/Insights/settings.json
- Workbooks/KeyVault/categoryResources.json
Template for Key Vault for Azure Monitor
> KeyVault Insight template

- Workbooks/CosmosDb/Overview/Overview.workbook
Removing third view from CDI, till third view bug is fixed.
> remove third view till third view bug is fixed

- Workbooks/Azure Backup/Backup Explorer/settings.json
- Workbooks/Azure Backup/Backup Report/settings.json
> [Azure backup] -  Iteration7

- Workbooks/CosmosDb/Overview/Overview.workbook
Moving cdi template to last iteration till metric 3rd view is in production.
> cdi to last iteration for proper formatting

- Workbooks/SapMonitor/SapHanaInfrastructure/SapHanaInfrastructure.workbook
**Problem**
- One customer of the Azure Monitor for SAP Solutions (preview) solution experienced an ingestion latency issue.
- More specifically, data ingested as custom log via Log Analytics Data Collection API took 30+ minutes to become available.
- This inconsistent behavior caused our Workbooks template to break, since we only check if data has been ingested in the last 30 minutes.
**Solution**
- To address this issue, the time range for the test query has been increased to 12 hours.
> [HOTFIX] Increase time range for test query to 12h

- Workbooks/CosmosDb/Overview/Overview.workbook
> metrics third view, CDI template.

- Workbooks/CosmosDb/Overview/Overview.workbook
- Workbooks/Virtual Machines/At-scale Metrics/Key Metrics.workbook
- Workbooks/Virtual Machines/CPU heatmap/CPU heatmap.workbook
ARG query without mvexpand for Cosmos, and Virtual machines templates.
> arg query without mvexpand

- Workbooks/CosmosDb/Overview/Overview.workbook
Add cosmos dbi step names, and add expand/collapse grid toolbar items
> CosmosDB Insights step names + expand button

- Workbooks/CosmosDb/Overview/Overview.workbook
> CDI - Default resource to 5 and metric (Usage (Request Units) ) remove from overview

- Workbooks/CosmosDb/Overview/Overview.workbook
Changes to CosmosDBI failures tab to look like keyvault insights
Note: Will probably change this again when filters are in prod
> Cosmos DB Insights Failures grid changes

- Workbooks/Individual Storage/Performance/Performance.workbook
Had two queue metrics, change one to missing file metric
> Storage Account Insights: Performance fix

- Workbooks/Individual Storage/Failures/Failures.workbook
Failing transactions by API name table was missing file and queue transactions
> Individual Storage Insights: Failure by API fix

- Workbooks/Azure Active Directory/SSPR Reset Funnel/SSPR Reset Funnel.workbook
Translator has reported possible source content issue. 
Description: ranage should be range
> M44341: Fixing typo ranage/range

- Workbooks/Storage/Overview/Overview.workbook
Default to 5 storage accounts and removing availability  from overview tab
> 5 accounts and removing availability - overview

- Workbooks/Azure Backup/Backup Explorer/Backup Explorer.workbook
fix build break - how did this get through the CI build which runs the same tests?
> fix build break

- Workbooks/Virtual Machine Scale Sets - Performance Analysis (Preview)/Virtual Machine Scale Sets - Performance Analysis (Preview).workbook
- Workbooks/Virtual Machine Scale Sets - Performance Analysis (Preview)/settings.json
Changed the charts in Perf Analysis workbook for VMSS to use InsightsMetrics
> Changed the query in VMSS Perf Analysis to use InsightsMetrics

- Workbooks/CosmosDb/Overview/Overview.workbook
>  cdi - remove failures from overview tab

- .pipelines/pipeline.user.windows.yml
- scripts/ProcessTemplates.ps1
- scripts/restoreDocs.cmd
- add script to clone localization repos during restore 
- remove de-de from language since repo is private and pipeline does not have access
- update pipeline build to generate json for each language
> add localization script to pipeline

- Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM (Preview)/Connections Overview.workbook
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM (Preview)/settings.json
Clean up non-onboarded case. Will promote this to production template once preview is verified.
Non-onboarded
Onboarded
> Improve onboarding check in Single VM Connections workbook

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/Performance Analysis for a Group of VMs (Dev).workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/settings.json
Improve onboarding check to also check for `ServiceMapComputer_CL`. Creating dev version of the workbook for testing in PROD, then will promote to production version once verified.
> Improve AtScale Performance onboarding check

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Azure Preview)/Performance Analysis for a Group of VMs (Azure Preview).workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Azure Preview)/settings.json
> Created Perf analysis workbook for Azure Mode

- Workbooks/View Designer/View Designer Transition Guide/Transition Guide.workbook
Updates related to [User Story 1668680](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1668680).
> Update Transition Guide.workbook

- Workbooks/Intune Audit/Audit/IntuneAuditActivity.workbook
The resolution of this change comes from here: https://github.com/microsoft/Application-Insights-Workbooks/pull/563
> C164290: Removing break-line to avoid display issues

- Workbooks/Intune Enrollment/Enrollment/IntuneEnrollment.workbook
The resolution of this change comes from here: https://github.com/microsoft/Application-Insights-Workbooks/pull/561
Related to this thread: #563
> C164292: Removing break-line to avoid display issues

- scripts/ProcessTemplates.ps1
$schema is needed for localization on categoryResources.json, however, it's causing ALM Integration processing so crash. need to investigate but this should resolve this issue and let loc continue
> ignore $schema

- Workbooks/Intune Compliance/Compliance/IntuneCompliance.workbook
This fix comes from here: https://github.com/microsoft/Application-Insights-Workbooks/pull/564
> C164291: Removing extra break-line

- .github/pull_request_template.md
hypothetically it gets used to create new PRs. too bad it didn't get used on this one as a sanity check?  anyway, this is what the default content will look like:
---
> add a pull request template to the repo

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/Performance Analysis for a Group of VMs (Dev).workbook
Ensure default subscription and a valid resource group is always
selected to prevent errors in the workbook upon initialization.
> Select default subscription and resource group

- CODEOWNERS
Add @rakshith210 and @microsoft/applicationinsights-devtools as code owners for Virtual Machine workbooks.
> Add additional code owners to VM workbooks

- Workbooks/Azure Active Directory TroubleShooting/ArchivedLogDateRange/ArchivedLogDateRange.workbook
This change adds the title to the Azure AD troubleshooting ArchivedLogDateRange workbook as discussed earlier today with D. Wood.
> add title to ArchivedLogDateRange.workbook

- Workbooks/Virtual Machines - Network Dependencies/Connections Overview (Dev)/Connections Overview (Dev).workbook
> Optimize top-level parameters for VM Connections

- Workbooks/Virtual Machines - Network Dependencies/Active Ports (Dev)/Active Ports (Dev).workbook
- Workbooks/Virtual Machines - Network Dependencies/Active Ports (Dev)/settings.json
Use the new scope selectors from #617
> Add Active Ports (Dev) workbook

- .github/pull_request_template.md
- Workbooks/App Hub/Cosmos Databases/Cosmos Databases.workbook
- Workbooks/CosmosDb/Overview/Overview.workbook
Change visibility parameter names+values to be more friendly
> CosmosDBI: Change conditional visibility names

- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook
> Made changes to Perf Counters workbook to make it work in Gallery for both modes

- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/Traffic Comparison.workbook
> Made changes to Traffic Comparison workbook to work in Gallery for both modes

- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/TCP Traffic.workbook
> Made changes to TCP traffic workbook to work in Gallery for both modes

- Workbooks/Virtual Machines - Network Dependencies/Open Ports/Open Ports.workbook
> Made changes to Open Port workbook to work in Gallery in both modes

- Workbooks/Virtual Machines - Network Dependencies/Active Ports/Active Ports.workbook
> Made changes to Active port workbook to work in Gallery for both modes

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook
Minor fix to perform ARG query over all subscriptions rather than just
the default subscriptions.
> Fix VM Insights Hybrid Performance workbook

- Workbooks/Virtual Machines - Network Dependencies/Connections Overview (Azure Preview)/Connections Overview (Azure Preview).workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Azure Preview)/Performance Analysis for a Group of VMs (Azure Preview).workbook
AtScale Performance workbook #617 
AtScale Connections workbook #618
> Promote Azure Preview workbooks

- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/Security and Audit.workbook
> Made changes to Security and Audit workbook to make it work in Gallery for both modes

- Workbooks/Virtual Machines - Network Dependencies/Active Ports/Active Ports.workbook
> Made changes to workspace query

- Workbooks/Virtual Machines - Network Dependencies/Active Ports/Active Ports.workbook
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
- Workbooks/Virtual Machines - Network Dependencies/Failed Connections/Failed Connections.workbook
- Workbooks/Virtual Machines - Network Dependencies/Open Ports/Open Ports.workbook
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/Security and Audit.workbook
- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/TCP Traffic.workbook
- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/Traffic Comparison.workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook
Modified the Workspace param query in the Hybrid workbooks
> Made changes to the Workspace param queries

- Workbooks/Network Insights/NetworkInsights-LoadBalancerMetrics/NetworkInsights-LoadBalancerMetrics.workbook
- Workbooks/Network Insights/NetworkInsights-LoadBalancerMetrics/settings.json
> Adding Load Balancer Metrics workbook for Network Insights

- Workbooks/Common/categoryResources.json
- Workbooks/Common/noSubscriptions/noSubscriptions.workbook
- Workbooks/Common/noSubscriptions/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Preview)/Performance Analysis for a Single VM.workbook
- Adding a 'No Subscriptions' templates, so that it can be loaded from any insights template
- The insights using this need to have a parameter called ResourceName to use render the resourceName in noSubscriptions workbook template
> No Subscriptions template

- Workbooks/Network Insights/NetworkInsights-LoadBalancerMetrics/NetworkInsights-LoadBalancerMetrics.workbook
> Updating no metric available message for basic LB

- Workbooks/AKS/Node GPU/Node GPU.workbook
- Workbooks/AKS/Node GPU/settings.json
* [* ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
This PR adds a new worrbook that shows the new GPU metrics we started collecting for Kubernetes clusters (AKS & non-AKS clusters) - [see below for a screen]
> Add GPU workbook

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Perf)/Performance Analysis for a Group of VMs.workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Perf)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Preview)/Performance Analysis for a Group of VMs (Preview).workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/settings.json
- Workbooks/Virtual Machines - Performance Analysis/categoryResources.json
- Workbooks/categoryResources.json
Create backup template that uses traditional Perf table.
Test
--
Pass in a workspace not present in default subscription
> Update VM Insights Perf Hybrid workbook

- Documentation/DataSources/DataSources.md
fix markdown table layout and link for alerts datasource
> fix table layout and link for alerts datasource

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Perf)/Performance Analysis for a Single VM (Perf).workbook
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Perf)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/settings.json
Create separate VM Insights workbooks for both InsightsMetrics and Perf
InsightsMetrics
Perf
> Update Single VM Performance workbook

- Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis (Perf)/settings.json
- Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/settings.json
> Fix VMSS gallery

- Workbooks/Network Insights/NetworkInsights-LoadBalancerMetrics/NetworkInsights-LoadBalancerMetrics.workbook
> Modifying CM query removed FrontendIP paramater

- Workbooks/Network Insights/NetworkInsights-LoadBalancerMetrics/NetworkInsights-LoadBalancerMetrics.workbook
> Handling case sensitivity of parameter (ids)

- CODEOWNERS
> Added code owners to Network Insights

- Workbooks/AKS/Node GPU/settings.json
Removing feature flag for GPU workbook.
> Remove feature flag for GPU workbook

- Documentation/DataSources/DataSources.md
> Fix JSONPath doc link

- Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Perf)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/settings.json
> Hide Perf Counters workbook back under preview flag

- Documentation/Visualizations/HoneyComb.md
Spelling error. identifying was spelt indentifying
> Spelling Update in HoneyComb.md

- scripts/ProcessTemplates.ps1
Removes all the old package building work from the build processing script.
i've already updated the deployment pipeline to no longer automatically upload to storage now that prod/etc are loading templates from hosting service
> remove all the old package building parts that are no longer needed

- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook
Also fix onboarding check to also check for `ServiceMapComputer_CL` table
Test
--
> Fix for custom time range

- Workbooks/Azure Active Directory Conditional Access/Conditional Access Insights and Reporting/ConditionalAccessInsightsAndReporting.workbook
> updated link to docs in the workbook

- Workbooks/Network Insights/LoadBalancerWorkbooks/NetworkInsights-LoadBalancerMetrics-Minified/NetworkInsights-LoadBalancerMetrics-Minified.workbook
> Changing Load Balancer minified workbook initial time interval

- Workbooks/Resource Insights/RedisCache/ResourceInsights.workbook
- Workbooks/Resource Insights/RedisCache/settings.json
- Workbooks/Resource Insights/categoryResources.json
Add redis cache resource insights
> Redis Cache Resource Insights

- Workbooks/AKS/Billing Usage/Billing Usage.workbook
- Workbooks/AKS/Billing Usage/settings.json
Introducing Billing Usage workbook in AKS resoruce. It is behind the preview flag for testing. After testing we will remove the feature flag. 
This is the same workbook which we were initially bringing to LA workspace. We are now making it available only in the AKS resource.
Pasting the screenshot.
> Saaror patch 2

- README.md
> Add link to groups documentation at the top level

- Documentation/DataSources/DataSources.md
remove preview from ADX, reorder datasources, add more see also link logs, adx for query optimization
> Update datasources docs for ADX, reorder content, add query optimization links

- Workbooks/CosmosDb/Overview/Overview.workbook
- Workbooks/Storage/Overview/Overview.workbook
Add a label for subscription columns so that they can be localized
> add label for loc

- Workbooks/Insights/RedisCache/settings.json
- Workbooks/KeyVault/AzureMonitor/settings.json
- Workbooks/Storage/Overview/settings.json
> show redis, kv, storage in the insights category in azmon

- Workbooks/AKS/Billing Usage/Billing Usage.workbook
Updating the usage workbook, with final changes. This is hidden behind feature flight.
> Update Billing Usage.workbook

- Workbooks/KeyVault/Azure Monitor Onboarding/Azure Monitor Onboarding.workbook
- Workbooks/KeyVault/AzureMonitor/AzureMonitor.workbook
- Workbooks/KeyVault/AzureMonitor/settings.json
- Workbooks/KeyVault/Overview/Overview.workbook
- Workbooks/KeyVault/Overview/settings.json
- Fixing a few small typos and formatting changes
- Changed resource overview links to point to insights blade
> Final PR for Key Vault Public Preview

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
1. Update UsersList and Whoused parameter type
2. Pass componnetId for tiles link and update links
> Change parameters type and update tiles link

- Workbooks/AKS/Node GPU/Node GPU.workbook
The workbook queries fail when clusterId is present because the where clause does not put the clusterId in quotes 
* [x ] *if updating templates, it is helpful to post a screenshot of what the changes look like.*
No visual change
> Update Node GPU.workbook

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
1. Merge duplicate queries
2. Set init value for parameters/queries
3. Fix some queries for ", ' errors
> Improve usage workbook query

- Workbooks/Insights/RedisCache/Insights.workbook
> Redis at scale to link to redis at resource

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
Update query for userEventsList
> Fix query for userEventsList

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
1. Remove empty table from who used
2. Fix query issue for getCustomDimension
> Modify performance Tile

- Workbooks/AKS/Workload Details AKS Engine/Workload Details AKS Engine.workbook
- Workbooks/AKS/Workload Details AKS Engine/settings.json
- Workbooks/AKS/Workload Details AKS/Workload Details AKS.workbook
- Workbooks/AKS/Workload Details AKS/settings.json
> Workload Details workbook

- Workbooks/Workloads/MySQL Insights/MySQL Insights.workbook
- Workbooks/Workloads/NGINX Insights/NGINX Insights.workbook
- Workbooks/Workloads/Redis Insights/Redis Insights.workbook
- Workbooks/Workloads/SQL Insights/SQL Insights.workbook
Query for workspace in all subs instead of just current sub.
> Fix issue in WLI when VM and WS are in different subs

- Workbooks/Workloads/MySQL Insights/MySQL Insights.workbook
- Workbooks/Workloads/NGINX Insights/NGINX Insights.workbook
- Workbooks/Workloads/Redis Insights/Redis Insights.workbook
1. Fix column names
2. Update chart formatting where applicable.
3. Add Uptime column to MySQL overview.
> Fix formatting issues in NGINX, Redis and MySQL templates

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* set time range to line chart and area chart
> Set time range for line/area charts

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Update get Dimensions query to resolve string with ' issue
> Update get dimensions query

- Workbooks/Workloads/MySQL Insights/settings.json
- Workbooks/Workloads/NGINX Insights/settings.json
- Workbooks/Workloads/Redis Insights/settings.json
- Workbooks/Workloads/SQL Azure Insights/settings.json
- Workbooks/Workloads/SQL Insights/settings.json
Revert workbook name changes from 
https://github.com/microsoft/Application-Insights-Workbooks/pull/819
> Undo workbook name change.

- Workbooks/Workloads/MySQL Insights/MySQL Insights.workbook
Add message on no on-boarded in scope (Need a smaller logo image)
Remove cache chart, feature deprecated
Add names
> MySQL: Add message on no on-boarded, remove cache chart, add names

- Workbooks/SapMonitor/SapHana/SapHana.workbook
This PR checks certain error conditions (mostly related to the upgrade to v2.0) and prints out meaningful messages to the users.
Error conditions checked include:
- Custom log table `SapHana_LoadHistory_CL` does not exist yet
- Custom log table `SapHana_LoadHistory_CL` exists, but it doesn't have a column `HOST_s` that was already used in v1.5 **--or--**
Custom table `SapHana_LoadHistory_CL` exists with columns `HOST_s` and `PROVIDER_INSTANCE_s`, but doesn't have any records yet
- Custom log table `SapHana_LoadHistory_CL` exists with column `HOST_s`, but it is missing a new column `PROVIDER_INSTANCE_s` introduced in v2.0
> SAP Monitor/SapHana: Add error checks

- Workbooks/Workloads/Onboard SQL Azure Insights/Onboard SQL Azure Insights.workbook
- Workbooks/Workloads/SQL Azure Insights/SQL Azure Insights.workbook
> [WLI] SQL Azure, onboarding fix and enable monitoring message change

- Workbooks/SapMonitor/SapHana/SapHana.workbook
This PR adds the work done for SAP HANA backup monitoring to the SapHana workbook template. It will be displayed by navigating to the "Backup" tab.
> SAP Monitor/SapHana: Backup

- Workbooks/Workloads/Redis Insights/Redis Insights.workbook
Fix to show Overview if no Connections
Fix calculation of Rate
Fix CPU percentage (upon discussion w/ Auston, moved to VM Insights counter)
Add Memory percentage
Fix Command menu, various other fixes here
Fix calculation of call time
Various other fixes
* [x ] *if updating templates, it is helpful to post a screenshot of what the changes look like.*
* [ x] *if updating templates, ensure that your parameters and steps have meaningful names.*
> various fixes for Redis workbook

- Workbooks/Workloads/NGINX Insights/NGINX Insights.workbook
- Workbooks/Workloads/Redis Insights/Redis Insights.workbook
- Workbooks/Workloads/SQL Azure Insights/SQL Azure Insights.workbook
- Workbooks/Workloads/SQL Insights/SQL Insights.workbook
Redis: Set Command filter to default to All
NGINX: Add rest of step names
SQL: fix step name
* [x ] *if updating templates, ensure that your parameters and steps have meaningful names.*
> Set Redis Command filter to All. Rest of step names

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
- Workbooks/ADXCluster/AtResource/settings.json
from `Workbooks/Resource Insights` to its new location.
see; https://github.com/microsoft/Application-Insights-Workbooks/pull/837
> Copying ADX Cluster At Resource workbook

- Workbooks/ADXCluster/AtScale/Insights.workbook
Adding the workbook pin field to this ADX workbook as well, since we are in the process of moving directories
> adding workbook pin to ADX at scale

- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix performance query in Users workbook
> Fix performance query

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Update barchart query when x-axis is date time
> Update barchart query

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
> Fix 1 hour time grain bug

- Workbooks/SapMonitor/MsSqlServer/MsSqlServer.workbook
- This PR adds content to the "AlwaysOn" tab inside the Microsoft SQL Server workbook template
> Add MsSqlServer/AlwaysOn

- Workbooks/SapMonitor/SapHana.old/settings.json
- Workbooks/SapMonitor/categoryResources.json
- For our upcoming Public Preview starting 7/15/2020, this PR implements the following minor changes to the Workbook gallery:
- Change description (to reflect that the visualizations are not only about "infrastructure" anymore)
- Lower priority of old SAP HANA workbook template, encouraging customers to update
> SAP Monitor: Minor updates for Public Preview

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Update Usage workbook user/session tiles and events table to actual number
> Set to acutal number for usage tiles and table

- Workbooks/Workloads/Alerts group/Alerts group.workbook
- Workbooks/Workloads/Collection logs/Collection logs.workbook
- Workbooks/Workloads/Onboard MSSQL Insights/Onboard MSSQL Insights.workbook
- Workbooks/Workloads/SQL Insights/SQL Insights.workbook
1. Onboarding template has bigger toml editor + colorization
2. Improvements to alerts and collection logs templates
3. SQL metric splits include sql_instance
> Misc improvements in SQLI

- Workbooks/CosmosDb/Overview/Overview.workbook
- Workbooks/EventGrid/AtScale/Topics/Insights.workbook
- Workbooks/KeyVault/AzureMonitor/AzureMonitor.workbook
- Workbooks/Storage/Overview/Overview.workbook
Renaming any at scale workbook parameter types to just 'Resources'
> renaming all at scale resources parameter

- Documentation/Visualizations/Graph.md
The "Source Id" was mentioned twice. The second one is actually the "Target Id"
> Fix a setting name in the Graph Settings section

- Workbooks/Azure Active Directory Conditional Access/Conditional Access Insights and Reporting/ConditionalAccessInsightsAndReporting.workbook
> Replaced location grid with map graphic

- Workbooks/Azure Active Directory Conditional Access/Conditional Access Insights and Reporting/ConditionalAccessInsightsAndReporting.workbook
- scripts/ProcessTemplates.ps1
the previous change made sure the files we generate are UTF8, but this makes sure all the files end up with utf8 and no byte order mark too
> force even the files we didn't generate to be UTF8 with no BOM

- Workbooks/AKS/NPM Configuration AKS Engine/settings.json
- Workbooks/AKS/NPM Configuration AKS/NPM Configuration AKS.workbook
- Workbooks/AKS/NPM Configuration AKS/settings.json
* [ X] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
Change NPM resource name and type to make work book work for AKS.
> Change NPM resource name and type.

- Workbooks/Failures/New Failures Analysis/New Failures Analysis.workbook
> Fix Time range in failue workbook

- Workbooks/Azure Active Directory Conditional Access/Legacy Authentication/Legacy Authentication (Preview).workbook
- Workbooks/Azure Active Directory Conditional Access/Legacy Authentication/settings.json
> Added new legacy authentication workbook under a private preview flag

- Workbooks/UsageMetrics/Usage - Impact/Usage - Impact.workbook
> Update text in impact workbook

- Workbooks/UsageMetrics/Usage - Funnels/Usage - Funnels.workbook
* Update before/after query title in funnel workbook
> Update funnel before and after query

- Workbooks/UsageMetrics/Usage - Funnels/Usage - Funnels.workbook
* Show pin button for funnels grid
> Add pin in funnels workbook

- Workbooks/Azure Active Directory/MultiFactorAuthenticationGaps/MultiFactorAuthenticationGaps.workbook
- Workbooks/Azure Active Directory/MultiFactorAuthenticationGaps/settings.json
We are adding MFA gaps workbook - this workbook looks at all sign-in and highlight the apps and users who are not covered by MFA. We are starting with a private preview.
> Adding new workbook for MFA gaps

- Workbooks/Azure Monitor - Agents/Overview/Agent Health Overview.workbook
Added additional background details in the text section of the Overview workbook to describe what the two agent processes are to provide context as it relates to the Health Service performance charts and the Monitoring Host performance charts (on their respective tabs). Renamed the HealthService and MonitoringHost tabs to align with the proper noun and not the actual name of the process itself.
> updated text section and tab labels

- Workbooks/AKS/NPM Configuration AKS Engine/NPM Configuration AKS Engine.workbook
Add cluster ID filter in AKS-E workbook. All the queries under this workbook needs a filter of cluster id to proceed.
> Add cluster ID filter in AKS engine workbook.

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - At resource - Update the "Overview" tab. Add "application name" to the grid
> ADX Insights - At resource - Update the "Overview" tab

- Workbooks/Windows Virtual Desktop/WVD Insights/settings.json
Changing the insights type to all lower case for consistency.
> Updating the WVD insights type to lower case.

- Workbooks/KeyVault/AzureMonitor/AzureMonitor.workbook
> Added search bar for failures tab

- Workbooks/IoTHub/IoT Edge/iotedge.workbook
- Workbooks/IoTHub/IoT Edge/settings.json
> update iotedge workbook

- Workbooks/Resource Insights/RedisCache/ResourceInsights.workbook
> fix redis write metric

- Workbooks/AKS/Node GPU/Node GPU.workbook
- Workbooks/AKS/Node GPU/settings.json
> Adding GPU Workbook to Arc gallery

- Workbooks/Usage/User Impact Analysis/User Impact Analysis.workbook
* Update to standard info textbox
before change
After change
> change to standard info box

- Workbooks/AKS/NPM Configuration AKS Engine/NPM Configuration AKS Engine.workbook
Fixes bugs
Adds stepnames
Removes unneccessary components
Optimizes queries
Fixes hostname query
Fixes quantiles query
Etc
> fix bugs in npm aks engine workbook

- Workbooks/MultiCluster/categoryResources.json
> Changing category title to Containers

- Workbooks/IoTHub/IoT Edge/iotedge.workbook
> Oct9 iotedge preview update

- Workbooks/Azure Active Directory TroubleShooting/Provisioning/ProvisioningAnalysis.workbook
> Select all filters by default

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
Fix onboarding message (in case the cluster is already onboarded to LA), fix tooltip texts, add help tests, remove DM combo box from the overview , set column width (%), change tab name to usage
> Update ADX at-resource workbook

- Workbooks/ADXCluster/AtScale/Insights.workbook
Add more time charts, fix tool tips
> Update ADX at-scale

- Workbooks/Azure Monitor - Workspaces/Agent Health/settings.json
This PR is to stage "soft-delete" of the existing LA Agent Health workbook by removing the resource type (i.e. category) value in the settings.json file so that it no longer appears in the catalog.  The LA Agent Health workbook has been replaced by the new AzMon Agents Health workbook(s).
> updated category for LA Agent Health workbook

- Workbooks/Azure Monitor - Agents/categoryResources.json
Renaming the category for the AzMon Agent Health workbook(s) from Azure Monitor agents to Azure Monitor essentials in categoryResources.json.
> revised category for AzMon Agent Health

- Workbooks/AKS/Deployments and HPAs AKS Engine/Deployments and HPAs AKS Engine.workbook
> ClusterId filtering for HPA AKS Engine ver.

- CODEOWNERS
- Workbooks/Azure Monitor - Agents/categoryResources.json
- Workbooks/Usage/User Impact Analysis/User Impact Analysis.workbook
- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Funnels/Usage - Funnels.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Add common dimensions for usage filters
* Update query for event list
* Update query for getDimensionList
* Merger parameters
> Add common dimension for filters and update event and dimension queries

- Workbooks/AKS/NPM Configuration/settings.json
Puts npm workbook back into preview
> make npm wkbk preview again

- Workbooks/Usage/User Impact Analysis/User Impact Analysis.workbook
* Update Impact events queries
> Update impact events parameters

- scripts/extractStrings.cmd
- scripts/extractStrings.js
- scripts/package-lock.json
- scripts/package.json
- scripts/restoreDocs.cmd
Reverts microsoft/Application-Insights-Workbooks#990 due to pipeline test issue
> Revert "Update Localization pipeline v2"

- Workbooks/Workloads-AMA/Azure SQL Managed Instance/Azure SQL Managed Instance.workbook
- Workbooks/Workloads-AMA/Azure SQL database/Azure SQL database.workbook
- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Fix % scales to min:0 max: auto
- Fix Select empty resource group on 'Create New Profile'
> scale on percentage single view, select empty resource group on 'create new profile'

- CODEOWNERS
* [ X ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
Removed Nick and Kaveesh from AKS codeowners so that we are not a bottleneck for approvals. Added Container Insights team in our place
> Removed Nick and Kaveesh. Added Container Insights

- Workbooks/Workloads-AMA/SQL Server Insights/SQL Server Insights.workbook
Fix bugs around error messages on main SQL server insights
preview: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.workloadinsights=true&feature.canmodifystamps=true&appInsightsExtension=workbooks&feature.localtemplates=true&feature.workbookGalleryRedirect=https%3A%2F%2Foychansa.blob.core.windows.net%2Fazmontemplates%2Fpackage&l=en.en-us#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/workbooks
> SQL server insights error messages fix

- Workbooks/Azure Monitor - Getting Started/categoryResources.json
move getting started to the top of the azure monitor gallery
> move getting started with workbooks to the top

- Workbooks/Azure Active Directory TroubleShooting/Provisioning/ProvisioningAnalysis.workbook
> Fixed duplicate GUID bug + added display names + export options

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Enable monitoring/Enable monitoring.workbook
Auto select subs from SQL Server Insights
Preview: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.workloadinsights=true&feature.canmodifystamps=true&appInsightsExtension=workbooks&feature.localtemplates=true&feature.workbookGalleryRedirect=https%3A%2F%2Foychansa.blob.core.windows.net%2Fazmontemplates%2Fpackage&l=en.en-us#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/workbooks
> auto select sub from SQL Server Insights

- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Edit profile/Edit profile.workbook
- Workbooks/Workloads-AMA/Edit profile/settings.json
- Workbooks/Workloads-AMA/Enable monitoring/Enable monitoring.workbook
- Add Edit profile UI
- Create New profile customized collection section will have values from the common settings section
Preview: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.workloadinsights=true&feature.canmodifystamps=true&appInsightsExtension=workbooks&feature.localtemplates=true&feature.workbookGalleryRedirect=https%3A%2F%2Foychansa.blob.core.windows.net%2Fazmontemplates%2Fpackage&l=en.en-us#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/workbooks
> edit profile UI

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Update event list query in parameters
> Update event list query in parameters

- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
Add regex validation for profile name
> profile name validation

- test/jsonValidationTest.js
somehow a previous pr for this added a git submodule for localization (still hot sure how or why or where), this redoes that change without the inadvertant submodule that broke the build
> redo the validation without somehow adding a git submodule left behind on my machine

- Workbooks/Network Insights/ExpressRouteCircuits/ExpressRouteCircuitMetrics/ExpressRouteCircuitMetrics.workbook
> Removing ER Gateway Constraint and using distinct in Gateway Queries

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Funnels/Usage - Funnels.workbook
- Workbooks/UsageMetrics/Usage - MoreEvents/Usage - MoreEvents.workbook
- Workbooks/UsageMetrics/Usage - MoreSessions/Usage - MoreSessions.workbook
- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
- scripts/extractStrings.js
* Update tile cards query and pass parameters to open workbook link 
* show logs view icon for properties grids
* Fix query error for single quote
* Remove default value for funnelsQuery
> Update Tile cards query

- Workbooks/Usage/User Impact Analysis/User Impact Analysis.workbook
- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Lower case chart type 
* Remove default value for validCorrelation in impact workbook
> lower case chart type

- CODEOWNERS
Add kusto-workbooks (ADX/Azure Data Explorer) team as code owners
> Add kusto-workbooks team

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Edit profile/Edit profile.workbook
- Workbooks/Workloads-AMA/Update monitoring vm config/Update monitoring vm config.workbook
- update the templateURI to azmonsolutions
> update template uri links

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - Add the "Cache" tab
> ADX Insights - Add the "Cache" tab

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
- Workbooks/ADXCluster/AtResourceCache/settings.json
> add cache tab to workbook

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
Improve the onboarding message
Add "(Database: Table)" to the pie charts
Change the "Others" option in the pie chart
> ADX Insights - Tables: Improve the onboarding message

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
add a "Click on the above grid rows" message
Fix column names and set min/max (0-100%) for the bar visualization (% of queries, in the grid)
Fix onboarding message
> ADX Insights - improve Cache tab

- Workbooks/Workloads-AMA/Update monitoring vm config/Update monitoring vm config.workbook
- editing configuration for monitoring vm will show the default template if the current settings cannot be retrieved
> Update Monitoring vm show default template

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix by/split by cohort query for authenticated users
> Fix authenticated cohort query

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/settings.json
- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/settings.json
- Workbooks/Workloads-AMA/Custom Telegraf/Custom Telegraf Insights/Custom Telegraf Insights.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Custom Telegraf Insights/settings.json
- Workbooks/Workloads-AMA/Custom Telegraf/Enable monitoring/Enable monitoring.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Enable monitoring/settings.json
- Workbooks/Workloads-AMA/Custom Telegraf/categoryResources.json
- Workbooks/Workloads-AMA/Enable monitoring/Enable monitoring.workbook
- Workbooks/Workloads-AMA/SQL Server Insights/settings.json
- Workbooks/categoryResources.json
- src/LocProject.json
- Workbook for custom telegraf monitoring
> Custom telegraf monitoring

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - Fix the HelpContent workbook type
> ADX Insights - Fix the HelpContent workbook type

- Workbooks/UsageMetrics/Usage - Funnels/Usage - Funnels.workbook
> enable query run for hidden funnel steps

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
Remove the "data in cache" column.
Set a "Sum" aggregation to the chart.
Update chart colors.
> ADX Insights - Cache tab

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
Add "Total Extents" tile 
Grid columns rename
Add expander
> ADX Insights - Tables tab

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Custom Telegraf Insights/Custom Telegraf Insights.workbook
- Workbooks/Workloads-AMA/Update monitoring vm config/Update monitoring vm config.workbook
- update doc links
- add split by to metrics
- update config param name
> Custom telegraf fixes

- src/NuGet.config
> Localization: Update nuget config

- Workbooks/Network Insights/ExpressRouteCircuits/ExpressRouteCircuitMetrics/ExpressRouteCircuitMetrics.workbook
> Correcting ER Gateway query + Adding CPU Utilization Metric

- Workbooks/CosmosDb/Resource Insights/Resource.Insights.workbook
- Workbooks/CosmosDb/Resource Insights/settings.json
> Creating Cosmos DB Resource Workbook

- Workbooks/SapMonitor/PrometheusOS/PrometheusOS.workbook
This change will add a chart for persistent memory R/W metrics
> Add Persistent memory read write chart

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Edit profile/Edit profile.workbook
- Workbooks/Workloads-AMA/Update monitoring vm config/Update monitoring vm config.workbook
- create new profile to only have collection interval dropdown
- can show telegraf settings by clicking 'show settings'
> Perf changes

- Workbooks/Workloads-AMA/Edit profile/Edit profile.workbook
- fix bug where edit profile changes it to sqlinsights type
> update edit profile to be more generic to just edit profile

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook
> add vm recommendation for custom telegraf, json validation for config

- Workbooks/Azure Active Directory TroubleShooting/SensitiveOperations/SensitiveOperations.workbook
- Workbooks/Azure Active Directory TroubleShooting/SensitiveOperations/settings.json
* Added new workbook for Solorigate Investigation
* added Solorigate workbook
* updated parse_json logic
* Updated title and descriptions
* Final pass on wording before approval
* Updated name of workbook in file structure
* escaped user input, and removed dropdown InitiatedBy parameters
* Changed InitiatingUserOrApp to Actor
Co-authored-by: Daniel Wood <dawoo@microsoft.com>
> Danielwood95av (#1136)

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
> ADX Insights - Tables tab: Improvements

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
> ADX Insights - Main at resource page: improvements

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
> ADX Insights cache tab

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
ADX Insights - cache: unnecessary title
> ADX Insights - cache: unnecessary title

- Workbooks/Workloads-AMA/Update monitoring vm config/Update monitoring vm config.workbook
> fix deploy unset vm name

- Workbooks/KeyVault/Overview/settings.json
> fix keyvault pin

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
> ADX at-resource - text fixes

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
ADX Insights - cache tab text improvements
> ADX Insights - cache tab text improvements

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
ADX Insights - table tab improvements
> ADX Insights - table tab improvements

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - hide the Resource Health tile
> ADX Insights - hide the Resource Health tile

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
ADX Insights - cache tab: Update the onboarding message
> ADX Insights - cache tab: Update the onboarding message

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
ADX Insights - tables tab: update the onboarding message
> ADX Insights - tables tab: update the onboarding message

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - at resource: fix onboarding messages, show Resource health tile
> ADX Insights - at resource: fix messages, show Resource health tile

- Workbooks/Network Insights/LoadBalancerWorkbooks/NetworkInsights-LoadBalancerMetrics-Minified/NetworkInsights-LoadBalancerMetrics-Minified.workbook
- Workbooks/Network Insights/LoadBalancerWorkbooks/NetworkInsights-LoadBalancerMetrics/NetworkInsights-LoadBalancerMetrics.workbook
> Adding tolower method to backend VM query in LB metrics

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
> ADX Insights add db name to tables tab

- Workbooks/ADXCluster/AtScale/Insights.workbook
ADX Insights - at scale: Rename ADX cluster to cluster (too long string)
> ADX Insights - at scale: Rename ADX cluster to cluster

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - Resource - Update the "User" icon
> ADX Insights - Resource - Update the "User" icon

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
ADX Insights - Update resource Health columns + the Ingestion metric aggregation (from count to sum)
> ADX Insights - Update resource Health columns

- Workbooks/Network Insights/VirtualWANWorkbooks/NetworkInsights-VirtualWANMetrics/NetworkInsights-VirtualWANMetrics.workbook
> Fixing typo

- Workbooks/SapMonitor/SapNetWeaver/SapNetWeaver.workbook
- Workbooks/SapMonitor/SapNetWeaver/settings.json
PR Changes
- Adding workbook for SAP Monitor - SAP NetWeaver Provider.
Screenshots:
> Sap monitor sap net weaver

- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Custom Telegraf Insights/Custom Telegraf Insights.workbook
- Workbooks/Workloads-AMA/Edit profile/Edit profile.workbook
- Add form validation for create and edit profile to prevent users from deploying with empty configs
> add form validation for edit and create profile

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - MoreEvents/Usage - MoreEvents.workbook
- Workbooks/UsageMetrics/Usage - MoreSessions/Usage - MoreSessions.workbook
- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
> Fix replace in usage query

- CODEOWNERS
> Updating owners for Intune Reports to Intune Reporting V2 Github Team

- Workbooks/Workloads-AMA/SQL Server/SQL Server.workbook
> remove memory clerk filter

- src/NuGet.config
> Update nuget config 

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
> display info message when not ubuntu vm 18.04 instead of filtering list

- CODEOWNERS
Adding container insights team as code owners for the multicluster workbook template
> Adding Container Insights team to manage multicluster template

- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- use old ui to select what queries to collect
- add availability queries to sql vm drop down
- Set default to 60s
> update create profile ui

- Workbooks/IoTHub/IoT Edge/iotedge.workbook
> iot edge preview - jan update

- Workbooks/Azure Backup/Backup Report/Backup Report.workbook
> ReferencingEmailTab

- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> SettingDefaultValueForRPParams

- Workbooks/Azure Active Directory Conditional Access/By conditional access status/SigninsByCAStatus.workbook
- Workbooks/Azure Active Directory Conditional Access/By conditional access status/settings.json
- Workbooks/Azure Active Directory Conditional Access/By grant controls/SignInsByGrantControls.workbook
- Workbooks/Azure Active Directory Conditional Access/By grant controls/settings.json
> deprecated sign-ins using CA and by grant controls workbooks

- Workbooks/Azure Backup/Backup Report/Backup Report.workbook
- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> ExportParamsForOptimize

- Workbooks/Azure Backup/Backup Report/Backup Report.workbook
> LoadAlwaysOptimize

- Workbooks/AKS/Billing Usage Divided/settings.json
- Workbooks/AKS/Deployments and HPAs/settings.json
- Workbooks/AKS/NPM Configuration/settings.json
- Workbooks/AKS/Node Disk Capacity/settings.json
- Workbooks/AKS/Node Disk IO/Node Disk IO.workbook
- Workbooks/AKS/Node Disk IO/settings.json
- Workbooks/AKS/Node GPU/settings.json
- Workbooks/AKS/Node Kubelet/settings.json
- Workbooks/AKS/Node Network/settings.json
- Workbooks/AKS/Workload Details Divided/settings.json
Adding descriptions for the CI workbooks
Billing Usage: Provides breakdown and details on how much data is being used
HPAs: View Deployments and HPA health and status over time
NPM: View your NPM metrics on your policy runtimes and IPSets
Disk Capacity: Analyze most used disks, disk health status, and free disk capacity
Disk IO: Shows data input/output across your nodes
GPU: View the usage of your GPU Node and the node/pod counts
Kubelet: Provides kubelet health, performance, and operations data
Network: Shows data and errors sent and received across nodes/interfaces
Workload: Contains comprehensive workload information on CPU/Memory usage, pod/container status, kube events, and persistent volumes
Includes a small dropdown fix for Disk IO Workbook
> Ci descriptions

- Workbooks/AKS/Persistent Volume Details/settings.json
Remove 'isPreview' and add a description
> Change PV Inventory workbook from private to public

- Workbooks/Azure Backup/Backup Report/Backup Report.workbook
- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> LoadAlwaysForOptimize

- CODEOWNERS
- Workbooks/Azure Security Center/Secure Score/SecureScore.workbook
- Workbooks/Azure Security Center/Secure Score/settings.json
- Workbooks/Azure Security Center/System Updates/SystemUpdates.workbook
- Workbooks/Azure Security Center/System Updates/settings.json
- Workbooks/Azure Security Center/Vulnerabilities/Vulnerabilities.workbook
- Workbooks/Azure Security Center/Vulnerabilities/settings.json
- Workbooks/Azure Security Center/categoryResources.json
- Added 3 main workbooks: secure score over time, system updates, server and container vulnerabilities.
- See sample screenshots below:
> publish initial version of security center workbooks

- Workbooks/IoTHub/IoT Edge/iotedge.workbook
> feb 7 update

- Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- restrict adding vms that are not ubuntu 18.04
> Update add vm

- Workbooks/Azure Backup/Backup Report/Backup Report.workbook
- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> CheckingInLatestVersionsAndNewParams

- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> FixingLink

- Workbooks/Workloads-AMA/Azure SQL database/Azure SQL database.workbook
> fix single azure db view when multiple dbs are under one instance

- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> UpdatingEmailUX

- Workbooks/Virtual Machines - Network Dependencies/Active Ports/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview (Azure Preview)/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Connections Overview/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Failed Connections/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Open Ports/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Security and Audit/settings.json
- Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/settings.json
- Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Azure Preview)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Perf)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Perf)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Azure Preview)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Perf)/settings.json
- Workbooks/Virtual Machines - Performance Analysis/Performance Counters/settings.json
**Add descriptions for VMInsights network and performance workbooks.**
**Network workbooks:**
**_Connections Overview:_** Provides network dependencies and connection metrics. 
**_Active ports:_** Provides connection metrics for active network ports.
**_Open ports:_** Provides connection metrics for open network ports.
**_Failed Connections:_** Provides failed network connections across machines.
**_TCP Traffic:_** Provides TCP network traffic across machines.
**_Traffic Comparison:_** Provides a comparison of the network traffic across different time ranges.
**_Security and Audit:_** Provides an overview of network destinations and identifies probable malicious connections.
**Performance workbooks:**
**_Performance Analysis:_** Provides CPU, Memory, Disk, and Network metrics collected by …
> Add descriptions for VMInsights network and performance workbooks.

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
add workload groups in usage tab
add data connection in metrics tab
> add workload groups and data connections changes

- Workbooks/Workloads-AMA/Create new profile/Create new profile.workbook
- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/Create new profile.workbook
> update profile locations with intercept of LA workspace locations

- Workbooks/Azure Backup/backupitems-tab/backupitems-tab.workbook
- Workbooks/Azure Backup/jobdistribution-tab/jobdistribution-tab.workbook
- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
- Workbooks/Azure Backup/policydetails-tab/policydetails-tab.workbook
- Workbooks/Azure Backup/usage-tab/usage-tab.workbook
> FinalChanges1

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix cohortEventsQuery init query error
> Set isRequired for parseCohortEvents

- Workbooks/Workloads-AMA/Alerts/Alerts.workbook
Added a search filter to alert summary grid:
> add search filter to alerts

- Workbooks/Workloads-AMA/Custom Telegraf/Create new profile/Create new profile.workbook
fix bug in deployment for create profile in custom telegraf scenario
> Fix custom telegraf profile

- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
> updatingToRelativePath

- Workbooks/Azure Security Center/Secure Score/SecureScore.workbook
- Workbooks/Azure Security Center/System Updates/SystemUpdates.workbook
- Workbooks/Azure Security Center/Vulnerabilities/Vulnerabilities.workbook
Added filters and improved columns/grid formatting
> Added filters and improved columns/grid formatting

- Workbooks/Workloads-AMA/Azure SQL Database/Azure SQL Database.workbook
- Workbooks/Workloads-AMA/Azure SQL Managed Instance/Azure SQL Managed Instance.workbook
- Workbooks/Workloads-AMA/Database Drilldown/Free space in tempdb/Free space in tempdb.workbook
- Workbooks/Workloads-AMA/Database Drilldown/Memory broker clerk/Memory broker clerk.workbook
- Workbooks/Workloads-AMA/SQL Server/SQL Server.workbook
> Update Key Stats drill down in Overview tab

- Workbooks/categoryResources.json
- scripts/generateTemplates.js
> Category fix: Handle virtual categories

- Workbooks/SapMonitor/SapNetWeaver/SapNetWeaver.workbook
**Workbook Updates:**
1. Add new visualization for "Queue Length"
2. Add a filter for "Queue Type"
**ScreenShot :**
> Add Queue Length Visualization

- Workbooks/Azure Security Center/System Updates/SystemUpdates.workbook
System updates workbook: fixed typos on the help panel
> Fixed typos on the help panel

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Update Whouse to fix events link issue in details
> Fix events link in details blade issue

- Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads/SQL/Availability group/Availability group.workbook
1. Update vm regions to include AMA extension regions
2. Separated the status graph from Availability groups tile so there's more content
Before:
After:
> Update vm regions to include AMA extension regions

- Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook
- Added message below configuration if it's invalid JSON, removed the deploy button if invalid
-
> add json validation on update vm

- Workbooks/IoTHub/IoT Edge/iotedge.workbook
> mar19 udpate

- Workbooks/Network Insights/PublicIpWorkbooks/NetworkInsights-PublicIPMetrics-Minified/NetworkInsights-PublicIPMetrics-Minified.workbook
- Workbooks/Network Insights/PublicIpWorkbooks/NetworkInsights-PublicIPMetrics-Minified/settings.json
- Workbooks/Network Insights/PublicIpWorkbooks/NetworkInsights-PublicIPMetrics/NetworkInsights-PublicIPMetrics.workbook
- Workbooks/Network Insights/PublicIpWorkbooks/NetworkInsights-PublicIPMetrics/settings.json
- Workbooks/Network Insights/PublicIpWorkbooks/categoryResources.json
* Defining public IP workbooks which will be onboarded to Network Insights.
* ![image](https://user-images.githubusercontent.com/20801488/111945805-5529dd80-8b00-11eb-894f-03068a167ad5.png)
> Initial setup for Public IP workbook

- Workbooks/SapMonitor/Alerts/Create Alert rule (step 1 of 2)/settings.json
Fix SapMonitor Create alert workbook type
> Fix SapMonitor Create alert workbook type

- Workbooks/SapMonitor/Alerts/Alerts/Alerts.workbook
- Workbooks/SapMonitor/Alerts/Alerts/settings.json
Added SapMonitor Alerts main context page.
Testing:
* Able to create an alert using create alerting workbook
* Saw new alert show up
* Was able to go to alert rule resource from link
* Time range filter working as intended
> Added main alerts context page

- Workbooks/Azure Active Directory/SignInsAADADFS/SignInsAADADFS.workbook
- Workbooks/Azure Active Directory/SignInsAADADFS/settings.json
Updated the Workbook queries to show ADFS data and have conditional views based on data selections.
> Updating Queries to be able to pull from ADFSSignIns Log Analytics stream in preparation for public blog announcement

- gallery/container-insights/Microsoft.ContainerService-managedClusters.json
- gallery/container-insights/Microsoft.Kubernetes-connectedClusters.json
- Modify the description / name in the Gallery as per request from Sahil.
* [ N/A] post a screenshot of templates and/or gallery changes
* [ x] ensure your template has a corresponding gallery entry in the gallery folder
* [ x] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [x ] ensure all steps have meaningful names
* [ x] ensure all parameters and grid columns have display names set so they can be localized
* [ x] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [ x] ensure that steps names are …
> rename and redescribe the osm workbook

- Workbooks/ADXCluster/AtResourceClusterBoundaries/ResourceClusterBoundaries.workbook
> Added cluster boundaries tab

- Workbooks/ADXCluster/AtResourceClusterBoundaries/ResourceClusterBoundaries.workbook
- Fixed SKU recommendation filter 
- Changed recommendations table to "Tiny" size
- Changed "Cpu" -> "CPU"
> Fixed recommendation filter bug + typo fix

- Workbooks/Network Insights/PublicIpWorkbooks/NetworkInsights-PublicIPMetrics-Minified/NetworkInsights-PublicIPMetrics-Minified.workbook
- Workbooks/Network Insights/PublicIpWorkbooks/NetworkInsights-PublicIPMetrics/NetworkInsights-PublicIPMetrics.workbook
Changing input type in Public IP template from ARG query to workbook input
> Changing input for public ip workbook

- Workbooks/Network Insights/NetworkInterfaceWorkbooks/NetworkInsights-NetworkInterfaceMetrics-Minified/NetworkInsights-NetworkInterfaceMetrics-Minified.workbook
- Workbooks/Network Insights/NetworkInterfaceWorkbooks/NetworkInsights-NetworkInterfaceMetrics/NetworkInsights-NetworkInterfaceMetrics.workbook
- gallery/workbook/microsoft.network-networkinterfaces.json
Onboarding NIC to Network Insights. Defining initial setup of NIC workbook
> NIC workbook onboarding in Network Insights

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
> add top users/app per workloadGroup

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
> Cache: Add notice on queries that scan data

- Workbooks/IoTHub/IoT Edge device details/iotedge-device-details.workbook
- Workbooks/IoTHub/IoT Edge/iotedge.workbook
- gallery/workbook/Microsoft.Devices-IotHubs.json
> add alerts and create standalone device details

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix authenticatedId cohort user query
> Fix auth cohort user query bug

- Workbooks/SapMonitor/Alerts/Alerts/Alerts.workbook
A default subscription will be chosen
> The default subscription is chosen

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix head count focus issue to replace tile to customized text
> Fix usage head count focus issue, change tile to custom text

- Workbooks/Azure Active Directory Conditional Access/Conditional Access Insights and Reporting/ConditionalAccessInsightsAndReporting.workbook
> updated the policy dropdown to be powered by Conditional Access API

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
> ingestion tab change format column settings and renamings

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
> add MV tab to Overview

- Workbooks/ADXCluster/AtResourceMaterializedView/ResourceMaterializedViewDetails.workbook
add default value to empty metric and add text MV tab
> add default value to empty metric and add text MV tab

- Workbooks/CosmosDb/Mongo Insights/Mongo Insights.workbook
Adding an additional template that will be used to distinguish between API types. This is a Mongo DB-specific workbook. No additional changes need to be added to the gallery folder/entry since this workbook will be conditionally visible if the user is on a Mongo DB account.
> Adding Mongo API specfic workbook

- Workbooks/Availability/Downtime Outages/Downtime Outages.workbook
Resource group parameter addition to resolve a sev 3
> Resource group update

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
> add request for feedback at overview tab

- Workbooks/Failures/Failure Insights/Failure Insights.workbook
- Workbooks/Performance/Performance Insights/Performance Insights.workbook
- Workbooks/Usage/Active Users/Active Users.workbook
- Workbooks/Usage/Usage by hours of the day/Usage by hours of the day.workbook
* Add title for workbook grids
> Fix workbook grid without title bug

- scripts/extractStrings.js
- scripts/generateTemplates.js
> Update localization script

- CODEOWNERS
- Workbooks/Azure Stack HCI/AtScale/Insights.workbook
* Change log
1. Added last updated column to show the latest timestamp of events.
2. Updated default time range to 24 hours.
3. Changed VMs grid tree from group by to parent/child view for date/time aggregation.
> Add last updated column

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix cohort data queries in usage
> Fix cohort query bugs

- Workbooks/IoTHub/IoT Edge device details/iotedge-device-details.workbook
- Workbooks/IoTHub/IoT Edge health snapshot/iotedge-health-snapshot.workbook
- Workbooks/IoTHub/IoT Edge/iotedge.workbook
- gallery/workbook/Microsoft.Devices-IotHubs.json
> may 18 update

- Workbooks/ADXCluster/AtResourceMaterializedView/ResourceMaterializedViewDetails.workbook
> add value to metric threshold and add LA icon to query

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
Update the "Open Advisor page" link (in the overview page) as a full screen blade
> Update the "Open Advisor page" link as a full screen blade

- gallery/workbook/microsoft.servicebus-namespaces.json
> Remove Preview flag from Service Bus Gallery

- Workbooks/Availability/Downtime Outages/Downtime Outages.workbook
updated resource query to use tolower to adjust for component casing in query results
> fixed ai resource query

- Workbooks/IoTHub/IoT Edge health snapshot/iotedge-health-snapshot.workbook
- gallery/workbook/Microsoft.Devices-IotHubs.json
> fix link, make public

- Workbooks/Network Insights/NetworkInterfaceWorkbooks/NetworkInsights-NetworkInterfaceMetrics-Minified/NetworkInsights-NetworkInterfaceMetrics-Minified.workbook
- Workbooks/Network Insights/NetworkInterfaceWorkbooks/NetworkInsights-NetworkInterfaceMetrics/NetworkInsights-NetworkInterfaceMetrics.workbook
NIC workbook update to include metrics
> Updating NIC workbook

- Workbooks/IoTHub/IoT Edge device details/iotedge-device-details.workbook
> Add client disconnects

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
> fix out of cache bug and add min value 0 to bars

- Workbooks/Azure Security Center/Compliance/Compliance.workbook
- gallery/workbook/Azure Security Center.json
typoes and private preview flag
> typoes and private preview flag

- Workbooks/AKS/Smart Insights/Smart Insights.workbook
Modified the Smart Insights workbook to be Arc compatible (top level params & query fixes)
> Update Smart Insights.workbook

- Workbooks/ADXCluster/AtResourceMaterializedView/ResourceMaterializedViewDetails.workbook
> resolve Yifat's requests in MV insights

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix x-axis display in annotation chart
> Fix x-axis display in annotation chart

- Workbooks/Azure Active Directory/Tenant Restriction/Tenant Restriction Insights.workbook
Modify first section's text for better customer experience.
Here's screenshot for modified workbook, highlight the change area:
> Modify Tenant Restriction Insights workbook text

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - MoreEvents/Usage - MoreEvents.workbook
- Workbooks/UsageMetrics/Usage - MoreSessions/Usage - MoreSessions.workbook
- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Replace narrow() to solve issue that auto convert char to unicode
> Replace narrow()

- CODEOWNERS
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
- gallery/workbook/microsoft.wvd-insights.overview.json
AVD update 2021-07-19
Update CODEOWNERS
Add file gallery/workbook/microsoft.wvd-insights.overview.json
> Add Wvd insights gallery

- Documentation/LegacyAI/DeprecatedWorkbookRetrievalTool.md
added explicit instruction to copy the raw workbook json
> added explicit instruction to copy the raw workbook json

- .gitattributes
i would hope that linguist isn't case specific, but maybe it is?
trying to get the default view of workbook files to be the json editor instead of text-like
> update .gitattributes from JSON to json

- Workbooks/IoTHub/IoT Edge device details/iotedge-device-details.workbook
- Workbooks/IoTHub/IoT Edge/iotedge.workbook
> add feedback link and add routing input/output

- Workbooks/Azure SQL VM/SQL Assessment/SQL Assessment.workbook
Address some recent issue found during bug bash.
> Update SQL Assessment workbook for issues

- Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVD Insights Update 2021-08-09
Updated version to 1.1.2
>     Updated version to 1.1.2

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
+ add "~" to "cluster_name ==" queries
> ADX Ingestion - improve titles text

- Workbooks/HDInsight/v2/Cluster/Flink/Flink.workbook
- Workbooks/HDInsight/v2/ClusterPool/ClusterPool.workbook
Updated chart for active pod by filtering for cluster name
> Updated chart for active pod by filtering for cluster name

- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
* Pass threshold to Apdex workbook
> Pass threshold to Apdex

- Workbooks/HDInsight/v2/Cluster/Flink/Flink.workbook
- Workbooks/HDInsight/v2/Cluster/LLAP/LLAP.workbook
- Workbooks/HDInsight/v2/Cluster/Trino/Trino.workbook
- Workbooks/HDInsight/v2/ClusterPool/ClusterPool.workbook
1. Updated parameter used for clusters = clusterName, expecting to equal to value passed in from NotebookParam set in portal
2. Updated parameter to have type Text or drop down
3. Updated downstream queries to filter by clusterName
> Update cluster parameter

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
> ADX Insights Add 2 spaces for the fail tab

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
> ADX Insights -ingestion - Add icons to the tiles

- Workbooks/ADXCluster/AtResourceTables/ResourceTableDetails.workbook
change pie charts to grid in tables tab
> change pie charts to grid in tables tab

- CODEOWNERS
Added the SQL External Monitoring group as the owners of SQL workbooks under workload folder.
> Added SQL External Monitoring as owners of SQL workbooks.

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
fix time brushing of logs queries
> fix time brushing of logs queries

- CODEOWNERS
Add IDC AMS Team into code owner for /Workbooks/SapMonitor** folder
> Add IDC AMS Team as code owner for folder /Workbooks/SapMonitor/**

- gallery/workbook/microsoft.aadiam-tenant.json
> Remove preview flag off AADIP Risk Analysis

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
ADX Ingestion tab - dark theme-related fixes
> ADX Ingestion tab - dark theme-related fixes + change "Engine storage" to "Storage Engine"

- Workbooks/Windows Virtual Desktop/Check Configuration/Check Configuration.workbook
- Workbooks/Windows Virtual Desktop/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVD Insights update version 1.1.7 - 2021-11-01
> AVD Insights update version 1.1.7 - 2021-11-01

- Workbooks/Windows Virtual Desktop/Check Configuration/Check Configuration.workbook
- Workbooks/Windows Virtual Desktop/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVI Update to 1.1.8 - 2021-11-15
> AVDI update to 1.1.8 - 2021-11-15

- Workbooks/SapMonitor/SapHana/SapHana.workbook
Updated the Hana DB Provider with the following new metrics: 
1. License Status - To check if an enforced license is installed and current memory consumption of SAP HANA exceeds the licensed amount of memory plus some tolerance
2. Savepoint - SAP HANA IO Savepoint
3. MVCC - SAP HANA Multiversion Concurrency Control (MVCC) count
4. Delta Merge  - SAP HANA delta merge issue
5. Statistics Alert - Reported SAP HANA Alerts
> Workbook changes for new metrics for Hana DB Provider

- Workbooks/Product Analytics using the Click Analytics Plugin/HEART Analytics - All Sections/HEART Analytics - All Sections.workbook
- gallery/workbook/microsoft.insights-components.json
Added 'framework by google' to the HEART Analytics - All Sections Workbook's HEART overview section. Also updated the gallery file to remove the private preview flag from all the HEART workbooks as we're ready for public preview.
> Updating HEART workbooks to remove private preview flag and updating overview content

- Workbooks/ADXCluster/AtResourceMaterializedView/ResourceMaterializedViewDetails.workbook
ADX Insights - Fix MV bug with top 5 limits
> ADX Insights - Fix MV bug with top 5 limits

- Workbooks/Usage/User Impact Analysis/User Impact Analysis.workbook
* Set min and max value for percentage grid column.
> Set min and max value for percentage column

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
> add order by to the 'batching by table' tile + add 'Failed ingestions by category' tile

- Workbooks/ADXCluster/AtResourceMaterializedView/ResourceMaterializedViewDetails.workbook
MV tab - fix to 10000 limit and remove the health
> ADX Insights - MV tab - fix to 10000 limit and remove the health

- Workbooks/Azure Security Center/Log4j/Log4j.workbook
- gallery/workbook/Azure Security Center.json
- Added a new workbook for Log4J vulnerability.
> Added Log4j workbook

- Workbooks/Azure SQL VM/SQL Assessment/SQL Assessment.workbook
- Simplify the pie charts for categorization of results
- Split the result grid into two - one for rule type and second for details based on selection in first grid
- Add filters for the grid
> SQLVM Assessment - update result grids and pie charts

- Workbooks/ADXCluster/AtResourceClusterBoundaries/ResourceClusterBoundaries.workbook
> Cluster Boundaries - remove title

- CODEOWNERS
Add missing ownership on IoT Central's gallery json
> Add IoT Edge team as owner for Microsoft.IoTCentral-IoTApps.json

- Workbooks/Azure Security Center/Active Alerts/ActiveAlerts.workbook
- gallery/workbook/Azure Security Center.json
This PR adds a new "Active Alerts" workbook to the gallery.
> Add Active Alerts workbook

- Workbooks/Workloads/SQL/Availability group/Availability group.workbook
Update the Availability group state query to use the time range parameter.
Before the change:
After:
> Add TimeRange param for Availability group state query

- Workbooks/Windows Virtual Desktop/Alerts/Alerts Report.workbook
- Workbooks/Windows Virtual Desktop/Check Configuration/Check Configuration.workbook
- Workbooks/Windows Virtual Desktop/Client Report/Client report.workbook
- Workbooks/Windows Virtual Desktop/Connection Diagnostics/Connection Diagnostics.workbook
- Workbooks/Windows Virtual Desktop/Connection Performance/Connection Performance.workbook
- Workbooks/Windows Virtual Desktop/Host Diagnostics/Host Diagnostics.workbook
- Workbooks/Windows Virtual Desktop/Host Performance/Host Performance.workbook
- Workbooks/Windows Virtual Desktop/NoData/NoData.workbook
- Workbooks/Windows Virtual Desktop/Overview/Overview.workbook
- Workbooks/Windows Virtual Desktop/User Report/User report.workbook
- Workbooks/Windows Virtual Desktop/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook
- Workbooks/Windows Virtual Desktop/shared/Host Pool Overview/Host Pool Overview.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVD Insights update 1.1.10 - 2022-02-14
> AVD Insights update 1.1.10 - 2022-02-14

- test/jsonValidationTest.js
Allow numeric characters in gallery files as some resource types contain a version number (eg. microsoft.dbforpostgresql-servergroupsv2
> Validation: Update Gallery File Validation Test

- CODEOWNERS
- gallery/hyperscalecitus-insights/microsoft.dbforpostgresql-servergroupsv2.json
> Add inisghts folder for HyperscaleCitus.

- gallery/usage/microsoft.insights-components.json
Removing private preview flag from heart workbooks so that they can be visible in the usage blade under 'more' section.
> Removed private preview flag from HEART workbooks

- Workbooks/Azure Active Directory/AuthenticationPrompts/Authentication Prompts Analysis Public Preview.workbook
> updated defaults of series colors. tried to correct for dark on dark colors. corrected "click here" link

- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
> Add LB and Public IP info in ACS workbook

- CONTRIBUTING.md
- Documentation/Contributing.md
Small change to fix "create a new branch" link which is not working
> Fix link in CONTRIBUTING.md

- Workbooks/ADXCluster/AtResource/ResourceInsights.workbook
> ADX Insights - Remove HTML span tags. Overview blade.

- Workbooks/Azure Security Center/Coverage/Coverage.workbook
- gallery/workbook/Azure Security Center.json
This PR will submit the Defender for Cloud coverage workbook to be added to Defender for Cloud's community gallery. The workbook shows Defender for Cloud plans/offerings on Azure subscriptions, AWS and GCP connectors.
_
> Tom janetscheck 01

- package-lock.json
- package.json
see https://github.com/microsoft/Application-Insights-Workbooks/security/dependabot/3
> update minimist to get past security issue

- Workbooks/Azure Security Center/Ransomware/Ransomware.workbook
- gallery/workbook/Azure Security Center.json
This PR will submit the Microsoft Defender for Cloud ransomware workbook to be added to Defender for Cloud's community gallery. The workbook shows recommendations that are mapped to the MITRE ATT&CK Framework, their status, and some overview graphs of how their subscriptions look when talking about Tactics and Techniques involved in the framework.
> Adding Ransomware Workbook for Defender for Cloud 

- Workbooks/Defender for IoT/Sensor Health/Sensor Health.workbook
> Update Sensor Health.workbook

- gallery/workbook/Azure Monitor.json
Tested it, and now removing the preview flag
> Remove preview flag from Spark Infrastructure

- CODEOWNERS
- Workbooks/Azure Storage Cache/AtScale/AtScale.workbook
- Workbooks/Azure Storage Cache/Performance/Insights.workbook
- gallery/storagecache-insights/Azure Monitor.json
- gallery/storagecache-insights/microsoft.storagecache-caches.json
- gallery/workbook/Azure Monitor.json
- Onboarding storagecache for using workbooks.
- Screenshots attached here:
1. Performance tab:
2. Capacity tab:
> Storage cache onboarding to workbooks

- Workbooks/SapMonitor2.0/Db2/Db2.workbook
- gallery/workbook/microsoft.workloads-monitors.json
DB2 provider workbook for AMS2.0
> Add workbook for DB2 provider in SapMonitor

- Workbooks/ADXCluster/AtResourceIngestion/ResourceIngestionDetails.workbook
> ADX Ingestion - add blob metrics for the data connection

- Workbooks/Azure Stack HCI/SingleCluster/Cluster.workbook
Views and texts are updated after review with team.
> Azure Stack HCI Single Cluster Workbook Template update after review

- Workbooks/Azure Stack HCI/AtScale/Insights.workbook
UI and texts are updated after review with team.
> Multi-Cluster Workbook Update after review

- Workbooks/Azure Security Center/Active Alerts/Active Alerts.workbook
- Fix open alert button in bottom alert table.
- Fix Resource, subscription to be clickable in bottom alert table.
- Fix Map view not showing.
- Fix strings.
**Screenshot to demonstrate all above:**
- Fix queries to filter only alerts with **status == "Active"** in tables with **"Active Alerts"** title.
- Changed survey text:
- Format long queries (using kql online editor) so they can be more readable.
> Update Active Alerts.workbook

- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
> Update app gateway string in ACSS workbook

- Workbooks/SapMonitor2.0/PrometheusHaCluster/PrometheusHaCluster.workbook
- gallery/workbook/microsoft.workloads-monitors.json
> Create PrometheusHA workbook

- Workbooks/AKS/Subnet IP Usage/Subnet IP Usage.workbook
- gallery/container-insights/Microsoft.ContainerService-managedClusters.json
Changed name from CNS IP Usage to Subnet IP Usage.
> [Nit] Name change

- Workbooks/SapMonitor2.0/Db2/Db2.workbook
*## PR Checklist
Updated Db2 workbook with Alerts
* Updated context pane for Alerts to open in new page.
> Updated Db2 workbook with Alerts

- Workbooks/Azure Security Center/Governance/Governance.workbook
> Update governance report with empty state view

- Workbooks/Defender for IoT/Sensor Health/Sensor health.workbook
> Update and rename Sensor Health.workbook to Sensor health.workbook

- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
Added the OS Quality checks
All the advisor recommendations are displayed to this workbook in separate group
> Add Advisor recommendation data

- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
Add SAP resource type to advisor recommendation.
> [ACSS] - Add SAP resource type

- Workbooks/Azure Stack HCI/SingleCluster/Cluster.workbook
Fixed REST API to query only MicrosoftMonitoringAgent type extension.
> Add extension name in query

- gallery/workbook/Azure Security Center.json
> Remove governance workbook feature flag

- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
> Add text changes and impact field

- Workbooks/Windows Virtual Desktop/Check Configuration/Check Configuration.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
- Workbooks/Windows Virtual Desktop/templates/avdworkspacediag.armtemplate
- Workbooks/Windows Virtual Desktop/templates/hostpooldiag.armtemplate
- Workbooks/Windows Virtual Desktop/templates/workspaceaddmultiloc.armtemplate
- Workbooks/Windows Virtual Desktop/templates/workspacecfgevents.armtemplate
- Workbooks/Windows Virtual Desktop/templates/workspaceconfigv1.armtemplate
AVDI update version 1.2.1 - 2022-06-20
Add arm templates to the repository
> AVDI update  version 1.2.1 - 2022-06-20

- Workbooks/UsageMetrics/Usage - Filters/Usage - UsageFilters.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix user type issue in query
> Fix user type issue in query

- Workbooks/AKS/Billing Usage By Datatable Tab/Billing Usage By Datatable Tab.workbook
- Workbooks/AKS/Billing Usage By Log Source Tab/Billing Usage By Log Source Tab.workbook
- Workbooks/AKS/Billing Usage By Namespace Tab/Billing Usage By Namespace Tab.workbook
> ContainerLogV2 union query updates

- Workbooks/Azure Backup/Backup Report/Backup Report.workbook
- Workbooks/Azure Backup/backupitems-tab/backupitems-tab.workbook
- Workbooks/Azure Backup/jobdistribution-tab/jobdistribution-tab.workbook
- Workbooks/Azure Backup/optimize-tab/optimize-tab.workbook
- Workbooks/Azure Backup/policyadherence-tab/policyadherence-tab.workbook
- Workbooks/Azure Backup/policydetails-tab/policydetails-tab.workbook
- Workbooks/Azure Backup/summary-tab/summary-tab.workbook
- Workbooks/Azure Backup/usage-tab/usage-tab.workbook
> Removing error handle and its dependency from all workbook

- Documentation/BYOS/BringYourOwnStorage.md
Adding note to make sure that this file is no longer edited.
> Adding note to make sure that this page is retired

- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
Add tab for each child resource recommendation.
> Add tabs for child resource for quality checks

- Workbooks/Failures/Failure Insights/Failure Insights.workbook
> Update Failures Insights header class

- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
> Add threshold validation

- Workbooks/Azure SQL VM/SQL Assessment/SQL Assessment.workbook
Pie charts now shows distinct numbers of rules
> PieCharts numbers for distinct rules

- Workbooks/Azure Center for SAP solutions/ACSS Aggregated/ACSS Aggregated.workbook
- gallery/workbook/microsoft.workloads-sapvirtualinstances.json
Cloned the previous workbook and made it at ACSS level for all VIS.
Added the VIS id to each table and VIS is redirectable also.
Added the SAP resource type to each table to identify the VM role.
Global filter is added for VIS default is all.
> Add new workbook for acss aggregated level

- Workbooks/Azure SQL VM/SQL Assessment/SQL Assessment.workbook
- Workbooks/Failures/Failure Insights/Failure Insights.workbook
- Update text to note the limited results per recommendation
- Distinct checkids in chart counts
> SQL Assessment - Update text about result limitation and unique count in charts

- gallery/updatecompliance-insights/Azure Monitor.json
- gallery/workbook/Azure Monitor.json
> Turn off preview for update compliance hub

- Workbooks/Communication Services/Insights_Beta/Insights_Beta.workbook
This tab includes a chart showing the API results, the sizes of the emails, an histogram by size, the count of recipients and the total count of emails. Additionally there is a drill down for the details of individual emails and recipients.
> New tab with Email

- Workbooks/Communication Services/Overview/Overview.workbook
> Added Email Tab

- Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook
> Fixed a typo

- Workbooks/Windows Virtual Desktop/Host Diagnostics/Host Diagnostics.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update version 1.2.3 - 2022-08-29
> AVDI update version 1.2.3 - 2022-08-29

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
Show top count tile till data is loaded.
> Update condition visibilities for usage total count tile

- Workbooks/Workloads/SAP/Inventory Checks for SAP/Inventory Checks for SAP.workbook
Removed Next Steps for change logs
* [ Updating fields, removing tag options.
> Public_Preview_Update

- Workbooks/Windows Virtual Desktop/AtScale/Alerts/Alerts Report.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Client Report/Client report.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Connection Diagnostics/Connection Diagnostics.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Connection Performance/Connection Performance.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Overview/Overview.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/AtScale/WVD Insights/WVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook
- Workbooks/Windows Virtual Desktop/shared/Host Pool Overview/Host Pool Overview.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update version 1.3.0 - 2022-09-12
> AVDI update version 1.3.0 - 2022-09-12

- Workbooks/CosmosDb/SQL Insights/SQL Insights.workbook
Add missing resource parameter reference to total request units metric chart
> At resource Cosmos DB Insights: Add missing resource reference

- Workbooks/Azure Managed Instance for Apache Cassandra/Cassandra MI Insights/Cassandra MI Insights.workbook
adding a few new metrics, changing time granularity, amending some metric titles, for Cassandra MI workbook
> add new metrics

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Funnels/Usage - Funnels.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
Add time range selections in Usage
> Add time selections for usage

- Workbooks/Azure Center for SAP solutions/ACSS Aggregated/ACSS Aggregated.workbook
- Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook
> Add the filter of 1 day for recommendations

- Workbooks/Azure Security Center/Coverage/Coverage.workbook
Updating Coverage workbook to include CSPM coverage
> updating Defender for Cloud Coverage workbook

- Workbooks/Windows Virtual Desktop/Client Report/Client report.workbook
- Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
- Add Windows  7 warning
- Add Client OS tables on client usage report
> AVDI update version 1.4.0 - 2022-10-17

- Workbooks/UpdateCompliance/Device information/Device information.workbook
> Remove wufb state and substate from device information

- Workbooks/SapMonitor2.0/AIOpsInsights/SAP AMS.workbook
Small corrections to visibility and VM ID data availability check.
> SAP Insights workbook corrections

- Workbooks/SapMonitor2.0/AIOpsInsights/Availability Insights/Auto RCA.workbook
- Workbooks/SapMonitor2.0/AIOpsInsights/SAP AMS.workbook
Health event object is different for different kinds of events. Fixed schema implemented to avoid unnecessary columns from showing up in the report.
> SAP Insights - fix for inconsistent object models in health events

- schema/workbook.json
- scripts/extractStrings.js
-  support workbook name in workbook link settings
- update scehma
> workbook name support

- CODEOWNERS
- Workbooks/Azure Monitor - Workspaces/Prometheus Explorer/Prometheus Explorer.workbook
- gallery/workbook/microsoft.monitor-accounts.json
Adding a template for an exploratory query experience for Azure Monitor workspaces similar to the existing Prometheus console.
> Add Prometheus Explorer Template

- Workbooks/Azure Managed Instance for Apache Cassandra/Cassandra MI Insights/Cassandra MI Insights.workbook
minor updates to "cpu" and "waiting on commit latency" metrics
> minor updates to cassandra mi metrics

- Workbooks/Azure Stack HCI/AtScale/Insights.workbook
- Update cluster link to insights blade
> Update cluster link to insights

- Workbooks/Communication Services/Insights_Beta/Insights_Beta.workbook
Added tabs to include the primitives Recording and Call Automation
Recording Workbook
Call Automation Workbook
> Added recording and call automation tab

- gallery/hyperscalecitus-insights/microsoft.dbforpostgresql-servergroupsv2.json
- gallery/workbook/microsoft.dbforpostgresql-servergroupsv2.json
Citus is rebranded as Azure Cosmos DB for PostgreSQL Cluster
> Rebranding citus to Azure Cosmos DB for PostgreSQL

- Workbooks/UsageMetrics/Usage - MoreEvents/Usage - MoreEvents.workbook
* hidden timestamp column in event grid
> hidden timestamp column

- Workbooks/AKS/Billing Usage Parameters/Billing Usage Parameters.workbook
- Workbooks/MultiCluster/Multi Cluster Controllers/Multi Cluster Controllers.workbook
- Workbooks/MultiCluster/Multi Cluster Performance/Multi Cluster Performance.workbook
- gallery/container-insights/Microsoft.HybridContainerService-provisionedClusters.json
> Add LCM workbook gallery

- Workbooks/Azure Security Center/Price Estimation/PriceEstimation.workbook
> Update Microsoft Defender For Cloud workbook

- Workbooks/Defender for IoT/Vulnerabilities/Vulnerabilities.workbook
> Added parameters fixes

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
- gallery/workbook/Azure Security Center.json
> Rename and update MDC pricing estimation workbook (Cost estimation)

- Workbooks/Defender for IoT/Vulnerabilities/Vulnerabilities.workbook
> update to vulnerabilities workbook

- CODEOWNERS
- gallery/workbook/Azure Advisor.json
ADDED GALLERY JSON FILE
I set up the Workbooks blade for our Advisor extension in Portal. We currently only have the Reliability workbook to display in our gallery.
* [] post a screenshot of templates and/or gallery changes
* [] ensure your template has a corresponding gallery entry in the gallery folder
* [] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
> Advisor gallery

- Workbooks/Windows Virtual Desktop/AtScale/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/AtScale/WVD Insights/WVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
> AVDI update version 1.6.0 - 2023-01-30

- Workbooks/Communication Services/Overview/Overview.workbook
Added a new tab for recording and call automation.
> Add recording and call automation tab

- scripts/generateTemplates.js
- scripts/package.json
- scripts/processDevPackageOnly.cmd
Restore scripts needed for deploying custom gallery
> Restore custom gallery scripts

- Workbooks/Azure Monitor - Workspaces/Prometheus Explorer/Prometheus Explorer.workbook
Changes the y-axis to be decimal instead of percent
> fix y axis on prom explorer workbook

- Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
- Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook
Add brackets for credscan to ignore string
> Add brackets around placeholder string

- Workbooks/Azure Security Center/Active Recommendations/Active Recommendations.workbook
- gallery/workbook/Azure Security Center.json
This PR will add a community workbook to gain insights into active recommendations, including the active period, per Azure subscriptions, AWS accounts, and GCP projects
> adding Active Recommendations workbook

- Workbooks/Azure Active Directory Identity Governance and Access/Provisioning Workbook/Provisioning Insights.workbook
- gallery/workbook/microsoft.aadiam-tenant.json
> added Identity Governance and Access Folder and Provisioning Insights Workbook

- Workbooks/KeyVault/AzureMonitor/AzureMonitor.workbook
Increase split by limit for overview grid
> Key Vault Insights: Increase metric split by limit

- Workbooks/SapMonitor2.0/AIOpsInsights/Availability Insights/Auto RCA.workbook
inconsistency in parsing of health events corrected.
> fix for health event parse error

- Workbooks/Azure Stack HCI/SingleCluster/Cluster.workbook
- Workbooks/Azure Stack HCI/SingleClusterAMA/Cluster.workbook
- Update single cluster workbook for HCI Insights
- Add LAW ARM ID as parameter instead of calling REST API
- Check MSI and capabilities for AMA support
- Update banner text
> Update single cluster workbook for AMA

- Workbooks/PostgreSQL Flexible Server/Enhanced/Enhanced Metrics.workbook
> PG Flex Enhanced Workbooks Banner and Replication tabchanges

- Workbooks/AKS/Workload Details Pod-Container Status Tab/Workload Details Pod-Container Status Tab.workbook
> Update container status icon

- Workbooks/PostgreSQL Flexible Server/Enhanced/Enhanced Metrics.workbook
- Workbooks/PostgreSQL Flexible Server/Overview/Overview.workbook
https://portal.azure.com/?feature.customportal=false&feature.workbookGalleryRedirect=https%3A%2F%2Fprkintworkbooks.blob.core.windows.net%2Fworkbooks%2Fpackage
> Fix typos for PG Flex Workbooks

- gallery/workbook/Azure Advisor.json
Added (preview) to the Reliability workbook title by updating the name of the item in the gallery JSON file.
> Added preview to the reliability workbook title

- Workbooks/MySQL Flexible Server/Enhanced/Enhanced Metrics.workbook
Testing Link: https://portal.azure.com/?feature.customportal=false&feature.workbookGalleryRedirect=https%3A%2F%2Fprkintworkbooks.blob.core.windows.net%2Fworkbooks%2Fpackage
> MySQL Flexible Server Enhanced Workbook with Tabs.

- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.0.0 2023-03.13
> AVDI update - version 2.0.0 - 2023-03.13

- Workbooks/Failures/New Failures Analysis/New Failures Analysis.workbook
- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - MoreEvents/Usage - MoreEvents.workbook
- Workbooks/UsageMetrics/Usage - MoreSessions/Usage - MoreSessions.workbook
- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
* Fix usage accessibility bugs
> fix usage accessibility bugs

- Workbooks/Communication Services/Overview/Overview.workbook
Added Email, Recording and Call Automation to Overview
Changed the SMS tab
> Changed overview and SMS

- Workbooks/Windows Virtual Desktop/AtScale/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.0.1 2023-03-20
> AVDI update - version 2.0.1 2023-03-20

- Workbooks/UpdateCompliance/Driver updates/Driver updates.workbook
> Stop query from breaking by adding hidden parameter

- Workbooks/SapMonitor2.0/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook
Added changes to write a query to get distinct cluster name in the cluster selection dropdown.
> Get distinct cluster name in the cluster selection dropdown

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
- Workbooks/Azure Security Center/Governance/Governance.workbook
- gallery/workbook/Azure Security Center.json
> Add DCSPM to Cost estimation workbook + Governance workbook title without preview

- Workbooks/SapMonitor2.0/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook
Updated check to run and fetch HA even when the step is hidden.
> updated do not run query check

- gallery/workbook/Azure Advisor.json
> Changed gallery name from Advisor to Community

- Workbooks/Windows Virtual Desktop/AtScale/WVD Insights/WVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.0.3 - 2023-04-10
> AVDI update - version 2.0.3 - 2023-04-10

- Workbooks/UpdateCompliance/Quality updates/Quality Updates.workbook
> Remove target version chart

- Workbooks/Azure Security Center/Active Alerts/Active Alerts.workbook
Reverts microsoft/Application-Insights-Workbooks#2239
As the deprecation is not affecting customers.
> Revert "Active Alerts - remove tags related widgets / filterings"

- Workbooks/SapMonitor2.0/Db2/Db2.workbook
- Workbooks/SapMonitor2.0/MsSqlServer/MsSqlServer.workbook
- Workbooks/SapMonitor2.0/PrometheusHaCluster/PrometheusHaCluster.workbook
- Workbooks/SapMonitor2.0/PrometheusOS/PrometheusOS.workbook
- Workbooks/SapMonitor2.0/SapHana/SapHana.workbook
- Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook
> Added warning for No provider and No LA data exist in all the providers

- Workbooks/KeyVault/AzureMonitor/AzureMonitor.workbook
Revise key vault insights tab styling to match with other insights (eg. cosmos db). Remove negative px height.
Before: 
After:
> Key Vault Insights - Update tab styling

- Workbooks/SapMonitor2.0/Db2/Db2.workbook
- Workbooks/SapMonitor2.0/MsSqlServer/MsSqlServer.workbook
- Workbooks/SapMonitor2.0/PrometheusHaCluster/PrometheusHaCluster.workbook
- Workbooks/SapMonitor2.0/PrometheusOS/PrometheusOS.workbook
- Workbooks/SapMonitor2.0/SapHana/SapHana.workbook
- Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook
Added warning for below cases for all the providers- 
•	If there is no active provider exist in AMS
•	If there is active provider but there is no data in LA
* [X ] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
> added warning for no provider and no LA data exist

- Workbooks/SapMonitor2.0/Db2/Db2.workbook
- Workbooks/SapMonitor2.0/MsSqlServer/MsSqlServer.workbook
- Workbooks/SapMonitor2.0/PrometheusHaCluster/PrometheusHaCluster.workbook
- Workbooks/SapMonitor2.0/PrometheusOS/PrometheusOS.workbook
- Workbooks/SapMonitor2.0/SapHana/SapHana.workbook
- Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook
> Button Link target update in SapMonitor workbooks

- Workbooks/UpdateCompliance/Alert details/Error Codes for Alert Subtype.workbook
> Fix duplicate description recommendation

- Workbooks/PostgreSQL Flexible Server/Overview/Overview.workbook
Onboards New Database Availability Metric in Overview Workbook.
https://portal.azure.com/?feature.customportal=false&feature.workbookGalleryRedirect=https%3A%2F%2Fprkintworkbooks.blob.core.windows.net%2Fworkbooks%2Fpackage
> Onboard Database Availability Metric in overview Workbook

- Workbooks/Azure Security Center/API Security/API Security.workbook
> Update API Security.workbook

- gallery/workbook/Azure Advisor.json
> Add Azure-Service-Retirement in gallery under preview

- Workbooks/Azure Stack HCI/SingleClusterAMA/Cluster.workbook
- CPU and memory usage columns are fixed to show chart instead of just numbers.
> Fix CPU and memory usage in single cluster Insights for AMA

- Workbooks/Azure Advisor/AzureServiceRetirement/Azure Services Retirement.workbook
- Added 12 more services Azure Synapse Analytics
Azure Synapse Analytics
CognitiveServices
Virtual Machines
Virtual Machines
Virtual Machines
Virtual Machines
Machine Learning Studio (classic) 
Public IP address
CognitiveServices
Azure Database for PostgreSQL
Azure Cosmos DB for PostgreSQL
- made few cosmetic changes as per Jessica's feedback (UX designer)
> New services added to service retirement workbook

- Workbooks/Azure Stack HCI/SingleClusterAMA/Cluster.workbook
- Update link URL in banner as it shouldn't go to troubleshooting page.
> Update banner link

- gallery/workbook/Azure Advisor.json
change category name to Azure Advisor in gallery
> change category name to Azure Advisor in gallery

- gallery/hci-insights/microsoft.azurestackhci-clusters.json
**Changes**
Changed the HCI workbook template name in order to show consistent blade title on Single Cluster HCI Workbook.
> Change HCI workbook template names

- Workbooks/Windows Virtual Desktop/shared/Host Pool Overview/Host Pool Overview.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.2.0 - 2023-05-22
> AVDI update - version 2.2.0 - 2023-05-22

- Workbooks/Azure Advisor/AzureServiceRetirement/Azure Services Retirement.workbook
> Fixed 4 bugs reported in bugbash

- gallery/workbook/Azure Advisor.json
> Removed feature flag for workbook template

- Workbooks/ServicesHub/AtResource/ADAssessmentWorkbookTemplate/ADAssessment.workbook
- Workbooks/ServicesHub/AtResource/ADSecurityAssessmentWorkbookTemplate/ADSecurityAssessment.workbook
- Workbooks/ServicesHub/AtResource/AzureAssessmentWorkbookTemplate/AzureAssessment.workbook
- Workbooks/ServicesHub/AtResource/ExchangeAssessmentWorkbookTemplate/ExchangeAssessment.workbook
- Workbooks/ServicesHub/AtResource/ExchangeOnlineAssessmentWorkbookTemplate/ExchangeOnlineAssessment.workbook
- Workbooks/ServicesHub/AtResource/SCCMAssessmentWorkbookTemplate/SCCMAssessment.workbook
- Workbooks/ServicesHub/AtResource/SCOMAssessmentWorkbookTemplate/SCOMAssessment.workbook
- Workbooks/ServicesHub/AtResource/SPAssessmentWorkbookTemplate/SPAssessment.workbook
- Workbooks/ServicesHub/AtResource/SQLAssessmentWorkbookTemplate/SQLAssessment.workbook
- Workbooks/ServicesHub/AtResource/SfBAssessmentWorkbookTemplate/SfBAssessment.workbook
- Workbooks/ServicesHub/AtResource/SharePointOnlineAssessmentWorkbookTemplate/SharePointOnlineAssessment.workbook
- Workbooks/ServicesHub/AtResource/WindowsClientAssessmentWorkbookTemplate/WindowsClientAssessment.workbook
- Workbooks/ServicesHub/AtResource/WindowsServerAssessmentWorkbookTemplate/WindowsServerAssessment.workbook
Changes:
We have added Affected Objects section in the on-demand assessments.
On click of every row in Affected objects grid, details of that row is shown in right pane.
Below is the screenshot of the changes.
> Add Affected Objects section

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
Updating DCSPM pricing to 5$, without discount model.
> Update DCSPM Pricing

- Workbooks/Windows Virtual Desktop/CheckAMAConfiguration/CheckAMAConfiguration.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.3.1 - 2023-06-19
> AVDI update - version 2.3.1 - 2023-06-19

- Workbooks/SapMonitor2.0/MsSqlServer/MsSqlServer.workbook
Made the following changes to MSSQL workbook:
- "Backups" in Backup section query fixed and added table existence check for the step.
- "Actual blocking Processes" in Problems section query fixed and added table existence check for the step.
- "Recorded errors" in Problems section query fixed and added table existence check for the step.
> MSSQL - Fixed broken steps

- Workbooks/Azure Security Center/API Security/API Security.workbook
> Minor Updates for API Security Workbook

- .vscode/settings.json
This PR associates .workbook files with the json formatter/syntax highlighter in VSCode for readability.
> Treat .workbook files as json in VSCode

- Workbooks/SapMonitor2.0/MsSqlServer/MsSqlServer.workbook
Update the no data message in the SQL workbook
> update the no data message in the SQL workbook

- Workbooks/UpdateCompliance/Expedite deployment view/Expedite deployment view.workbook
- Workbooks/UpdateCompliance/Quality updates/Quality Updates.workbook
> Fix issue where denominator in expedite kpi card might not be set

- Workbooks/ServicesHub/AtResource/ADAssessmentWorkbookTemplate/ADAssessment.workbook
- Workbooks/ServicesHub/AtResource/ADSecurityAssessmentWorkbookTemplate/ADSecurityAssessment.workbook
- Workbooks/ServicesHub/AtResource/AzureAssessmentWorkbookTemplate/AzureAssessment.workbook
- Workbooks/ServicesHub/AtResource/ExchangeAssessmentWorkbookTemplate/ExchangeAssessment.workbook
- Workbooks/ServicesHub/AtResource/ExchangeOnlineAssessmentWorkbookTemplate/ExchangeOnlineAssessment.workbook
- Workbooks/ServicesHub/AtResource/SCCMAssessmentWorkbookTemplate/SCCMAssessment.workbook
- Workbooks/ServicesHub/AtResource/SCOMAssessmentWorkbookTemplate/SCOMAssessment.workbook
- Workbooks/ServicesHub/AtResource/SPAssessmentWorkbookTemplate/SPAssessment.workbook
- Workbooks/ServicesHub/AtResource/SQLAssessmentWorkbookTemplate/SQLAssessment.workbook
- Workbooks/ServicesHub/AtResource/SfBAssessmentWorkbookTemplate/SfBAssessment.workbook
- Workbooks/ServicesHub/AtResource/SharePointOnlineAssessmentWorkbookTemplate/SharePointOnlineAssessment.workbook
- Workbooks/ServicesHub/AtResource/WindowsClientAssessmentWorkbookTemplate/WindowsClientAssessment.workbook
- Workbooks/ServicesHub/AtResource/WindowsServerAssessmentWorkbookTemplate/WindowsServerAssessment.workbook
Below is the screenshot for change
> Add Title in detail section

- Workbooks/UpdateCompliance/Driver updates/Driver updates.workbook
> Fix error message in driver kpi card

- gallery/workbook/Azure Advisor.json
> remove preview flag for cost workbook

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
> Cost estimation: Add defender for ARM and AKV

- Workbooks/UpdateCompliance/Feature updates/Feature updates.workbook
> Change text in FU EOS flyout

- CODEOWNERS
- Workbooks/Global Secure Access/Discovered Application Segments/Discovered Application Segments.workbook
- Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook
- gallery/workbook/Global Secure Access.json
We're creating a new gallery for our service, along with a new workbook for discovered application segments.
We're also updating the CODEOWNERS list so that the Global Secure Access team can receive pull requests for that workbook.
Discovered Application Segments workbook:
> New discovered application segments workbook for Global Secure Access

- Workbooks/Global Secure Access/Office Log Health and Data Enrichment/Office Log Health and Data Enrichment.workbook
We're updating log health & data enrichment workbook.
Office Log Health & Data Enrichment Workbook (updated parts):
> Update office log health & data enrichment workbook for Global Secure Access

- Workbooks/Windows Virtual Desktop/AtScale/Overview/Overview.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.3.3 - 2023-08-21
> AVDI update - version 2.3.3 - 2023-08-21

- Workbooks/Windows Virtual Desktop/CheckAMAConfiguration/CheckAMAConfiguration.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 2.3.4 - 2023-09-05
> AVDI update - version 2.3.4 - 2023-09-05

- Workbooks/Azure Security Center/Coverage/Coverage.workbook
This PR will add a new table for detailed coverage of some Defender for Cloud plans that require additional settings rather than just enabling the plan. In addition to that, a new filtering option is added so customers can decide which coverage (relative, absolute, or detailed) they would like to show.
> adding detailed coverage to MDC Coverage workbook

- Workbooks/Global Secure Access/Office Log Health and Data Enrichment/Office Log Health and Data Enrichment.workbook
We're updating the log health and data enrichment workbook to utilize LogAnalyticWorkspace parameter in the Workload, Users, DeviceId, IP parameters.
> Fix office log health & data enrichment workbook for Global Secure Access

- Workbooks/Global Secure Access/Discovered Application Segments/Discovered Application Segments.workbook
We're updating the discovered application segments workbook to utilize LogAnalyticWorkspace parameter in the User parameter.
> Fix discovered application segments workbook for Global Secure Access

- Workbooks/Global Secure Access/Office Log Health and Data Enrichment/Office Log Health and Data Enrichment.workbook
Update questions as the LA table schema as changed EventId to Id
OperationName to Operation
UniqueTokenIdentifier to UniqueTokenId
* [ V] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [V ] Validate your changes using one or more of the [testing](../Documentation/Testing.md) methods.
* [V ] ensure your template has a corresponding gallery entry in the gallery folder
* [ V] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [V ] ensure all steps have meaningful names
* [V ] ensure all parameters and grid columns have display names set so they can be localized
* [ V] ensure that parameters id values are unique __or they will fail …
> Update Office Log Health and Data Enrichment.workbook

- Workbooks/SapMonitor2.0/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook
Existing logic is to create alert in the LAWs RG, so updating the logic to create alert in the MRG linked to AMS.
> Update alert creation from LAWs RG to MRG

- Workbooks/Global Secure Access/Common/Traffic Logs.workbook
- Workbooks/Global Secure Access/Office Log Health and Data Enrichment/Office Log Health and Data Enrichment.workbook
- gallery/workbook/Global Secure Access.json
* [V] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
Fix a filter in workloads parameter to take into account the time parameter. 
Rename the summary of the graphs.
Add limit of 20 to pie chart, before using Others.
* [V] Validate your changes using one or more of the [testing](../Documentation/Testing.md) methods.
Validate my changes by generating a new workbook based on the template and checking all is as expected. 
* [V] post a screenshot of templates and/or gallery changes
* [V] ensure your template has a corresponding gallery entry in the gallery folder
* [V ] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [V ] ensure …
> Miritsadon add traffic logs workbook under common

- Workbooks/UsageMetrics/Usage - MoreUsers/Usage - MoreUsers.workbook
* Update usage user perf threshold validation
> Usage user perf threshold validation

- Workbooks/Windows Virtual Desktop/CheckAMAConfiguration/CheckAMAConfiguration.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 3.1.0 - 2023-10-02
> AVDI update - version 3.1.0 - 2023-10-02

- Workbooks/Azure Monitor - Workspaces/Prometheus Explorer/Prometheus Explorer.workbook
This is a basic text change to make the error message slightly more generic since there are other issues the troubleshooting documentation helps with besides permission issues now.
> update access message

- Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook
Tooltips added to PMEC Site Overview workbook to explain what the fields mean e.g. explaining acronyms or specific terminology.
> Added tooltips. Removed platform type column.

- Workbooks/Windows Virtual Desktop/AVD Insights/AVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Connection Diagnostics/Connection Diagnostics.workbook
- Workbooks/Windows Virtual Desktop/AtScale/WVD Insights/WVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/CheckAMAConfiguration/CheckAMAConfiguration.workbook
- Workbooks/Windows Virtual Desktop/Connection Diagnostics/Connection Diagnostics.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
- Workbooks/Windows Virtual Desktop/templates/avdworkspacediag.armtemplate
- Workbooks/Windows Virtual Desktop/templates/hostpooldiag.armtemplate
AVDI update - version 3.2.0 - 2023-10-09
> AVDI update - version 3.2.0 - 2023-10-09

- Workbooks/SapMonitor2.0/AIOpsInsights/SAP AMS.workbook
A fix for opening Perf Flyout with correct parameters.
> PerfAlerts Flyout Fix

- Workbooks/AKS/Cluster Optimization/Cluster Optimization.workbook
- Workbooks/AKS/Deployments and HPAs/Deployments and HPAs.workbook
- Workbooks/AKS/NPM Configuration/NPM Configuration.workbook
- Workbooks/AKS/Node Disk Capacity/Node Disk Capacity.workbook
- Workbooks/AKS/Node Disk IO/Node Disk IO.workbook
- Workbooks/AKS/Node GPU/Node GPU.workbook
- Workbooks/AKS/Node Kubelet/Node Kubelet.workbook
- Workbooks/AKS/Node Network/Node Network.workbook
- Workbooks/AKS/Persistent Volume Details/Persistent Volume Details.workbook
- Workbooks/AKS/Subnet IP Usage/Subnet IP Usage.workbook
- Workbooks/AKS/Workload Details Divided/Workload Details Divided.workbook
> add initiator param for CI onboarding blade

- Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
- Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
- Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook
> Fix usage event query

- Workbooks/Global Secure Access/Common/Traffic Logs.workbook
- Workbooks/Global Secure Access/Discovered Application Segments/Discovered Application Segments.workbook
- Workbooks/Global Secure Access/Microsoft 365 Log Health and Data Enrichment/Microsoft 365 Log Health and Data Enrichment.workbook
- Workbooks/Global Secure Access/Office Log Health and Data Enrichment/Office Log Health and Data Enrichment.workbook
- gallery/workbook/Global Secure Access.json
We're removing the 'any' option from the workspace dropdown menu and adding a title above it in all workbooks. We're also removing the 99th percentile from Latency Analysis in Office Log Health and Data Enrichment workbook, and adding a new workbook with the same content but a new name, which will be deleted in the future.
> Update Global Secure Access's workbooks

- Workbooks/Azure Security Center/DevOps Security/DevOps Security.workbook
> Update DevOps Security.workbook

- Workbooks/Traffic Analytics/VNet/YourEnvUnifiedTest
> Adding YourEnvUnifiedTest

- Workbooks/Global Secure Access/Microsoft 365 Log Health and Data Enrichment/Microsoft 365 Log Health and Data Enrichment.workbook
We're changing the values in the Details column of Microsoft 365 Enriched Events table to a link with the label "View".
> Update Microsoft 365 Log Health and Data Enrichment workbook

- Workbooks/SapMonitor2.0/AIOpsInsights/Performance Insights/Auto Perf RCA.workbook
Changes for this release:
- FIxed few Performance Flyout SAP Metrics visualizations for Insights Workbook.
> Fix for Perf Flyout Errors before Configuring Insights

- Workbooks/Global Secure Access/Discovered Application Segments/Discovered Application Segments.workbook
We're updating the title text across the workbook to be in a different format.
> Update Discovered Application Segments workbook

- Workbooks/Azure Stack HCI/AtScale/Insights.workbook
> AMAv2 At-scale workbook

- Workbooks/Azure Advisor/AzureServiceRetirement/Azure Services Retirement.workbook
> Banner addition for TLS 1.0/1.1

- Workbooks/Azure Advisor/Cost Optimization/AHB/AHB.workbook
- Workbooks/Azure Advisor/Cost Optimization/Compute/Compute.workbook
- Workbooks/Azure Advisor/Cost Optimization/CostOptimization.workbook
- Workbooks/Azure Advisor/Cost Optimization/Networking/Networking.workbook
- Workbooks/Azure Advisor/Cost Optimization/Reservations/Reservations.workbook
- Workbooks/Azure Advisor/Cost Optimization/SavingsPlan/SavingsPlan.workbook
- Workbooks/Azure Advisor/Cost Optimization/Storage/Storage.workbook
- Workbooks/Azure Advisor/Cost Optimization/Top10Services/Top10Services.workbook
New subtab for RI and Savings Plan
Savings Plan recommendations
Reservations recommendations
AHB for Stack HCI
New Synapse query under the Top 10 Services tab
New Log Analytics query under the Top 10 Services tab
Moved AKS and App services query under the Top 10 Services tab
> Azure Advisor Cost Optimization Workbook - November Updates

- Workbooks/Network Insights/AzureFirewallWorkbooks/NetworkInsights-AzureFirewallMetrics-StructuredLogs/NetworkInsights-AzureFirewallMetricsStructuredLogs.workbook
> Creating new Threat Intelligence tab in the Azure Firewall workbook

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
> Update cost estimation workbook with GCP

- Workbooks/UpdateCompliance/Active alerts device detail/Active alerts device detail.workbook
> Allow customers to see Active Alerts query so we can better debug

- Workbooks/Defender for IoT/Device Risk Score/Device risk score.workbook
> added device risk score workbook

- gallery/workbook/defender-for-iot.json
> Adding new workbook to D4IoT gallery

- Workbooks/Defender for IoT/Device Risk Score/Device risk score.workbook
> updated risk score workbook

- Workbooks/ServicesHub/AtResource/ADAssessmentWorkbookTemplate/ADAssessment.workbook
- Workbooks/ServicesHub/AtResource/ADSecurityAssessmentWorkbookTemplate/ADSecurityAssessment.workbook
- Workbooks/ServicesHub/AtResource/AzureAssessmentWorkbookTemplate/AzureAssessment.workbook
- Workbooks/ServicesHub/AtResource/ExchangeAssessmentWorkbookTemplate/ExchangeAssessment.workbook
- Workbooks/ServicesHub/AtResource/ExchangeOnlineAssessmentWorkbookTemplate/ExchangeOnlineAssessment.workbook
- Workbooks/ServicesHub/AtResource/SCCMAssessmentWorkbookTemplate/SCCMAssessment.workbook
- Workbooks/ServicesHub/AtResource/SCOMAssessmentWorkbookTemplate/SCOMAssessment.workbook
- Workbooks/ServicesHub/AtResource/SPAssessmentWorkbookTemplate/SPAssessment.workbook
- Workbooks/ServicesHub/AtResource/SQLAssessmentWorkbookTemplate/SQLAssessment.workbook
- Workbooks/ServicesHub/AtResource/SharePointOnlineAssessmentWorkbookTemplate/SharePointOnlineAssessment.workbook
- Workbooks/ServicesHub/AtResource/WindowsClientAssessmentWorkbookTemplate/WindowsClientAssessment.workbook
- Workbooks/ServicesHub/AtResource/WindowsServerAssessmentWorkbookTemplate/WindowsServerAssessment.workbook
Removed "isHiddenWhenLocked": true, from all ODA templates
> Enabled subscription filter for all ODA Workbook templates

- Workbooks/SapMonitor2.0/Alerts/Alerts/Alerts.workbook
Adding a upsell banner for new alerts experience
> Upsell banner for new alerts experience

- Workbooks/AKS/Cluster Optimization/Cluster Optimization.workbook
> update cluster optimization workbook message to exclude windows nodes

- Workbooks/Windows Virtual Desktop/AVD Insights/AVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 3.2.1 - 2024-02-06
> AVDI update - version 3.2.1 - 2023-02-06

- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
- Workbooks/Windows Virtual Desktop/templates/createdcr1.armtemplate
AVDI update - version 3.2.2 - 2023-02-12
> AVDI update - version 3.2.2 - 2023-02-12

- Workbooks/UpdateCompliance/Expedite deployment view/Expedite deployment view.workbook
> Add update release time to alerts view from expedite deployment view

- Workbooks/Azure API Management/Analytics/analytics.workbook
Added new Geography tab to APIM analytics workbook
> Geography tab added to APIM analytics

- Workbooks/Azure Monitor - Agents/Agent Migration Tracker/AMA Migration Helper.workbook
Fixed queries for subscriptions and VM counts, as well as wording on machine tabs, based on recent support tickets
> Fixed queries for VM count and wording

- Workbooks/Azure Stack HCI/Dell/MultiCluster/Cluster.workbook
- gallery/workbook/Azure Monitor.json
Multi Cluster Workbook for Dell APEX
> Dell APEX Multi Cluster workbook

- gallery/workbook/businesscontinuity-insights.json
Update businesscontinuity-insights for name
> Update businesscontinuity-insights for name

- Workbooks/Windows Virtual Desktop/AVD Insights/AVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Connection Reliability/Connection Reliability.workbook
- Workbooks/Windows Virtual Desktop/AtScale/WVD Insights/WVDWorkbookV2.workbook
- Workbooks/Windows Virtual Desktop/Autoscale/autoscale.workbook
- Workbooks/Windows Virtual Desktop/CheckAMAConfiguration/CheckAMAConfiguration.workbook
- Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 3.3.0 - 2024-04-01
> AVDI update - version 3.3.0 - 2024-04-01

- Workbooks/UpdateCompliance/Total devices/Total devices.workbook
> Remove line from total devices

- Workbooks/Workloads/SQL/SQL Server Insights/SQL Server Insights.workbook
- Add a message with a link to database watcher documentation.
> Add a database watcher recommendation

- Workbooks/Azure Security Center/Attack Paths/Attack Paths.workbook
- gallery/workbook/Azure Security Center.json
Added a new community workbook to track attack paths over time.
Based on customer feedback, CxE team created a new workbook to track attack paths over time.
> Added attack paths over time

- scripts/generateTemplates.js
Modify generate template script to add armtemplate index references to `_index.json`.
> Add armtemplate to generated index file 

- Workbooks/Azure Monitor - Workspaces/At Scale Insights/At Scale Insights.workbook
- Workbooks/Azure Monitor - Workspaces/Usage Insights/Usage Insights.workbook
- Adds limits columns to at-scale view
- Adds "unused metrics" section to resource view
> Add missing information to amw insights workbooks

- Workbooks/Azure Advisor/Cost Optimization/AHB/AHB.workbook
- Workbooks/Azure Advisor/Cost Optimization/CostOptimization.workbook
- Workbooks/Azure Advisor/Cost Optimization/Networking/Networking.workbook
- Add queries:
- Identify idle ER circuit
- Identify PIP DDoS 
- Identify PIP routing method
- Pie Chart to summarize commitment discount savings
- Include AHB for SQL pool elastic pool
> Advisor Cost Optimization workbook - April Release

- Workbooks/Azure Security Center/Containers Security/Containers Security.workbook
Adding in multicloud and configuration overview
*I added insights for resources in AWS and GCP. I also added an overview for if dcspm or defender for containers is enabled.
> Update Containers Security.workbook

- Documentation/Deployment.md
Update deployment document to include new build pipeline
> [Documentation] Update build pipeline link

- Workbooks/UpdateCompliance/Total devices/Total devices.workbook
> Change alert type

- gallery/workbook/microsoft.workloads-monitors.json
> Added preview tag to SID Landscape View workbook

- Workbooks/Azure Logic Apps/FilteredServiceBus/FilteredServiceBus.workbook
Before:
After:
Tested using Github branch
> Rework list of topics & queues in AIS notebook

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
> Cost estimation - Update workbook discount default value

- Workbooks/Windows Virtual Desktop/AtScale/Connection Reliability/Connection Reliability.workbook
- Workbooks/Windows Virtual Desktop/AtScale/Utilization Report/Utilization Report.workbook
- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
AVDI update - version 3.5.0 - 2024-06-19
> AVDI update - version 3.5.0 - 2024-06-19

- Workbooks/PostgreSQL Flexible Server/Performance/High CPU Usage/High CPU Usage.workbook
> Change to high CPU usage

- Workbooks/PostgreSQL Flexible Server/Performance/High CPU Usage/High CPU Usage.workbook
> More corrections to High CPU usage workbook

- Workbooks/PostgreSQL Flexible Server/Performance/High CPU Usage/High CPU Usage.workbook
> More fixes in High CPU usage workbook

- Workbooks/PostgreSQL Flexible Server/Performance/High CPU Usage/High CPU Usage.workbook
> More fixes

- Workbooks/PostgreSQL Flexible Server/Performance/High CPU Usage/High CPU Usage.workbook
> Fix syntax error

- Workbooks/PostgreSQL Flexible Server/Performance/Autovacuum Monitoring/Autovacuum Monitoring.workbook
- Workbooks/PostgreSQL Flexible Server/Performance/High CPU Usage/High CPU Usage.workbook
- Workbooks/PostgreSQL Flexible Server/Performance/High IOPS Usage/High IOPS Usage.workbook
- Workbooks/PostgreSQL Flexible Server/Performance/High Memory Usage/High Memory Usage.workbook
- Workbooks/PostgreSQL Flexible Server/Performance/Query Performance Insights/Query Performance Insights.workbook
| Item | Workbook |
| --- | --- |
| 1. Add table level auto vacuum details [7 Days history] <br> - Show number of times AV ran on table <br> - Time to run the AV <br> - Number of dead tuples cleaned or not removed <br> - Oldest xmin details | Autovacuum Monitoring |
| AV Parameter Values : Validate parameters | Autovacuum Monitoring |
| Transaction ID utilization Metric | Autovacuum Monitoring |
| Validate content of Wraparound text. Is it relevant upto PG16 | Autovacuum Wraparound |
| Parameter check for log min duration, pgaudit --> write & read | High CPU |
| Locks information + advanced metric [Sessions tab] | High CPU |
| Another tab for High CPU queries (mean time * calls) | High CPU |
| Warning for idle in transaction state | High CPU |
| PG Bouncer Recommendations update | High …
> Pushing perf workbooksv2 changes

- Workbooks/SapMonitor2.0/SidLandscapeView/SidLandscapeView.workbook
> Text changes text in the SID Landscape View workbook

- Workbooks/Azure Monitor - Agents/Agent Migration Tracker/AMA Migration Helper.workbook
Updated the Hybrid without Arc queries to optimise the query and improve returned results
> Updated AMA Migration Helper

- Workbooks/SapMonitor2.0/OracleDb/OracleDb.workbook
> Remove extra space in one of the condition in Oracle DB workbook

- Workbooks/SapMonitor2.0/SidLandscapeView/SidLandscapeView.workbook
> UI improvements to SID landscape view workbook

- Workbooks/MySQL Flexible Server/Overview/Overview.workbook
MySQL Portal team update the default template of the overview workbook.
> Update MySQL Overview.workbook

- Workbooks/Azure Advisor/Cost Optimization/CostOptimization.workbook
This is a small PR to fix the commitment discount tab
> Fix commitment discount tab

- Workbooks/Intune Reports/Device Compliance Trends/DeviceComplianceTrends.workbook
- Workbooks/Intune Reports/Preview Device Compliance Trends/DeviceComplianceTrends.workbook
Update Device Compliance (60 day trend) to Device Compliance (30 day trend), the report now show only 30 day trend
> Device compliance trend to show 30 day trend data.

- Workbooks/Global Secure Access/Common/Client Activity and Status/Client Activity and Status.workbook
- Workbooks/Global Secure Access/Common/Network Traffic Insights/Network Traffic Insights.workbook
- Workbooks/Global Secure Access/Common/Remote Network Health/Remote Network Health.workbook
- Workbooks/Global Secure Access/Microsoft Entra Internet Access/Enriched Microsoft 365 logs/Enriched Microsoft 365 logs.workbook
- Workbooks/Global Secure Access/Microsoft Entra Private Access/Discovered Application Segments/Discovered Application Segments.workbook
> Add preview tags to GSA workbook template titles

- Workbooks/Azure Advisor/Cost Optimization/AHB/AHB.workbook
- Workbooks/Azure Advisor/Cost Optimization/CommitmentDiscounts/commitment.workbook
- Addition of a new "Custom Image" subtab within the AHB tab.
- Improved RI queries. I added conditional visibility to the RI group so it only appears when there's a recommendation. If there are no RI recommendations, the RI query doesn't show up.
> Cost optimization workbook - August release

- Workbooks/SapMonitor2.0/AIOpsInsights/Availability Insights/Auto RCA.workbook
> remove flag healthData from condition visibility

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
> Fix Cost estimation workbook DCSPM plan

- Workbooks/Workloads/SQL/SQL Server Insights/SQL Server Insights.workbook
Add the [retirement](https://azure.microsoft.com/en-us/updates/v2/sql-insights-retirement) message on a SQL Insights workbook.
> Add the retirement message

- Workbooks/Network Insights/ExpressRouteCircuits/ExpressRouteCircuitMetrics/ExpressRouteCircuitMetrics.workbook
> Fix Bug in ExR Workbook

- Workbooks/Azure Feature Experimentation/Experiment Analysis/Experiment Analysis.workbook
Testing in PPE identified that passing parameter values via URL only works if the parameters do not reside within a group. This change moves the parameters outside the group (impact to layout is minimal).
> Update parameters in Experiment Analysis workbook

- Workbooks/Workloads/SAP/Inventory Checks for SAP/Inventory Checks for SAP.workbook
Updating the Azure NetApp Files Monitoring stats for Azure Files Backup and view to monitor the ANF Volume threshold using TimeRange parameter
1) Added view to monitor the ANF Volume Threshold history to help customers/partners monitoring the ANF usage & 2) Added view to monitor the ANF Files backup that will help customers monitor amount of data transferred from ANF Volume to managed storage account. One of the ways to monitor amount of data transferred to managed storage account.
Tested the changes on Internal subscriptions
> Update Inventory Checks for SAP October 2024

- Workbooks/Azure Logic Apps/Integration Environment Application/FilteredAPIM/FilteredAPIM.workbook
- Workbooks/Azure Logic Apps/Integration Environment Application/FilteredServiceBus/FilteredServiceBus.workbook
- Workbooks/Azure Logic Apps/Integration Environment Application/IntegrationEnvironmentApplication.workbook
- Workbooks/Azure Logic Apps/Integration Environment Application/IntegrationLogicApps/IntegrationLogicApps.workbook
- Workbooks/Azure Logic Apps/Integration Environment Insights/IntegrationEnvironmentInsights.workbook
- Workbooks/Azure Logic Apps/Integration Environment/README.md
The previously added workbook for Integration Environment Applications had incorrect directory name of 'Integration Environment'. We need that name for a different dashboard, so the folder is being duplicated to preserve backwards compat.
So there are now three folders:
- Integration Environment: This is the original untouched folder currently referenced from portal for Integration Environment Applications. We will leave this alone until transition is complete.
- Integration Environment Application: This is what Integration Environment should have been from the start. We made it by duplicating all the files from Integration Environment and just changing the directory name. The portal's current references to Integration Environment will change to Integration Environment Application.
- …
> Prepare for upcoming workbook refactors in Logic Apps AIS

- Workbooks/Database watcher/Azure SQL Database/database/database.workbook
- Workbooks/Database watcher/Azure SQL Database/elastic pool/elastic pool.workbook
- Workbooks/Database watcher/Azure SQL Database/estate/estate.workbook
- Workbooks/Database watcher/Azure SQL Managed Instance/estate/estate.workbook
- Workbooks/Database watcher/Azure SQL Managed Instance/instance/instance.workbook
- Workbooks/Database watcher/SQL Server/estate/estate.workbook
- Workbooks/Database watcher/SQL Server/instance/instance.workbook
Fix duplicate parameter IDs.
* [n/a] post a screenshot of templates and/or gallery changes
> [database watcher] Make parameter IDs unique

- Workbooks/Azure Advisor/AzureServiceRetirement/Azure Services Retirement.workbook
Added an info banner at the top
> Update Azure Services Retirement workbook

- Workbooks/Online Experimentation/Experiment Analysis/Experiment Analysis.workbook
* Default view shows all metrics
* Number formatting for columns: Control value and Treatment value
* Add tooltip to column: Effect estimate
> Minor updates to Experiment Analysis workbook

- CODEOWNERS
- Workbooks/Azure Machine Learning/AI Studio/AtResource/AI-Studio-Insights.workbook
Minor changes to AI Studio Insights
> Ignite changes AI studio Insights

- gallery/workbook/microsoft.experimentation-experimentworkspaces.json
set "isPreview" to false on Experiment Analysis workbook
> Remove preview flag from Experiment Analysis workbook

- Workbooks/Azure Machine Learning/AI Studio/AtResource/AI-Studio-Insights.workbook
> AI studio Insights Patch

- Workbooks/Database watcher/Azure SQL Database/database/database.workbook
- Workbooks/Database watcher/Azure SQL Database/elastic pool/elastic pool.workbook
- Workbooks/Database watcher/Azure SQL Database/estate/estate.workbook
- Workbooks/Database watcher/Azure SQL Managed Instance/estate/estate.workbook
- Workbooks/Database watcher/Azure SQL Managed Instance/instance/instance.workbook
- Workbooks/Database watcher/SQL Server/estate/estate.workbook
- Workbooks/Database watcher/SQL Server/instance/instance.workbook
- Workbooks/Database watcher/watcher.workbook
Use the latest database watcher API version, `2024-07-19-preview`.
> [database watcher] Use the latest API version

- Workbooks/Azure Security Center/Cost Estimation/CostEstimation.workbook
> ASC: Update cost estimation workbook with GCP Servers plan

- gallery/workbook/microsoft.apimanagement-service.json
The workbook has been used for a while in embedded blade, we're looking to make it available for customers to explore how it is built and modify as necessary.
> Releasing APIM workbook

- Workbooks/Azure Logic Apps/B2B Tracking/Integration Account Tracking/IntegrationAccountTracking.workbook
> Get IntegrationAccountResourceId parameter from passed componentid

- Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook
Version change for 'Add Multipath as UdpType to the Connection Reliability tab' changes.
[https://github.com/microsoft/Application-Insights-Workbooks/pull/2878
](url)
> Version Change for Multipath

- Workbooks/Global Secure Access/Microsoft Entra Internet Access/Enriched Microsoft 365 logs/Enriched Microsoft 365 logs.workbook
Add deprecation notice for Enriched Microsoft 365 Logs workbook
> Add deprecation notice for Enriched Microsoft 365 Logs workbook

- Workbooks/Online Experimentation/Experiment Analysis/Experiment Analysis.workbook
This PR is to add a new parameter which can hide or show log analytics workspace and time range dropdowns.
url to show LAW and timerange dropdowns - https://ms.portal.azure.com/?feature.workbookGalleryBranch=vebudumu%2FAnalysisWorkbookChanges#view/AppInsightsExtension/UsageNotebookBlade/ComponentId/%2Fsubscriptions%2F80d2c6c6-fa64-4ab1-8aa5-4e118c6b16ce%2FresourceGroups%2Fexponexpgroup%2Fproviders%2FMicrosoft.Experimentation%2FexperimentWorkspaces%2Fexponexp/ConfigurationId/community-Workbooks%2FOnline%20Experimentation%2FExperiment%20Analysis/WorkbookTemplateName/Experiment%20Analysis/NotebookParams~/%7B%22Workspace%22%3A …
> Experiment Analysis Workbook - Show or hide log analytics workspace dropdown

- Workbooks/Communication Services/Voice_Video/Voice_Video.workbook
mapping to sub-template has a typo
> Call Insights - fix sub-template mapping typo

- Workbooks/Azure Monitor - Workspaces/Usage Insights/Usage Insights.workbook
https://msazure.visualstudio.com/One/_workitems/edit/28477514 https://msazure.visualstudio.com/One/_workitems/edit/28452139 https://msazure.visualstudio.com/One/_workitems/edit/28452031 https://msazure.visualstudio.com/One/_workitems/edit/28451996 https://msazure.visualstudio.com/One/_workitems/edit/30813356
When done correctly, this …
> Update Usage Insights.workbook to address bugs

- Workbooks/Azure Monitor - Workspaces/Usage Insights/Usage Insights.workbook
> Update Usage Insights.workbook Show LAW query for all widgets

- Workbooks/Communication Services/Insights_legacy/Insights_legacy.workbook
- Workbooks/Communication Services/Voice_Video_Volume/Voice_Video_Volume.workbook
Fix timeseries graph column map configuration
fix legacy insights workbook mapping
> Fix Volume tab timeseries graph in "daily" view

- Workbooks/Azure Machine Learning/AI Studio/FoundryDashboard/FoundryDashboard.workbook
- gallery/workbook/microsoft.insights-components.json
- gallery/workbook/microsoft.machinelearningservices-workspaces.json
- test/jsonValidationTest.js
Adds a preview template for AI Foundry.  The templates are marked isPreview so they dont' show up in the gallery by default (i can remove the gallery entries entirely if requested)
> add preview version of foundry dashboard

- Workbooks/Network Insights/LoadBalancerWorkbooks/NetworkInsights-LoadBalancerMetrics/NetworkInsights-LoadBalancerMetrics.workbook
- Workbooks/Network Insights/VirtualNetworkGatewayWorkbooks/NetworkInsights-VirtualNetworkGatewayMetrics/NetworkInsights-VirtualNetworkGatewayMetrics.workbook
> Update LB and Vnet Gateway workbooks

- Workbooks/Azure Monitor - Workspaces/Metrics Usage Insights/Metrics Usage Insights.workbook
> Update Top 10 Metrics Daily Timeseries Trend query

- Workbooks/Online Experimentation/Experiment Status/Experiment Status.workbook
> Add option to hide workspace selection in experimentation status workbook

- Workbooks/Azure Monitor - Workspaces/Metrics Usage Insights/Metrics Usage Insights.workbook
**Two Diagnostic Settings and no Data being ingested **
Before
After
> Update workbook to handle edge case of multiple diagnostic settings with different category type (logs or metrics usage details)

- Workbooks/Azure Machine Learning/AI Studio/FoundryDashboard/FoundryDashboard.workbook
This PR commits some changes that fix visual glitches in Foundry Dashboard.
> 🔧 Fix Foundry Dashboard tile dimensions

- gallery/workbook/microsoft.monitor-accounts.json
Remove IsPreview setting for metrics usage insights workbook
> Remove IsPreview setting for metrics usage insights workbook

- Workbooks/Azure Monitor - Workspaces/Metrics Usage Insights/Metrics Usage Insights.workbook
Update Documentation links in metrics usage insights workbook.
replace with https://learn.microsoft.com/azure/azure-monitor/metrics/metrics-usage-insights 
> Update Documentation links in metrics usage insights workbook

- Workbooks/Azure Update Management Center/compliance-tab/compliance-tab.workbook
This is just a minor text fix. (Please check "File changes" section)
No visible change.
- https://ms.portal.azure.com/?feature.workbookGalleryBranch=eap%2Fapanchal%2FfixSourceForComplianceTab#view/Microsoft_Azure_Automation/UpdateCenterMenuBlade/~/workbook
- Verified using the link above (check SS).
> [Azure Update Manager] Fix blade source

- Workbooks/Azure Monitor - Workspaces/Metrics Usage Insights/Metrics Usage Insights.workbook
Update lookback of datapresent
> Update lookback of datapresent

- Workbooks/Azure Machine Learning/AI Studio/FoundryDashboard/FoundryDashboard.workbook
remove evaluation metrics text item and replace it with title on the tiles with rowcount showing
turns on open external query button on all the items that do queries
> turn on showAnalytics in steps doing queries

- Workbooks/Azure Machine Learning/AI Studio/FoundryDashboard/FoundryDashboard.workbook
> 🔧 Foundry dark mode improvements

- CODEOWNERS
- Simple change to add a new resource to the codeowners file.
> adding cosmos db fleets

- Workbooks/CosmosDb/Overview/Overview.workbook
Rolling back overview blade removing merge query for throttled request percentage
> rolling back overview changes

- Workbooks/Azure Active Directory Provisioning/AAD cloud sync Insights (Preview)/AAD cloud sync Insights.workbook
Update template id in workbook link
Update templateId value in workbook to correct value. Previous path was incorrect.
> Update AAD cloud sync Insights.workbook

- Workbooks/Azure Advisor/Cost Optimization/CostOptimization.workbook
Add changelog tab in the Overview page
Update the Cost Optimization workbook and added a changelog tab.
> COW Update overview page

- Workbooks/Azure Security Center/Vulnerabilities/Vulnerabilities.workbook
> Fix sql unhealthy resources count query
