Workbooks/Usage/Retention - N Period/settings.json
Workbooks/Usage/Usage Calendar/Usage Calendar.workbook
Workbooks/Usage/Usage Calendar/settings.json
Workbooks/Usage/Usage by hours of the day/Usage by hours of the day.workbook
Workbooks/Usage/Usage by hours of the day/settings.json

Also include a chance to hide the N-period retention template from the Usage group of AI workbooks. Eric, you should confirm that not having a gallery entry will be fine with the template service.

Add usage pattern templates (calendar, hours of day) to AI workbooks

---

Workbooks/Usage/Authenticated User Timelines/Authenticated User Timelines.workbook

The sessions grid at the bottom is "broken" once there's a selection there, so after you select a row in the bottom, changing users at the top won't do anything.
The sessions query step both “consumes” UserId, and it also says it “exports” UserId as well.  So once a row is selected in that bottom grid, it is ignoring any incoming change to UserId since it has its own value now “locked” by the selection in the grid.
This step just shouldn’t have that checkbox set.  That step was probably cloned from the previous query and then the query changed, leaving this field intact.
This removes that exported selection parameter in that step.

remove export of userId in the sessions grid, it is breaking this step

---

Workbooks/Virtual Machines/Virtual Machine Performance/Single Virtual Machine Performance.workbook

Initial attempt at workbook for Single VM performance view of Azure Monitor for VMs. This contains the following:
* Seven charts mirrored from Single VM Insights page
* Grid where user can select a machine to view stats
* Chart where user can view any counter
Initial state
Select a workspace and a VM
<edit: updated screenshot>

Add Workbook for Single VM Performance - Azure Monitor for VMs

---

Workbooks/Virtual Machines/Virtual Machine Performance/Single Virtual Machine Performance.workbook

Change the `computer` parameter to sentence case (i.e. `Computer`) so it
will correctly receive the current computer name when the user navigates
to this workbook from a single VM chart.
- Change `computer` hidden parameter to `Computer`
- Adjust kusto query to remove unused clause

Fix Single VM chart workbook

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/Performance Analysis for a Single VM.workbook

The Metrics notebook parameter was colliding with the other charts in
the latter half of the workbook. Changing the top-most Metrics to
ChartMetrtics to prevent overriding the defaults of the other charts.

Change Metrics name to ChartMetrics

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/Performance Analysis for a Single VM.workbook

Single VM workbooks supports custom query for charts such as network and
max logical disk used that cannot be generalized. Also rearranged the
parameters so they appear in a column due to conditional visibility.
Removed "createdTime" from TimeRange parameter as that is not deemed
necessary.
Custom Query:
Regular (Non-Custom Query):

Add custom query field

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/settings.json

GridRefresh: This will conditionally refresh below grid.
ComputerNameContains:  Search computers in the workspace.
Hierarchy: Defines how deep the aggregations go.
Example:
No Filter, Hierarchy: Computer -> Process
Filter: local, Hierarchy: Computer -> Process -> IP -> Port
Rolling up Malicious Connections:

Connections Overview Workbook

---

Workbooks/Virtual Machines/Virtual Machine Performance/Virtual Machine Performance.workbook

Opening this workbook from Single VM gallery will automatically select a default workspace

Fix vm perf workbook from single vm gallery

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/settings.json

Improve UX of group perf workbook and have it only shown when accessed from AtScale Monitor
- Rename workbook to `Performance`
- Minor cosmetic fixes
- Hide workbook dropdown
- Add helper text
- Add missing heatmap to table
- Split parameters for all the charts
- Fix erroneous dropdown
Example:

Update VM Group Perf Analysis Workbook

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/Performance Analysis for a Single VM.workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/settings.json
Workbooks/Virtual Machines/Virtual Machine Performance/settings.json

Further polish Single VM performance analysis workbook to bring it more
in line with its AtScale counterpart. Also delist a duplicate workbook
since that has been incorporated into this workbook. Update cosmetic
look-and-feel and add helper text to aid end-user in navigating around
this workbook.
- Rename workbook to "Performance" in Single VM gallery
- Delist "Virtual Machine Performance" workbook from Single VM gallery
- Add and update helper text
- Cosmetic changes for easier readability
- Align parameter names with AtScale Performance workbook
- Minor fix in last chart to use correct parameter

Update Single VM workbook

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/settings.json

`Connections Overview` now appears in Single VM workbooks gallery. Additional helper text and support for Virtual Machine resource has been added to the workbook.
Single VM
AtScale

Add Single VM support in Connections Overview

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/settings.json

Include `isSelected` item in `Computers` dropdown in order to handle
edge cases where `All` item isn't selected by default. Also put the
parameters into a single line for AtScale, hence the copied workbook for
Single VM, for performance reasons.
Overview:

Fix Connections Overview workbook for AtScale

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook

Cosmetic and performance updates to the workbook. 25% faster chart
rendering time by only querying the chart that is being shown. Fix
extraneous charts being re-rendered when `Counter` dropdown is changed.
Improve cosemtic change for `Counter` dropdown.
- Make top table full-length
- Remove top graph
- Improve performance with query snippets
- Minor change to `Aggregation`
- Move `Aggregation`s under each chart title
- Move `Counter` dropdown same section as the top table
- Fix `Counter` not selecting a default counter upon initialization
- Improve `Counter` dropdown
- Fix only top chart being refreshed when `Counter` is selected
Preview:

Update VM Group Performance Workbook

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook

Fixed computers not showing in the table list for AtScale Connections
Overview. Recent changes in default workbooks query broke this workbook
causing the computer name to be wrongly populated.
Preview

Hotfix Connections Overview

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/Performance Analysis for a Group of VMs.workbook

Save additional vertical real-estate by moving helper text within the
parameters. Also set the default counter of the table to `Processor
Time`
Preview:

Move helper text within parameters

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/Connections Overview.workbook

Bring Connections Overview workbook for Single VM to parity with its
AtScale counterpart. Includes all fixes such as inbound connections and
additional filters.
Preview:

Update Connections Overview for Single VM

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM/Performance Analysis for a Single VM.workbook

Align Performance Analysis workbook with its AtScale counterpart. Minor
cosmetic changes including changing `Percentiles` label back to
`Aggregates`. Also improve `Counter` dropdown.
Preview:

Update Performance Analysis for Single VM

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook

Major update to Connections Overview workbook for At-Scale VM Insights.
Various bug fixes such as fixing the inbound direction table entries.
Also showing detailed information for all levels, and not just for
computers. Lastly, add additional filters to only show malicious
connections, links failed, and above average response time. Minor
cosmetic changes to the workbook.
Preview (AtScale)
Preview (SingleVM)

Update Connections Overview workbook

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/Connections Overview.workbook

Minor fix to `TableFilter` dropdown with improperly defined JSON. Also consolidate `EmptyOrOnboarded` into `Test` hidden parameter to check to see if VM has been onboarded or not.

Fix TableFilter dropdown

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook

Add log analytics button to always show on grid. Requested by customer. More diffs than usual due to template changes on PPE.
AtScale
SingleVM
Pin to dashboard
Test
* Verified log analytics blade works
* Verified pin to dashboard works

Add log analytics button to grid

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook

while working on workbook links, I found 2 parameters here that were working by inheriting the workspace from resources instead of using the workspace parameter.  
(in my links branch, the resourceIds for the workspace is *only* a vm id, it might be the case that from your blade you're passing both the workspace *and* virtual machine ids in resource ids?)

Connections Overview: fix a couple params not using the workspace param

---

Workbooks/Failures/Failure Insights/Failure Insights.workbook

for Bug 1441498: [Screen Reader - Application Insights E2E - Failure Analysis] When focus received 'Failed Operations' and 'All Operations' graph chart, screen reader not given relevant information
switched text steps for chart headers to actual chart headers, added failure text:

move text step headings into chart headings, set no rows text

---

Workbooks/Azure Monitor - Workspaces/Workspace Usage/Workspace Usage.workbook

this template has a resource id in it, causing it to try to select that sub instead of the value returned as default in the query

remove hardcoded subscription selection

---

Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/Performance Analysis.workbook
Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/settings.json
Workbooks/Virtual Machine Scale Sets - Performance Analysis/categoryResources.json
Workbooks/Virtual machine Scale Sets - Network Dependencies/Active Ports/Active Ports.workbook
Workbooks/Virtual machine Scale Sets - Network Dependencies/Active Ports/settings.json
Workbooks/Virtual machine Scale Sets - Network Dependencies/Connections Overview/Connections Overview.workbook
Workbooks/Virtual machine Scale Sets - Network Dependencies/Connections Overview/settings.json
Workbooks/Virtual machine Scale Sets - Network Dependencies/categoryResources.json

Workbooks for VMSS.
Since most of the workbooks applicable to At Scale are also applicable to VMSS and some to VMs, we should be creating ResourceType agnostic workbooks when we can. 
'Active Ports' is an attempt at that, unfortunately there is a bug which restricts the parameter use. Hence I have duplicated 'Connections Overview' and 'Performance Analysis' workbooks. 
'Connections Overview' also takes advantage of JSON type, making the workbook run query much faster.  This can be enhanced to complex JSON structures, but due to shortage of time, I have kept it as simple  as possible.

Initial checkin for VMSS workbooks

---

Workbooks/Individual Storage/Transactions by Storage Type/Transactions by Storage Type.workbook

Removes the split by in the first chart.

Remove split by in one of the templates

---

Workbooks/Virtual Machines - Performance Analysis/Resource Monitor/Resource Monitor.workbook

Add dropdowns to show or hide help text for each metric and enable or
disable running their respective queries. All but one query is disabled
by default for workbook performance reasons.

Clean-up Resource Monitor workbook

---

Workbooks/Storage/Overview/Overview.workbook

Fixed:
1. Subscription parameter ARG query get its values from 'All subs' instead of 'Default subs'
2. Increased the sub limit to 20.

Fix an issue with storage sub picker

---

Workbooks/Storage/Overview/Overview.workbook

Simplifies the edit experience:
1. Use only the metric control (no merge control).
2. Simplifies parameters (removed default sub and visibility param)
3. Removed the storage account counts and replaced with a banner at the bottom.

Update storage at-scale template

---

.travis.yml
README.md

I added the travis link to readme, and it shows the right icon for build status but clicking it went to Travis's docs instead of our builds

fix link to open right travis link, try to build master AND pr builds

---

Workbooks/Individual Storage/Overview/Overview.workbook

Summary step was defaulting to 1 hour instead of using the time parameter

Storage Insights: Resource Overview should take time param

---

Documentation/Visualizations/Graph.md
Workbooks/Individual Storage/Overview/Overview.workbook
Workbooks/Storage/Overview/Overview.workbook

Limit the formatting of tiles to 2 decimal places
Sometimes metrics returns split by error as lower case success. Add a regex to handle lower case success

SAI: Add number formatting to tiles, add missing column match in overview

---

Workbooks/CosmosDb/Overview/Overview.workbook

the previous commit to the template changed the cosmosdb query to also return subs instead of changing the subs query
moved the subs query to the subs param, restored the previous query for cosmosdb param

fix cosmosdb template

---

CODEOWNERS

This should enable automatic reviewers on various paths in the repo, and teams that want to add their own teams as owners on paths for their templates can.
see https://help.github.com/en/articles/about-code-owners
I don't think this will start working until it is checked in though, so i'm not positive all the paths and syntax are correct until people start creating prs after that?

add codeowners file which will automatically add reviewers

---

Workbooks/Storage/Capacity/Capacity.workbook
Workbooks/Storage/Overview/Overview.workbook

Column name option has been removed from metric pills and moved to column label options in settings blade. Remove column name from each metric setting and move it to column label settings.
Removes the confusion where someone tries to change Availability metric  to say Egress metric but the column name still says Availability.

Storage Insights: Use column labels

---

Workbooks/SapMonitor/SapHanaInfrastructure/SapHanaInfrastructure.workbook

Starting from the previous PR #375, there is a parameter (`testDataExist`) that will probe if the ingested custom logs have already "arrived" to Log Analytics. This was originally (wrongly) used in the user parameters, and then moved to the top of the workbook template. However, it referenced `TimeRange`, which was not set at the moment.
For the purpose of checking if data already exists, I've "hard-coded" a 30 minutes threshold which resolves this issue. Going forward, a more elaborate method can be used.

Fix SAP Monitor v2 (modify TimeRange)

---

test/jsonValidationTest.js

workbooks can have this field, templates cannot, so nothing in this repo should have that field set

add check to prohibit content from having "fromTemplateId" field

---

Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook

Minor cosmetic fix to Performance Counters workbook by removing an unused parameter. The parameters were probably introduced as part of a feature enhancement to the workbook, but was never implemented and utilized in our Ibiza extension. Important changes are between lines `183` and `192`. The rest of the diffs are due to template update from the workbooks extension.
Overview:
Before with broken parameter

Remove unused parameters

---

Workbooks/Virtual Machines - Network Dependencies/Active Ports/settings.json
Workbooks/Virtual Machines - Network Dependencies/Connection Records/settings.json
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/settings.json
Workbooks/Virtual Machines - Network Dependencies/Failed Connections/settings.json
Workbooks/Virtual Machines - Network Dependencies/Open Ports/settings.json
Workbooks/Virtual Machines - Network Dependencies/Security and Audit/settings.json
Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/settings.json
Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/settings.json
Workbooks/Virtual Machines - Network Dependencies/VM Events/settings.json
Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs/settings.json
Workbooks/Virtual Machines - Performance Analysis/Performance Counters/settings.json
Workbooks/Virtual Machines - Performance Analysis/Resource Monitor/settings.json

I pushed these same changes to https://github.com/ericc1103/Application-Insights-Templates-Dev but for some reason the Log Analytics workbook gallery is still showing VM Insights templates. Will take a look again tomorrow.

Remove VM Insights workbooks from workspace gallery

---

Workbooks/CosmosDb/Overview/Overview.workbook

Add operation tab
Margin between the tabs control and the metric grid
Use custom column name for Capacity tab columns

cosmosdb, operations tab and other cosmetic changes

---

CONTRIBUTING.md
Documentation/Contributing.md
README.md

added a top level contributing doc about getting contributor access, etc, instead of having that point to details about contributing templates.
links from the main readme go to the new page, which also has a link to the template details docs

add top level contributing docs

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Preview)/Performance Analysis for a Single VM.workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Preview)/settings.json

Use the new InsightsMetrics table, workbook is behind preview flag

Add Preview Single VM Perf workbook using InsightsMetrics

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview - Single VM/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook

KQL comments were originally introduced for better loading user experience. Recent updates in workbooks makes adding such KQL comments unnecessary. Also KQL queries were causing problems when the query strings were getting too long.
AtScale
SingleVM

Remove unnecessary KQL comments

---

Workbooks/CosmosDb/Overview/Overview.workbook

Showing operations as column instead of part of hierarchy.

Operations tab changes

---

CODEOWNERS
CONTRIBUTING.md

Added default owners from recent history. 
If a folder ended up with only one owner, I added our team again so that it isn't just one owner.
From how I read https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners, it implies to me that the last entry that applies wins, so it could end up with one person being required, but you can't approve your own PRs so without that people would be stuck?
i'm sure there will be some growing pains with this, so bear with us!

Update CODEOWNERS with defaults for each folder

---

schema/corhort.json

Add cohort schema
Note: The only thing localize-able currently is the markdown text only. For some reason the parameter is stringified in the save object so there's no way to mark the labels as localize-able.

Add cohort schema

---

Workbooks/SapMonitor/SapHanaInfrastructure/SapHanaInfrastructure.workbook

This PR resolves the following issues:
- Include y-scale support for "CPU %" and "Memory %" charts
- Fix host status for HANA scale-out (now displays host names)
- Fix visibility of "Memory anomalies" chart

Add y-scaling for % charts, fix scale-out support

---

CODEOWNERS

it doesn't look like GitHub/whatever codeowners parsing likes spaces in filenames, so it is basically falling back to everything owned by us.  it looks like spaces for stars was the best thing that worked "cross platform", we'll see what GitHub says after it gets completed?

replace spaces in codeowners file with stars

---

Workbooks/Resource Groups/Sql databases/Sql databases.workbook

Telemetry is showing many failures in this workbook. After further investigation, metrics provider is returning 400s for the DTU percentage metric due to the fact that data warehouses do not support this metric. https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-concept-resource-utilization-query-activity
Removing DTU % from the template

SQL database Workbook: Remove DTU % Metric

---

Workbooks/Resource Groups/Sql databases/Sql databases.workbook

Second and hopefully last fix for SQB DB resource group template. Previously I removed one metric due to failing metrics call. Turns out there are many restrictions on which metrics are enabled. 
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftsqlserversdatabases
Changing the template to only use metrics that are enabled for all sql types

SQL DB Resource Group Insights Fix

---

scripts/ProcessTemplates.ps1

sometimes loc branches are missing some .json and .workbook files so the script copies them from master to loc branches when processing the templates. however, when the .workbook filename changes, this process could copy and have multiple .workbook in a directory and the tool will fail. this fix will check if .workbook already exist in the loc branches and skip copying another .workbook file over

skip copy workbook in loc if exist

---

.gitattributes
.github/CODE_OF_CONDUCT.md

* Adds .gitattributes that should ([according to this](https://github.com/github/linguist#using-gitattributes)) make `.workbooks` and `.cohorts` files treated as json files in github for compares, etc
* also adds the standard microsoft open source code of conduct markdown file as well.

treat workbook, cohort files as json in github

---

Workbooks/View Designer/Donut-List/Donut & List.workbook
Workbooks/View Designer/Line Chart Callout List/Line Chart Callout List.workbook
Workbooks/View Designer/Number List/Number & List.workbook
Workbooks/View Designer/Tabbed/Tabbed Views.workbook
Workbooks/View Designer/Timeline List/Timeline & List.workbook
Workbooks/View Designer/Two Numbers & List/Two Numbers & List.workbook
Workbooks/View Designer/Two Numbers & List/settings.json
Workbooks/View Designer/Vertical Overview/Vertical Overview.workbook
Workbooks/View Designer/Vertical Overview/settings.json
Workbooks/View Designer/View Designer Transition Guide/View Designer Transition Guide.workbook

* Removed the outlines from all the visualizations, decreased spacing between steps, and added filters for all grids
* Adding a few modified instructions to clarify the steps on how to make the workbook
* Small query fixes to drop the | render chart in favor of using workbooks visualization controls
* Added a vertical layout template and a two numbers & list template
* Reverted all single number instances to tiles from a parameter text placeholder

View Designer Template QOL Fixes

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/Performance Analysis for a Group of VMs (Dev).workbook

Moved all queries back to workspace-centric queries. User will first
select appropriate workspace regions based on subscriptions and resource
groups. The Virtual Machines dropdown is now based off of workspace
`InsightsMetrics` with query snippets.
- Update query to read from workspaces
- Expand subscription selection scope
- Attempt to fix default counter and subscription
- Empty counter prompt
- Fix Top 10 charts to workspace-centric queries
- Add virtual machine dropdown based off of workspaces InsightsMetrics
- Add Query filter by virtual machines
- Optimize selecting virtual machines
Top 100
Top 10

Add workspace regions

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/Performance Analysis for a Group of VMs (Dev).workbook

Previous implementation only fetched workspaces from the respective
sub/rg. This change will instead retrieve workspaces from VMs onboarded
to the respective sub/rg utilizing ARM parameters.
NOTE: there may be a bug where this workbook will be broken upon
initialization.
- Change sub and RG to single-select
- Add armPrefix parameter
- Modify workspaces dropdown to read from ARM
- Filter workspaces through ARG
- Workspaces respect workspace regions

Retrieve workspaces and VMs via Service Map API

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/Performance Analysis for a Group of VMs (Dev).workbook

Malformed ARM URLs caused the ARM parameter to error out resetting the
"All" default value upon initialization. Also modified the `vmSnippet`
so that it will only show VMs in currently selected sub/RG.
- Change to armUrl
- Make Workspaces dropdown not required
- Fix workspaces ARM parameter
- Filter workspace query to scoped onboarded VMs

Fix malformed ARM URLs

---

Workbooks/Virtual Machines - Network Dependencies/Connections Overview (Dev)/Connections Overview (Dev).workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview (Dev)/settings.json

Utilize the appropriate Azure-mode scope selections so that only
onboarded VMs and their respective reporting workspaces will be shown in
the workbook. Optimized the workbook by converting all query snippets to
use the Criteria parameter.
- Expand subscription context
- Import workspace region parameters
- Convert all query snippets to criterias
- Replace using vmSnippet
- Fix single selection Connections grid
- Update parameter names to avoid conflict
- Add table placeholders
- Fix empty GridDestinationPort table parameter

Optimize Connections Overview workbook

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Group of VMs (Dev)/Performance Analysis for a Group of VMs (Dev).workbook

Provide better user experience with top-level scope selectors by
auto-filtering subscriptions with VMs all the way to filtering relevant
locations and resource groups.
- Fix selecting default resource group
- Fix selecting resource group if passed in
- Update Test parameter
- Prevent malformed ARM URL

Optimize top-level scope selectors for VM Group Performance

---

Workbooks/Virtual Machines - Network Dependencies/Security and Audit/Security and Audit.workbook

Add a `Test` parameter to check for data in `VMConnection` table and show onboarding prompt.
Not onboarded
Onboarded

Show onboarding prompt when missing VMConnection

---

Workbooks/Azure Active Directory/EntitlementManagementAccessPackageActivity/EntitlementManagementAccessPackageActivity.workbook
Workbooks/Azure Active Directory/EntitlementManagementAccessPackageActivity/settings.json

Remove the preview flag from this workbook, and shorten workbook title so that it fits into the gallery tile in English.  Update the capitalization in the workbook top heading to match that of other Azure AD workbooks.

Remove preview flag from Azure AD entitlement management access package activity workbook

---

Workbooks/Virtual Machines - Performance Analysis/Performance Analysis for a Single VM (Preview)/Performance Analysis for a Single VM.workbook

Minor fix to the Single VM Performance workbook template with grouping of the counter dropdowns.

Fix dropdown grouping

---

Workbooks/Virtual Machines - Network Dependencies/Active Ports/Active Ports.workbook
Workbooks/Virtual Machines - Network Dependencies/Connections Overview/Connections Overview.workbook
Workbooks/Virtual Machines - Network Dependencies/Failed Connections/Failed Connections.workbook
Workbooks/Virtual Machines - Network Dependencies/Open Ports/Open Ports.workbook
Workbooks/Virtual Machines - Network Dependencies/TCP Traffic/TCP Traffic.workbook
Workbooks/Virtual Machines - Network Dependencies/Traffic Comparison/Traffic Comparison.workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook

Support non-onboarding scenarios across all the hybrid workbooks since
they can be accessed via Azure mode from VM Insights. In addition, clean
up some of the queries and minor optimizations using the Criteria
parameter. The Performance Counter workbook was updated to use
InsightsMetrics and revamped with fewer charts for better performance.
- Add test parameter to Active Ports template
- Add test parameter to Open Ports template
- Fix test parameters and update Failed Connections template
- Clean-up queries in Failed Connections template
- Add onboarding support to TCP Traffic template
- Update Traffic Comparison template
- Update hybrid Connections Overview workbook with onboarding prompt
- Revamp Performance Counters workbook
- Add prompt to Open Ports template
Connections Overview …

Add test parameters to VM Insights templates

---

Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Perf)/Performance Counters (Perf).workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Perf)/settings.json
Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Preview)/Performance Counters (Preview).workbook
Workbooks/Virtual Machines - Performance Analysis/categoryResources.json
Workbooks/categoryResources.json

Introduce Perf version of the Performance Counters VM Insights template
to support existing customers. Also minor whitespace fix.
- Fix onboarding case in Perf Counters template
- Also fix formatting error in `categoryResources.json`
Test
--
Performance Counters (Perf)
Performance Counters (Insights Metrics)

VM Insights Performance Counters update with Perf and InsightsMetrics

---

Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis (Perf)/Performance Analysis (Perf).workbook
Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis (Perf)/settings.json
Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis (Preview)/Performance Analysis (Preview).workbook
Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/Performance Analysis.workbook
Workbooks/Virtual Machine Scale Sets - Performance Analysis/Performance Analysis/settings.json

Update VMSS Perf workbooks to use InsightsMetrics. The regular and preview templates are the same, the preview will eventually be deprecated as with the other VM Insights templates. The Perf based iteration was copied over with the Perf suffix.
Test
-
VMSS Perf
VMSS InsightsMetrics

Update VMSS Perf workbook

---

Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Perf)/Performance Counters (Perf).workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Counters (Preview)/Performance Counters (Preview).workbook
Workbooks/Virtual Machines - Performance Analysis/Performance Counters/Performance Counters.workbook

Update the templates and ensure `queryType` is specified. Also optimized
the Performance Counter workbook to utilize non-LA based parameters to
reduce amount of LA queries.
Test
-
InsightsMetrics
Perf

Optimize Performance Counters templates

---

Documentation/DataSources/DataSources.md

fix link in data source docs
link had backslashes instead of slashes, so it can't find the file when you click it.

fix link in data source docs

---

Workbooks/SapMonitor/SapHanaInfrastructure/SapHanaInfrastructure.workbook

- PR #685 added a filter on the new provider instance concept, which has been introduced with content version 0.4.0.
- As there are still a few legacy customers who haven't updated their SAP Monitor resource, the schema of their custom logs does not have the underlying column PROVIDER_INSTANCE_s yet. Therefore, the queries in their workbooks fail and show no data.
- This hotfix adds backwards compatibility and resolves the issue by checking if the new column actually exists. Only then, the provider dropdown is actually shown to the user.

[HOTFIX] SAP Monitor: Add check if PROVIDER_INSTANCE_s column exists

---

Workbooks/Azure Resources/Alerts/Alerts.workbook

now that links to any view are enabled, add the ability to open up alert details from the alerts template.
the alert name column now opens the alert details:

add link to alerts details in alerts template

---

Workbooks/Individual Storage/Overview/settings.json

the at resource storage insights template isn't in the "storage-insights" gallery (nothing is), so that call to get templates for that gallery fails all the time.
and since it isn't in the gallery, when things like pins try to look it up to get its info, it doesn't get found since it isn't in a gallery.  so the pinned item shows up as "unknown":

make sure storage insights single resource is in a "gallery" so it can get looked up for metadata in that gallery

---

Workbooks/Individual Storage/Capacity/Capacity.workbook
Workbooks/Storage/Overview/Overview.workbook

Metrics chart show metrics in Bytes but tiles/graph is showing number format units in Bytes (SI). Since we can't change the metric chart number format, change the tiles/graph number format to Bytes instead

Storage Insights: Change Capacity metrics units from SI Bytes to Bytes

---

Workbooks/SapMonitor/SapHana.old/settings.json

Until we officially roll out the new SAP Monitor version, we would like to keep the old SAP HANA workbook template in the very front of the gallery. This way, we ensure it gets invoked automatically when a user clicks on the "Insights (Preview)" TOC node inside a SAP Monitor resource.

Moved old SAP HANA template to the front

---

Workbooks/SapMonitor/MsSqlServer/MsSqlServer.workbook
Workbooks/SapMonitor/PrometheusHaCluster/PrometheusHaCluster.workbook
Workbooks/SapMonitor/SapHana.old/settings.json
Workbooks/SapMonitor/SapHana/SapHana.workbook

- For our newly added workbook templates, resource type was missing and not properly passed; this causes the loading of the workbook template to fail with error message "No resources set."
- This fix addresses the issue by manually adding the following line to the pertinent queries:
`            "resourceType": "microsoft.operationalinsights/workspaces"`
- The fix has been applied on the latest version of the workbook templates.

Add resource type explicitly to queries

---

Workbooks/ADXCluster/AtScale/Insights.workbook
Workbooks/ADXCluster/AtScale/settings.json
Workbooks/ADXCluster/categoryResources.json

Copying the ADX At Scale workbook from Workbooks/Insights/ADXCluster to its new home here. The files in the original location
will be deleted once required changes in Azure Monitor Extension have been made.

Add ADX At Scale workbook to new location

---

Workbooks/SapMonitor/MsSqlServer/MsSqlServer.workbook

- In the workbook template for the MsSqlServer provider type, the dropdown (picker) for the provider instance defaults to using the last 24 hours. In cases where there is no "fresh" data, this would result in the workbook template becoming unusable, because the user cannot select a provider anymore.
- This PR extends the picker query by a 30-day filter to ensure users can at least select from previous providers.

SAP Monitor: Fix provider picker in MsSqlServer template

---

scripts/extractStrings.js

Originally wanted loc files to be under a string subfolder, but that would require manually adding a strings folder under every single workbook folder and requiring this folder being created going forward. Loc tool does not handle auto-creation of specified paths other than the {Lang} folder. So just removing the strings subfolder since it's not really needed.

Localization: Remove strings path

---

CODEOWNERS

Adds a line to the `CODEOWNERS` file that makes the workbooks team and the loc team the owners of all the loc `*.resjson*` files in the repo.  the loc process will start checking loc'd content into this repo instead of the 17 repos they have copied right now

add codeowners settings for loc files anywhere in the repo

---

Workbooks/Resource Insights/RedisCache/ResourceInsights.workbook

the same usedmemory2 metric was used twice, instead of usedmemory1

fix duplicate metric for shards

---

scripts/ProcessTemplates.ps1

Undoing just the part where we force all the files to be utf8 no bom.  it is messing up emojis in files that already are fine.  leaving the part that generates all of our generated files in the build as UTF8 (ps was generating UCS-2?)

Revert "force all json files to be UTF-8 no BOM"

---

CODEOWNERS

Changed CODEOWNERS to point to the azuremonitorforsapsolutions team instead of individuals on the team

update codeowners for azuremonitorforsapsolutions

---

CODEOWNERS

I noticed recently that suggested/reqiured reviewers aren't getting set by codeowners.
I opened a support ticket with github and was told:
> If any line in your CODEOWNERS file contains invalid syntax, the file will not be detected and will not be used to request reviews. 
> Invalid syntax includes inline comments and user or team names that do not exist on GitHub.
invalid syntax includes users that do not exist!
(it might also apply to teams that are marked "secret" instead of public, i still need to verify that part)
support told me this one, `csigs`, is not by itself a valid user, so the whole file is technically incorrect.

apparently a single invalid user can invalidate the entire codeowners file

---

package-lock.json

I'm not sure why the travis-ci build has started failing, it shouldn't require any keys/auth as all the packages the travis build needs are public.
`package-lock.json` lists some mseng packages references though, so maybe that is the issue?

remove mseng references from package-lock to fix travis-ci build?

---

Workbooks/AKS/Workload Details Persistent Volumes Tab/Workload Details Persistent Volumes Tab.workbook
Workbooks/AKS/Workload Details Persistent Volumes Tab/settings.json

Allow users to visualize the new PV usage data sent to InsightsMetrics, so that they can easily discover PVs with high usage and troubleshoot problems with usage and capacity for each workload. Users can filter by all PVs or only those with high usage and also select a specific one to see a detailed usage chart over the time frame.

Add PV Workload Workbook

---

test/jsonValidationTest.js

Reverts microsoft/Application-Insights-Workbooks#1041
somehow some commit here (a merge?) added a submodule for the localization folder which shouldn't exist.

Revert "make PR validation fail if you have a settings.json file but no workbook (catch spelling/etc errors of filenames)"

---

Workbooks/Azure Active Directory TroubleShooting/Provisioning/ProvisioningAnalysis.workbook

JobID and App filters will be defaulted to "All" to prevent from seeing error messages when viewing the workbook.

Define defaults for filters

---

scripts/extractStrings.js

Windows has a max of 260 chars. Output path can be reduced by not including redundant template name as it is not necessary to include in the file path (folder used as unique identifier).

Localization v2 - Reduce output path under 260 char

---

scripts/ProcessTemplates.ps1
scripts/npmPack.cmd
test/jsonValidationTest.js

Turns off --quiet on npm pack in the build pipeline so we can track down if that's the thing truncating filenames or if it is some other part of the build before that
adds a validation step to the PR validation that verifies that the path of the template doesn't exceed limits that appear to come from either the tgz format node uses, or from some limitation of the build pipeline

Add long file name/path validation to PR validation

---

Workbooks/UsageMetrics/Usage - Events/Usage - Events.workbook
Workbooks/UsageMetrics/Usage - Sessions/Usage - Sessions.workbook
Workbooks/UsageMetrics/Usage - Users/Usage - Users.workbook

* Fix error "bin(): argument #2 must be a positive constant timespan (1 tick or higher)" in barChartMode query

Fix bin 2nd argument error

---

Workbooks/Workloads-AMA/Azure SQL databases/Azure SQL databases.workbook
Workbooks/Workloads-AMA/Database Drilldown/File Sizes/File Sizes.workbook

- File sizes chart label now says "Data File(s) Used Size (KB)"

fix label for file sizes

---

Workbooks/Workloads-AMA/Azure SQL Managed Instance/Azure SQL Managed Instance.workbook
Workbooks/Workloads-AMA/Azure SQL Managed Instances/Azure SQL Managed Instances.workbook
Workbooks/Workloads-AMA/Azure SQL database/Azure SQL database.workbook
Workbooks/Workloads-AMA/Azure SQL databases/Azure SQL databases.workbook
Workbooks/Workloads-AMA/SQL Server/SQL Server.workbook
Workbooks/Workloads-AMA/SQL Servers/SQL Servers.workbook

- Remove 'Computer' as a split by options
- remove namespace 'sqlserver_performance' metrics from Azure SQL Dbs and Azure SQL MI
- only show the metrics applicable

Explore metrics fix

---

Workbooks/Virtual Machines/Virtual Machine overview/Virtual Machine overview.workbook
Workbooks/Virtual Machines/Virtual Machine overview/settings.json

Adds a simple template that wraps the existing vm details context blade template, and has an alerts tab to have a default metrics based template on VMs.
the gallery with my new item in it:
The default look of the workbook:
alerts tab:

Add a metrics based default single vm overview template

---

Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook

- use constant for telegraf userid

use constant for telegraf user id

---

Workbooks/AKS/Workload Details Persistent Volumes Tab/Workload Details Persistent Volumes Tab.workbook

Column labels for the PV usage grid were accidentally deleted at some point. Adding back in.

Workload Workbook PV Tab: Add back in column labels

---

Workbooks/Windows Virtual Desktop/WVD Insights/WVDWorkbookV1.workbook

Change TimeRange parameter default from 0 to 172800000

Fix TimeRange default value

---

Workbooks/Workloads-AMA/Custom Telegraf/Enable monitoring/Enable monitoring.workbook
Workbooks/Workloads-AMA/Enable monitoring/Enable monitoring.workbook
Workbooks/Workloads-AMA/Troubleshoot SQL logs/Troubleshoot SQL logs.workbook

- error filter now shows warning+Error
- updated logs to include warning icon
- fix bug where if a monitoring profile has multiple VMS, select the correct vm that was used to open logs

fix tsg error filter, selecting vm automatically

---

Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook

- Adding a VM to a profile now loads the existing WLI config if it exists

Load existing wli config per vm

---

Workbooks/CosmosDb/Resource Insights/Resource Insights.workbook

- Remove cosmos sub picker
- Can test via oychan-cosmos scale and clicking on one of the cosmos db's in overview tab

remove cosmos sub picker

---

Documentation/Contributing.md

This PR clarifies an item in Contributing.md that tripped me up and fixes a typo.
> Add `?feature.workbookGalleryBranch=[name of branch]` to the portal url.
was changed to
> Add `?feature.workbookGalleryBranch=[name of branch]` to the portal url. So you URL looks something like [https://portal.azure.com/?feature.workbookGalleryBranch=master](https://portal.azure.com/?feature.workbookGalleryBranch=master)
so it can't be confused for [https://portal.azure.com/?feature.workbookGalleryBranch=[master]](https://portal.azure.com/?feature.workbookGalleryBranch=[master]) (which does not work)
> Once you have add marked your template as `isPreview`, you can see this workbook by adding `feature.includePreviewTemplates` in your Azure Portal Url. So you URL looks something like …

Contributing.md clarifications

---

Workbooks/Workloads-AMA/Azure SQL Managed Instances/Azure SQL Managed Instances.workbook
Workbooks/Workloads-AMA/Azure SQL databases/Azure SQL databases.workbook
Workbooks/Workloads-AMA/SQL Server Insights/SQL Server Insights.workbook
Workbooks/Workloads-AMA/SQL Servers/SQL Servers.workbook

-fix logs bug when viewing from dbs overview

pass commonErrors param to child lworkbooks

---

README.md

updated the badge here to show the status of the template validation build against master:
`https://github.com/microsoft/Application-Insights-Workbooks/workflows/Template%20Validation/badge.svg`

Update the validation badge to use the github action instead of travis

---

Workbooks/Workloads-AMA/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads-AMA/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads-AMA/Update monitoring vm config/Update monitoring vm config.workbook

- if vms start with the same name, it could pull more than one vm config. This fixes it

fix issue where similar vm names would pull more than one config

---

Workbooks/SapMonitor/SapNetWeaver/SapNetWeaver.workbook

Workbook Updates
- Move legend tab to top for overview tab.
- change trendlines to area chart.
- group instance process by SIDs.
- Split performance tab content into Utilization and Performance.
- Add queue statistics tab with visualizations for queue utilization.
Workbook Screenshots:-

SapMonitor - SapNetWeaver Workbook Update

---

Workbooks/categoryResources.json

WVD is missing an entry in category resources, so it is showing its key instead of a label.

fix WDV showing a key instead of a label in azure monitor

---

Workbooks/Workloads-AMA/Collection logs/Collection logs.workbook
Workbooks/Workloads-AMA/Enable monitoring/Enable monitoring.workbook

fix case for update where metrics are not collected

---

scripts/extractStrings.js

Move block out one level because logic was supposed to happen once per directory, not per file.

Localization script fix: LocProject contains duplicate entries 

---

Workbooks/SapMonitor/Alerts/log-metric-noag.armtemplate
Workbooks/SapMonitor/Alerts/log-metric.armtemplate

Adding alert rule ARM templates to SapMonitor workbooks
Will be used by Alerts workbook in the future
They are currently the same as the ones used by SQL insights

Added alert rule ARM templates for SapMonitor

---

Workbooks/HDInsight/At-Scale/HDInsightAtScale.workbook

Removed "Selected" from monitored and unmonitored tiles.

remove Selected from tiles showing monitored and unmonitored clusters

---

Workbooks/ADXCluster/AtResourceClusterBoundaries/ResourceClusterBoundaries.workbook

Fixed cache utilization change by day to use avg instead of max to align with the other chart which uses avg.
Before - the changes aren't align with the left chart:
After:

Fixed cache utilization change by day to use avg instead of max

---

Workbooks/ADXCluster/AtResourceCache/ResourceCacheDetails.workbook

Like in Anita, they used to show users that are running queries with long lookback. can maybe correlate between the id in commands and queries.
Anita had the "Detailed View" Button.
It opens a grid (under the histogram) with columns for: User, application, Number of queries.
Once you clicked on a bar, the grid changed accordingly and showed the top users (by query count) who ran the queries for the selected lookback period (per day)

Add correlation to user with long lookback of queries

---

Workbooks/SapMonitor/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook

Fixed issue where the profile ID was set incorrectly, causing alerts to not show up

Fix issue where profile id was set incorrectly

---

Workbooks/Workloads/SQL/Create new profile/CreateNewProfile.armtemplate

remove deploying VMInsights solution as no longer needed if using DCR for data collection.

remove deploying VMInsights solution as no longer needed

---

Workbooks/SapMonitor/SapNetWeaver/SapNetWeaver.workbook

1. Code changes to add a new 'Application' tab for including Short Dump visualization'
2. Validation error message for the user to enable the RFC Metrics
3. Some small query changes in the previously included error messages for other metrics.
4. Logic to hide/show the navigation menu based on the RFC Metrics.
5. Some more code clean up related to the rename 'Performance' to 'EnqueueStatistics'

Adding visualization for NetWeaver - RFC Short Dump Metrics

---

Workbooks/Azure Stack HCI/AtScale/Insights.workbook

I found an issue that multi-value type parameter is not updated when time range changes even if the query depends on it. But, it works with resource picker so it is fixed by just changing type.

Change clusters parameter to resource picker type

---

CODEOWNERS
Workbooks/RedisCache/AtResource/ResourceInsights.workbook
Workbooks/RedisCache/AtScale/Insights.workbook
gallery/rediscache-insights/Azure Monitor.json
gallery/workbook/Azure Monitor.json
gallery/workbook/microsoft.cache-redis.json

* Copy the RedisCache workbooks to new locations to match other
workbooks.
* Update the gallery entries to use the new locations.
* Add the azure-cache-for-redis team as a code owner for both the old
and new locations.
* Update the `id` and `name` properties in the Azure Cache for Redis
gallery files to more closely match the naming styles that other
services use for those properties.
Commits f22208b7, 6631860d, and cef04530 moved the workbooks for
ADXCluster, EventHub, and ServiceBus out of the Workbooks/Insights and
Workbooks/Resource Insights directories into per-team directories. The
RedisCache workbooks had not yet been moved from those old directories
to a per-team directory, so they can now be copied into a per-team
directory.
One reason to copy the workbooks into the new directory …

Update RedisCache workbook locations & CODEOWNERS

---

Workbooks/Workloads/Custom Telegraf/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads/Custom Telegraf/Create new profile/Create new profile.workbook
Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads/SQL/Create new profile/Create new profile.workbook

This change is adding "Australia East" to the list of supported regions. Create New Profile location will new have this new region.
[Use this link to test out this change using private deployment build](https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.localtemplates=true&feature.workloadinsights=true&feature.workbookGalleryRedirect=https%3A%2F%2Farunamanagedappstorage.blob.core.windows.net%2Fwli-ama-alerts-vu%2Fpackage#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/sqlWorkloadInsights)

add AustraliaEast to the static location

---

Workbooks/SapMonitor/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook

Allow alert threshold to be added to the query template
No UI change
Manually tested, saw {AlertThreshold} got replaced with the actual threshold value

Allow threshold to be added to the query template

---

Workbooks/SapMonitor/MsSqlServer/MsSqlServer.workbook
Workbooks/SapMonitor/SapNetWeaver/SapNetWeaver.workbook

Need to hide alerts button as we want to release them all at the same time
Fixed Netweaver alert button to open in context pane

Hide alerts button

---

Workbooks/RedisCache/AtResource/ResourceInsights.workbook
Workbooks/Resource Insights/RedisCache/ResourceInsights.workbook

Because the Azure Cache for Redis used memory metrics track single
values over time, aggregating by sum resulted in graphs that showed
higher than expected values for time granularities larger than 1 minute.
For example, if the used memory for a cache was constant at 100 MB, the
graph showed a value of 200 MB when set to a time granularity of 1
minute and 1 GB when set to a time granularity of 5 minutes.
To solve this issue, change the aggregation type from sum to max. This
results in graphs that show the expected values for all time
granularities. It also aligns the workbook with the at-scale workbook
and the Overview section of Azure Cache for Redis resources in the Azure
portal, which both already aggregate used memory by max.
At the moment, some places in the Azure portal still link …

Change aggregation type to max for used memory

---

Workbooks/RedisCache/AtResource/ResourceInsights.workbook
Workbooks/Resource Insights/RedisCache/ResourceInsights.workbook

* Add display names for the server load, CPU, used memory, and connected
clients tiles to indicate that they show max values.
* Change the tiles for errors, expired keys, and evicted keys to
aggregate by sum to match the larger graphs for those metrics.
* Change the connected clients graph to aggregate by max instead of sum.
Each connected clients data point records the total number of
connected clients, not the change in number of connected clients, so
aggregating by max or by average is typically the most useful option.
Aggregating by max helps reveal temporary spikes of high activity.
* Change the graphs for cache read, cache write, and operations per
second to aggregate by max instead of sum. Each of these metrics
records values in units per second. Although it's tempting to
aggregate …

Change aggregation types for RedisCache metrics

---

.gitattributes

try to get github to detect workbook and cohort files as json.
i see they had `linquist-detectable` but not `=true` ?
maybe that's why this isn't working?

try to get github to detect workbook and cohort files as json

---

Workbooks/SapMonitor/PrometheusOS/PrometheusOS.workbook

* [ * ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
This change was required because of the change in the instance_s field.  It used to be (incorrectly) the IP address of the node, but is now the name of the provider instance.  Unfortunately this caused a problem with existing log analytics instances, that there would be old data as well as new data.  This change simply refines the query to take the newest data.  There should be no visible change to the workbook.

fix query returning old data 

---

Documentation/LegacyAI/PrivateWorkbookConversion.workbook

Previous version was returning the workbook resource id of the private workbook being recovered, which by default then made a new workbook *linked to the old workbook* instead of linked to "Azure Monitor" or the resource the previous private workbook was linked to

fix sourceId, so recovered workbooks are linked to same resource as original

---

Workbooks/Workloads/SQL/Create new profile/Create new profile.workbook

The current region list for monitoring profile is static. DCR has become available in some regions that are not in the list. This PR ensures that DCR can be deployed to all the regions that it's supported in by doing the following:
1. Instead of asking users where the profile should be deployed to, we ask users to pick the LA workspace first.
2. With the LA workspace information we could fetch its location with ARM query and populate the profile location to be the same.
3. This doesn't change the existing behavior since customers can only pick LA workspace in the same profile location they've picked. Users can still pick a different LA workspace later with "Edit Profile"
4. DCR is supported in all regions LA workspace is supported in according to this - …

Enabling creating monitoring profile in all regions DCR is supported in.

---

Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook

Remove the static region filter in the monitoring vm query in the "Add monitoring virtual machine workbook", so customers can choose monitoring vms from a broader list.
Gallery link: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.localtemplates=true&feature.workloadinsights=true&feature.workbookGalleryRedirect=https%3A%2F%2Freadablesecondaries.blob.core.windows.net%2Fazure-monitor-workbook-templates%2Fpackage#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/sqlWorkloadInsights
Monitoring vms in Brazil South and other regions are now available in the list.

Removed static region filters in query for monitoring vms

---

Workbooks/Workloads/SQL/SQL Server/SQL Server.workbook

Some queries in sql server workbook have fix time range regardless of what users select in the time range parameter. This PR fixes those queries to use the time range of users' selection.
Before: the query only returns 1 day worth of data even though the time range is 3 days
After: the query now returns 3 days worth of data
link to gallery: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.localtemplates=true&feature.workloadinsights=true&feature.workbookGalleryRedirect=https%3A%2F%2Freadablesecondaries.blob.core.windows.net%2Fazure-monitor-workbook-templates%2Fpackage#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/sqlWorkloadInsights

Fixed queries in drill down sql server workbooks to use the time range parameter

---

Workbooks/MySQL Flexible Server/Overview/Overview.workbook

Both the metrics were Total connection ... We needed to make one for active connections instead

Add active connection metric to chart in MySQL Overview Workbook

---

CODEOWNERS
Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook

Enforcing usage of Key Vaults in monitoring vm config related workbooks due to security concerns. With this update, users cannot add/update monitoring vm config without giving access to Key Vaults. Added an informational banner asking user to reference passwords from Key Vaults and two error banners when access is not provided.
link to workbooks: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.localtemplates=true&feature.workloadinsights=true&feature.workbookGalleryRedirect=https%3A%2F%2Freadablesecondaries.blob.core.windows.net%2Fazure-monitor-workbook-templates%2Fpackage#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/sqlWorkloadInsights

Enforcing usage of Key Vaults in Add/Update monitoring virtual machine workbooks.

---

scripts/extractStrings.js

Fix locked strings in script, missing quotes around the locked string
Eg. Currently locked strings are reported as "{Locked={newIssuesCnt}}"
Correction: "{Locked="{newIssuesCnt}"}"

Localization locked strings script fix

---

Workbooks/Communication Services/Overview/Overview.workbook

New version of the Azure Communication Services Insights tab
- Followed the Azure Workbooks team's advice and made the text more informational when queries return no results:
- Improved the text descriptions in some sections:
- Added drill-down functionality to improve dashboard navigation experience:
- On grids:
- And on pie charts:
- Added drill-down for specific IDs, users, or meetings:

ACS Insights tab v2

---

Workbooks/Communication Services/Overview/Overview.workbook

Changed hard-coded time range value in **Voice and video** -> **Details** tab that was only showing the call details for calls made in the last 24 hours

Fixed hard-coded time range in Voice and video -> Details tab

---

Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook

Make Key Vaulty optional as per customer feedback. Added link to Key Vault documentation in messages.
link to gallery: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.localtemplates=true&feature.workloadinsights=true&feature.workbookGalleryRedirect=https%3A%2F%2Freadablesecondaries.blob.core.windows.net%2Fazure-monitor-workbook-templates%2Fpackage#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/sqlWorkloadInsights

[SqlInsights] Make KV optional as per customer feedback

---

Workbooks/ADXCluster/AtResource/ResourceInsights.workbook

Streaming Ingest Result metric – now has only “count” aggregation.
Removed the AVG aggregation from the Insights.

ADX Insights - fix Streaming Ingest Result metric - count aggregation

---

Workbooks/CosmosDb/Overview/Overview.workbook

Addressing this open ADO item to remove deprecated metric from Overview page.
https://msazure.visualstudio.com/One/_workitems/edit/12841181 
https://msazure.visualstudio.com/One/_workitems/edit/12841181

Removing deprecated metric from Overview Workbook

---

Workbooks/IoT Central/IoT Edge device details/IoT Edge device details.workbook
Workbooks/IoTHub/IoT Edge device details/IoT Edge device details.workbook

The endTime variable in the time series for the host CPU, memory, disk graphs was including an extra period of time for which we won't have any reported metric (which is then assumed to be zero).  This fixes it to stop at the specified end time.
Try with [https://ms.portal.azure.com/**?feature.workbookGalleryBranch=users%2Fmicahl%2Fgraph-updates**](https://ms.portal.azure.com/?feature.workbookGalleryBranch=users%2Fmicahl%2Fgraph-updates)
**Before**
**After**

Correct the endTime being used to create the time series

---

CODEOWNERS

Add IDC Azure Monitor for sap solutions team as code owners for v2 workbooks and gallery file as well

Add CODEOWNERS for SapMonitor2.0 workbooks

---

Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook

This PR consists of changes in two queries and one minor change in the footer of the workbook. 
- The area chart now shows the work process utilization based on each work-process type, instead of cumulative. 
- The table below will now show the latest active work process according to the time stamp. 
- The footer is updated with proper casing.

Updated the queries for the Worker Process Type on Performance Tab

---

Workbooks/SapMonitor2.0/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook
Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook

This PR consists of following changes on the SapNetWeaver Provider Workbook Template:
- make the SapNetWeaver nomenclature and case to match the ProviderType in the response. 
- Update the Alerts template to show only successful Provider Instances in the list.

Updated Alerts to show successful Provider Instances

---

Workbooks/Synapse/Streaming/Streaming.workbook

Only changing labels and improving the auto-select for application name drop down:

Add the units to the labels

---

Workbooks/SapMonitor2.0/PrometheusOS/PrometheusOS.workbook

Select any one hostname by default in OS provider workbook

Select any one hostname by default

---

Workbooks/Network Insights/VirtualWANWorkbooks/NetworkInsights-VirtualWANMetrics/NetworkInsights-VirtualWANMetrics.workbook

Fix bug where Vnet connection count was always 0 due to change in ARG result of VWan.
Solution: Get the Vnet count through ARM Query

Fix Vnet Connection Count bug in VWan workbook

---

CODEOWNERS

There were users who no longer are valid in github's user info that had codeownership, removed them to keep the file valid.
Its nice that github now has UX for this!

remove invalid users from codeowners file

---

CODEOWNERS
gallery/workbook/Microsoft.ConnectedVehicle-platformAccounts.json

NOTE: CODEOWNERS broken for the gallery file, so need AI team approval.
Remove the preview flag for the workbook that was previously deployed and fix casing in the CODEOWNERS file

remove the preview flag for new ConnectedVehicle workbook

---

Workbooks/Azure Security Center/Coverage/Coverage.workbook

This change will add a filter capability to AWS/GCP tables in the Defender for Cloud Coverage workbook.

adding filter capability to AWS/GCP tables in Coverage workbook

---

Workbooks/Azure Security Center/Coverage/Coverage.workbook

This PR fixes the *relative coverage for Azure subscriptions* table as it didn't show Servers coverage.
It also aligns table headings for AWS and GCP to use the same wording.

fixing table in coverage workbook

---

Workbooks/Azure Security Center/Price Estimation/PriceEstimation.workbook

In case Defender for Containers is enabled, AKS VMSS nodes are exempted from Defender for Servers billing. This change will add a toggle switch to allow setting Defender for Containers on/off when estimating Defender for Servers cost. In addition, we removed the coverage table as this is part of a separate workbook.

updating calculation for Defender for Servers

---

Workbooks/Azure Stack HCI/AtScale/Insights.workbook
Workbooks/Azure Stack HCI/SingleCluster/Cluster.workbook

- RDMA was not shown in the chart as the name of parameter was not correct.
- Added a link of HCI update instructions to drive error message.
- Fix memory column in server tab for 0 total memory

Fix RDMA chart in HCI Insights

---

Workbooks/Azure Security Center/Price Estimation/PriceEstimation.workbook

Defender for App Service calculation was reported to be incorrect. This change fixes calculation to align with actual billing as it is being used in Defender for Cloud's backend.

fixing Defender for App Service calculation

---

Workbooks/Azure Security Center/Coverage/Coverage.workbook

This update adds coverage information for Defender for Databases for AWS and GCP multicloud connectors.

adding coverage for Defender for Databases

---

Workbooks/AKS/Node GPU/Node GPU.workbook

Moving to a tab structure, adding note on GPU migration
GPU metrics collection are being deprecated from the Kubernetes upstream. Added a note in the template to redirect to Container Insights documentation.

GPU metrics deprecation

---

Workbooks/Network Insights/VirtualWANWorkbooks/NetworkInsights-VirtualWANMetrics/NetworkInsights-VirtualWANMetrics.workbook

Fix bug in "Virtual WAN Hub level Status and Capacities" section where the output was not showing due to multiple hidden merge steps.

Fix Virtual WAN Hub level Status and Capacities bug

---

Workbooks/UpdateCompliance/Active alerts/Active alerts.workbook
Workbooks/UpdateCompliance/Feature updates/Feature updates.workbook
Workbooks/UpdateCompliance/Quality updates/Quality Updates.workbook

Modify the active alerts kpi cards in QU and FU

---

Workbooks/RedisCache/GeoReplicationDashboard/GeoReplicationMetrics.workbook

We found a scenario wherein Azure Resource Graph query is not able to sync the linkedserver role post we reverse the roles of caches. Until we figure this out with Azure Resource Graph team, We're removing this filtering based on linkedServer role.

[Workbook Change] Remove filtering based on LinkedServer Role

---

Workbooks/AKS/Subnet IP Usage/Subnet IP Usage.workbook

In the Subnet IP usage Workbook we made the following changes
- Removed the IP usage reserved for future to avoid any confusion to the user.
- For the IPs allocated from Subnet and IPs assigned to Pod, we are currently using bar to show historical view. We added a section to show current time view on the same section 
- We improved the query  
- Below are the screenshot of the changes:
1) Removed "IPs reserved for future Pods" from the list
2) For IPs allocated from Subnet we created two views:
* Current Time view 
* Historical view 
3) For IPs assigned to Pod from Subnet we created two views:
* Current Time view
* Historical view

Revised the UI for the Subnet IP usage Workbook

---

Workbooks/UpdateCompliance/Feature updates/Feature updates.workbook

Fix query in win 11 pie chart in feature update

---

Workbooks/Azure Stack HCI/SingleCluster/Cluster.workbook

- Fixed link type in VM tab which should jump into resource page.

Fix link type in VM

---

Workbooks/SapMonitor2.0/SapLandscapeMonitor/SapLandscapeMonitor.workbook

Increased custom width for alert filters in SAP Landscape monitor workbook.

Updated custom width for alert filters

---

Workbooks/SapMonitor2.0/Alerts/Create Alert rule (step 1 of 2)/Create Alert rule (step 1 of 2).workbook

Moved Provider Instance dropdown outside the current dropdown group.
Made the Provider instance dropdown conditionally visible, hide the dropdown when provider type is HA Cluster.
Updated Headers above the dropdowns.
Alerts Page for HA Alerts 
Alerts Page For other Provider Types

changes to hide provider dropdown

---

CODEOWNERS
Workbooks/Network Security Perimeter/Access Logs/NSP Access Logs Insights.workbook

Objective: To show NSP(Network Security Perimeter) product access logs insights using workbook, so created new workbook template to show the access logs with time range parameter so that users can access the logs.

Added new template for NSP Access logs insights

---

Workbooks/SapMonitor2.0/SapHana/SapHana.workbook

- fix typos (e.g. avaialble-> available)
- check correct filtering in query for timegenerated depending on user's selection in param_timeframe
- in transaction tab correct displaying of note message if there are no data to be displayed + frequency how often new data are fetched
- in System Utilization tab > Memory Service Usage: for empty field in "Tenant Name" add "SYSTEMDB"
- System Utilization - sort desc tenant, time (move to left), and Rename the host column to Service
- Landspace overview - don't show duplicates for hosts, and empty database column
Before:
Now:
- Backup tab shows error if the Backup Type filter is set to "Unset"
- Update Replication site to be filtered based on user's time frame selection

 HANA workbook GA check - fix typos and bugs

---

Workbooks/Database watcher/watcher.workbook

This PR moves a parameter block containing the `watcherResourceId` out of a group so that this parameter can be set by portal when loading the workbook.
* [n/a] post a screenshot of templates and/or gallery changes

[Database watcher] Make watcherResourceId settable externally

---

CODEOWNERS

Update ownership of LA Gallery to include workbooks team so we can unblock changes to the LA Gallery

Update ownership of LA Gallery to include workbooks team

---

gallery/workbook/microsoft.operationalinsights-workspaces.json

Update the titles of the LA workspace templates.  Before they all have "Log Analytics Workspace Insights" in the beginning so you can't tell what they are.  I also re-ordered them so the Insights template is first, then they appear in the same order the tabs appear in the Insights template itself.

Update titles of LA Insights templates

---

Workbooks/Azure Monitor - Workspaces/Prometheus Explorer/Prometheus Explorer.workbook

the chart just uses the default setting and shows 1 series:
use all string columns, split to first 50+others

24185180: update prom explorer template in AMW to use this all string columns setting, high limit for max series

---

Workbooks/SapMonitor2.0/SapNetWeaver/SapNetWeaver.workbook

Description:
1. This PR is a minor bug fix for outbound queue tiles. Ideally to show/hide the outbound queues we need to check the outbound queue parameter, but looks like the code was checking the "inbound queue parameter" and some customers who didn't have any data in outbound queues in the SAP system were seeing the below error in the workbook:
As a part of the fix, we updated the correct parameter to hide/show the tiles and also included proper step names for certain tiles to follow the appropriate nomenclature in the workbook.
IcM - https://portal.microsofticm.com/imp/v3/incidents/details/393660828/home
2. Sub menu for the Queue Statistics tab is currently not displayed today when a customer creates SOAP-only providers and does not have any RFC providers. This PR includes a fix to …

NetWeaver Workbook - Add appropriate param check name for outbound queue tiles and updated logic to show sub menu for queue statistics tab

---

Workbooks/SapMonitor2.0/SapLandscapeMonitor/SapLandscapeMonitor.workbook

- Removed 250 alerts count limit and set limit of 500 for displaying alert details in tabular view
- Added check for 'alert-template-id' tag in alert rule to filter out external alerts created on the same LA workspace
- Set 48 hours as default selection for time range

SPOG - Removed alerts limit and added external alerts filter

---

Workbooks/KeyVault/AzureMonitor/AzureMonitor.workbook

its hidden, always set to all
but it makes an extra unnecessary query to arg to get the RG's for all the subs and makes the queries more complicated
There's no *visible* or functional changes in insights, only when editing:
you can see the "resource groups" all
after, doesn't.

remove the hidden resource group param from keyvault insights

---

Workbooks/SapMonitor2.0/MsSqlServer/MsSqlServer.workbook

Added missing check for AO failover parameter which is used for checking existence for AO Failover table in LAWS.

MSSQL - Added hidden flag for AO failover parameter

---

Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook

1. cd1ec6c8511bd3f561740ba92f92e5dbb88d5a29 Fix Subscription scope for Kubernetes cluster parameter. This fixes the metrics not working if the Packet Core Control Plane does not have an ASE resource.
2. 905bd86e4d9b3dd1f38a3873097f5a6a15a71c42 Make the packet core control plane errors a bar chart instead of a line chart to make it easier to see cumulative errors.
3. 28f57ec49002a2cef4d215c8d4dee1503e2d3d34 Expand SIM policies by default. Modify the SIM policy view so that they are visible without needing to expand. ![image](https://github.com/microsoft/Application-Insights-Workbooks/assets/3382572/ed3498ed-8433-42a3-8f1e-e4278021c7b4)

Some minor PMEC Site Overview improvements

---

Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook

Use maximum rather than average as the aggregation for provisioned subscribers - bringing in line with the other metrics (connected nodeBs, registered/connected subscribers). This wasn't possible previously due to a metrics bug, but this is now fixed. This avoids an issue where provisioned subscribers can show as a decimal value if there are multiple values being aggregated over.

Fix aggregation for provisioned subscribers

---

Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook

Ensure that when the MNC has a leading zero it is displayed in full. Fix a bug where the leading zero was omitted.
With PLMN ID 315 010, old behaviour:
New behaviour:

Fix incorrect PLMN ID display

---

Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook

A couple of small tweaks to the PMEC Site Overview:
* Only show resolved alerts within the timespan, and show which resource the alert was triggered on. Update the filtering to show either alerts that are firing or ones that resolved within the configured timespan. On the all alerts view, show the resource that the alert is firing on. 
* Fix the size of the ASE IP config panel to properly fit the content.

Minor tweaks to alert and ASE IP config views

---

Workbooks/SapMonitor2.0/Alerts/Alerts/Alerts.workbook

Updating the Alert Rule Details Blade.
After clicking on one of the alert rule -

Updating alert rule details blade name

---

Workbooks/Database watcher/Azure SQL Database/database/database.workbook
Workbooks/Database watcher/Azure SQL Database/elastic pool/elastic pool.workbook
Workbooks/Database watcher/Azure SQL Database/estate/estate.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/estate/estate.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/instance/instance.workbook
Workbooks/Database watcher/SQL Server/estate/estate.workbook
Workbooks/Database watcher/SQL Server/instance/instance.workbook
Workbooks/Database watcher/watcher.workbook

This PR changes the API version used to get the properties of the specified watcher resource, from 2023-03-01-preview to 2023-09-01-preview. Reflecting API changes, it also changes how the Kusto cluster URI and database name are derived from the watcher resource properties.
* [n/a] post a screenshot of templates and/or gallery changes

Change API to 2023-09-01-preview

---

Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook

Use a parent-child relationship in the grid to only show values that are at the SIM policy scope once per policy, rather than once per data network.
SIM policies are now displayed like this:
Previously this looked like this:
(note how the Provisioning State is shown three times for MultiDN-Policy, even though it only applies to the top-level SIM policy).

Improve UX of SIM Policies panel

---

Workbooks/SapMonitor2.0/AIOpsInsights/Availability Insights/Auto RCA.workbook
Workbooks/SapMonitor2.0/AIOpsInsights/Performance Insights/Auto Perf RCA.workbook
Workbooks/SapMonitor2.0/AIOpsInsights/SAP AMS.workbook

Changes:
- Multi-VM Flyout: To remove the issue of duplicate alerts, the alerts have been grouped by Providers. The flyout that opens up has multi-vm flyout, where customer can even select the VM to see insights.
- JIT Onboarding: The configuration of infra access is no longer a prerequisite for viewing insights. Only specific areas of the workbook now request configuring.
- Minor bug fixes

Multi-VM Flyout and JIT Onboarding

---

Workbooks/Azure Private MEC/PMEC Site Overview/PMEC Site Overview.workbook

Fix bug where when 1000 SIMs are provisioned it shows up as 1 in the workbook due to the conditional formatting we had set on the tiles.
Before:
After:

Fix display of tiles when value exceeds 1000

---

Workbooks/Azure Center for SAP solutions/ACSS Aggregated/ACSS Aggregated.workbook
Workbooks/Azure Center for SAP solutions/SAP Inventory Checks/SAP Inventory Checks.workbook

- **VM Monitoring Metrics (Last 24 hours):**
Shows the list of VMs for the selected VIS(es), and their health metrics in the past 24 hours.
Since this is a metrics tile which gets the metrics for VMs, I had to find a workaround to add a column for the SID of the VMs. To do that I had to create 2 hidden steps, and then create a 3rd query step in which I'm getting the data by merging the results of the previous 2 steps.
- **Current VM Health & Annotations:**
Shows the list of VMs for the selected VIS(es), and their current health and annotations.
- **VM Health Changes (Last 14 days):**
Shows the list of VMs for the selected VIS(es), and their corresponding health changes in the past 14 days.
I also had to add a parameter **vmIds** to the ACSS_Aggregated workbook, as I had to supply that …

Added VM metrics, VM health, and VM Health Changes tiles to ACSS_Aggregated and SAP_Inventory_Checks workbooks.

---

gallery/workbook/businesscontinuity-insights.json

Adding a new category for Azure Site Recovery to separate out Azure Site Recovery templates from Azure Backup templates in gallery.

Separating out ASR workbooks as different category

---

Workbooks/Azure Monitor - Agents/Agent Migration Tracker/AMA Migration Helper.workbook

Add Azure Automation Update Management Tab to AMA Migration Helper Workbook
- Adding Azure Automation Update Management Tab in the Workbook.
- Update Top-Level Banner to include info about the new Tab.
- In this Tab, Customers will be able to select a Workspace that has "Updates" Solution Enabled.
- Once the Workspace is selected, it will auto-populate the Automation Account.
- Then it will fetch info about all Machines with Updates Solution Enabled Reporting to Log Analytics Workspace.
- Then we will additionally fetch info about Azure and Arc-Enabled Machines from ARG.
- Join the data from above two queries to present two tables in Machines Tab. One Table will have all Azure and Arc Machines while the other table will have all Non-Azure Machines which are not arc-enabled. Please refer …

Add Azure Automation Update Management Tab to AMA Migration Helper Workbook

---

CODEOWNERS
Workbooks/Azure Logic Apps/LA Standard Metrics/LAStandardMetrics.json

This is a workbook for Azure Logic Apps standard that will be referenced from the LA portal in the insights blade.
It was tested by deploying to a custom gallery, and then via `enableWorkbooks` + `apply` on the resource. There are three tabs, describing overview, workflows, and compute.
Please help advise:
- For CODEOWNERS, will an @azure team work? Or do we need to provide a @microsoft one?
- Do we need a gallery file update for our scenario? Or is contributing the workbook sufficient if we reference it directly from the built-in blade?
Feel free to ping me at `karansin`
https://github.com/microsoft/Application-Insights-Workbooks/assets/7775527/d476e644-77d5-4ff9-b9c8-12289b0403b0

Contribute workbook for Azure Logic Apps

---

Workbooks/Communication Services/Overview/Overview.workbook

We have an issue in our Azure Communications Email Service Insights Workbook where our per-instance table shows an aggregated date (bin()). The issue is in the query used to generate this chart. The Date Sent column is using the bin() function to round to the nearest time bucket. This instance level chart should use actual timestamps

Update Overview.workbook update datetime column

---

Workbooks/Azure Logic Apps/FilteredAPIM/FilteredAPIM.workbook
Workbooks/Azure Logic Apps/FilteredServiceBus/FilteredServiceBus.workbook
Workbooks/Azure Logic Apps/Integration Environment/IntegrationEnvironment.workbook
Workbooks/Azure Logic Apps/IntegrationLogicApps/IntegrationLogicApps.workbook

This PR adds a 'report' workbook for integration spaces. These will be referenced using the WorkbookViewerBlade in a new Insights tab.
Integration spaces allow users to group several resources together, so the workbook embeds information about the enclosed logic apps, APIMs, and ServiceBus instances. The inner workbooks were generated by adding entity-filtering to the existing workbooks for those resources (users configure specific entities as part of their integration space). Each resource has its own workbook file, and the top-level workbook includes the others as templates.
Users must select the application insights instance connected to their resource. This should be improved in the future as we find a way to enforce it programmatically in UX; but until then, this will get the …

Add workbooks for Logic Apps AIS (Integrate)

---

Workbooks/SapMonitor2.0/AIOpsInsights/Availability Insights/Auto RCA.workbook
Workbooks/SapMonitor2.0/AIOpsInsights/SAP AMS.workbook

Bug:
Solution: Added table exists check and did a conditional render.
Solution: removed column Application Server:

Remove dependency from VIS

---

Workbooks/Database watcher/watcher.workbook

- Add text in the `Data store` group to provide data store connection status and informational messages to explain why connection to the data store isn't attempted.
- Revert a previous change and move the "data store inaccessible" message back into the `Data store` group, to avoid showing it incorrectly while the connection is still being opened.
 

Add data store connection status

---

Workbooks/Windows Virtual Desktop/AtScale/Overview/Overview.workbook
Workbooks/Windows Virtual Desktop/shared/Template Versioning Footer/Template Versioning Footer.workbook

On the "Overview" page, change the name from "Azure Stack HCI" to "Azure Local".
https://ms.portal.azure.com/?feature.workbookGalleryBranch=xixiao%2FchangeHCINaming#view/Microsoft_Azure_WVD/WvdManagerMenuBlade/~/insights

Change Azure Stack HCI naming convention to Azure Local

---

Workbooks/Database watcher/Azure SQL Database/database/activity/activity.workbook
Workbooks/Database watcher/Azure SQL Database/elastic pool/activity/activity.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/instance/activity/activity.workbook
Workbooks/Database watcher/SQL Server/instance/activity/activity.workbook

The tempdb allocation and consumption columns in the Activity grid are displayed as plain numbers.
Use byte units and grouping separators.

Use byte units and separators for tempdb consumption

---

Workbooks/Database watcher/Azure SQL Database/database/database.workbook
Workbooks/Database watcher/Azure SQL Database/database/top queries/top queries.workbook
Workbooks/Database watcher/Azure SQL Database/estate/estate.workbook
Workbooks/Database watcher/Azure SQL Database/estate/top queries/top queries.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/estate/estate.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/estate/top queries/top queries.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/instance/instance.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/instance/top queries/top queries.workbook
Workbooks/Database watcher/SQL Server/estate/estate.workbook
Workbooks/Database watcher/SQL Server/estate/top queries/top queries.workbook
Workbooks/Database watcher/SQL Server/instance/instance.workbook
Workbooks/Database watcher/SQL Server/instance/top queries/top queries.workbook

When there is no data on the `Top queries` dashboards, show info messages if Query Store isn't collecting or when the replica type isn't supported.

[database watcher] Add info messages when top queries aren't shown for known reasons

---

Workbooks/Database watcher/watcher.workbook

When the free ADX cluster is close to running out of space quota, show a warning based on the compressed size (which is the enforced limit), instead of a warning based on the approximate and not enforced original data size.

[database watcher] Use free ADX compressed size limit in data store warning

---

Workbooks/Database watcher/Azure SQL Database/database/georeplicas/georeplicas.workbook
Workbooks/Database watcher/Azure SQL Database/database/storage/storage.workbook
Workbooks/Database watcher/Azure SQL Database/elastic pool/storage/storage.workbook
Workbooks/Database watcher/Azure SQL Managed Instance/instance/databases/databases.workbook

Add a `Max data`/`Max log` series to storage consumption charts.

[database watcher] Improve storage utilization charts to show maximum storage size

---

Workbooks/Workloads/SQL/SQL Server Insights/SQL Server Insights.workbook

SQL Insights has been deprecated on 31 Dec 2024 - updating the retirement content

Update retirement text for sql insights

---

gallery/workbook/Azure Monitor.json
gallery/workload-insights/Azure Monitor.json

SQL Insights officially got retired on 31 December 2024. Removing its reference from workbook insights gallery
Validated, no SQL Insights under "Insights" gallery

Remove sql insights from workbook gallery

---

Workbooks/Azure SQL VM/SQL Assessment/SQL Assessment.workbook

Resolving accessibility bug: Text visually appearing as heading is not defined as heading programmatically under "Trends" tab.
SQL VM BPA Workbook: Add h3 tag for section headers
Section headers like "Total issues" are not programmatically defined as heading: 
Section headers now have proper h3 tag applied:

SQL VM BPA Workbook: Add h3 tag for section headers

---

Workbooks/Online Experimentation/Experiment Analysis/Experiment Analysis.workbook

- Experiment dropout currently sort experiments by end time, which in cases like the second iteration end earlier than the first iteration (due to different duration settings), it will makes iteration 1 comes first in the drop down.
- Fixed by sorting them in analysis start time.

[Online experimentation analysis] Sort experiment dropdown by analysis's start time (iteration)

---

Workbooks/Azure Security Center/Containers Security/Containers Security.workbook

Changing the subscription filter to only show default subscriptions instead of all subscriptions
Changed the subscription filter so that it reflects the default subscriptions instead of all subscriptions in the tenant

Update Containers Security.workbook

---

Workbooks/Azure Monitor - Workspaces/Metrics Usage Insights/Metrics Usage Insights.workbook

Fix incorrect DS warning message in workbooks- account exploration, unused metrics

---

Workbooks/Azure Monitor - Workspaces/Metrics Usage Insights/Metrics Usage Insights.workbook

Based on the feedback from the demo this morning, after checking with the PM, changing the error to a warning for the missing diagnostic setting message in the Metrics Usage Insights workbook is the right approach.

Change missing diagnostic setting message to a warning

---

Workbooks/Azure Machine Learning/AI Studio/FoundryDashboard/FoundryDashboard.workbook

This PR adds the inline step toolbar buttons to the Foundry dashboard:

🔧 Add inline step toolbar buttons to Foundry Dashboard

---

Workbooks/Online Experimentation/Experiment Analysis/Experiment Analysis.workbook
Workbooks/Online Experimentation/Experiment Status/Experiment Status.workbook

- Add label filter to online experimentation workbook
- Swtich to AppEvent in dropdown to enable system prompt and label be picked up faster when assignment is not summarized.

Add label filter to online experimentation workbook

---

Workbooks/CosmosDb Fleet/Overview.workbook
Workbooks/CosmosDb/Overview/Overview.workbook

https://msazure.visualstudio.com/One/_workitems/edit/33409794
Right now you have the links inside the Azure Advisor Recommendations  opening up a menu blade in a side context pane. This causes  alot of weird portal issues as the portal doesn't expect menu items to be opened in a context pane. Making change for link to open in a full window instead.
When done correctly, this means that from then on *your* team does reviews of *your* things, …

updating in context pane to false

---

CODEOWNERS
Workbooks/CosmosDb Mongo vCore/Overview/Overview.workbook

Solves customer IcM where they couldn't edit their metrics by time range
There was a metrics display issue within the Insights dashboard where, despite metrics data flowing correctly, the dashboard fails to expand the selected time range beyond one hour.
Before fix (from IcM):
After fix (different dataset):
Validated using Advanced Editor

Updating vCore CODEOWNERS and fixing vCore Insights workbook

---

Workbooks/PostgreSQL Flexible Server/Performance/Query Performance Insights/Query Performance Insights.workbook

Use time legend for x axes in QPI workbooks

Use time legend for x axes in QPI workbooks
